package arb.expressions;

import java.util.HashMap;
import java.util.concurrent.atomic.AtomicReference;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import arb.functions.Function;

/**
 * Custom {@link ClassLoader} for arb4j dynamically-compiled {@link Expression}
 * implementations.
 *
 * <p>
 * Bytecodes produced by {@link Expression#generate()} are registered via
 * {@link #registerBytecodes(String, byte[])} before {@link #loadClass(String)}
 * is called. The standard {@link ClassLoader#loadClass} contract applies:
 * parent delegation runs first, so any class already present on the classpath
 * (e.g. pre-compiled by the arb4j Maven plugin) is returned directly without
 * ever calling {@link #findClass}, preventing duplicate class definition.
 *
 * @author Stephen Crowley ©2024-2025
 * @see arb.documentation.BusinessSourceLicenseVersionOnePointOne © terms
 */
public class ExpressionClassLoader extends
                                   ClassLoader
{

  private final static Logger            log              = LoggerFactory.getLogger(ExpressionClassLoader.class);

  /**
   * Classes that have been defined by this loader, keyed by binary name.
   */
  public final HashMap<String, Class<?>> compiledClasses  = new HashMap<>();

  public final Context                   context;

  public ExpressionClassLoader(Context context)
  {
    assert context != null : "context shan't be null";
    this.context = context;
  }

  /**
   * Defines a class directly from ASM bytecode, returning the defined Class
   * object. Replaces the prior register-bytecodes-then-loadClass flow with
   * a one-shot defineClass call; the round-trip through pendingBytecodes
   * and {@link #findClass} that flow required is what allowed re-entrant
   * findClass calls (triggered by JVM field-type resolution) to fall into
   * the {@code functionMapping.instantiate()} branch and recompile a class
   * mid-definition. With this method the bytecode is defined immediately;
   * subsequent {@link #findClass} calls hit the {@link #compiledClasses}
   * cache or fail.
   *
   * @param internalName slash-form internal name of the class
   *                     (e.g. {@code "arb/jacobi/P"}); matches what
   *                     {@link org.objectweb.asm.ClassWriter#visit
   *                     ClassWriter.visit} writes into the bytecode
   * @param bytecodes    ASM-generated bytecodes
   * @return the defined {@link Class}
   */
  public Class<?> defineClassDirectly(String internalName, byte[] bytecodes)
  {
    String binaryName = internalName.replace('/', '.');
    Class<?> already = compiledClasses.get(binaryName);
    if (already != null)
    {
      return already;
    }
    Class<?> defined = defineClass(binaryName, bytecodes, 0, bytecodes.length);
    compiledClasses.put(binaryName, defined);
    return defined;
  }

  /**
   * Called by {@link ClassLoader#loadClass} only after parent delegation has
   * already failed to locate the class. Returns a class previously defined
   * by {@link #defineClassDirectly(String, byte[])}, or a known function
   * class registered in {@link Context#functions}, lazily compiling the
   * mapping's expression if needed. The lazy compile is guarded against
   * re-entrance on the same Expression instance via
   * {@link Expression#compileInProgress}: while one Expression is mid-
   * compile, a JVM-driven findClass lookup that resolves to that same
   * Expression returns the placeholder Function interface class instead
   * of triggering a recursive compile.
   *
   * @throws ClassNotFoundException if no defined class, no instantiated
   *                                FunctionMapping, and no Expression
   *                                available to compile under the given
   *                                name
   */
  @Override
  @SuppressWarnings("unchecked")
  protected Class<?> findClass(String name) throws ClassNotFoundException
  {
    if (Expression.trace)
    {
      log.debug("findClass('{}') in Context#{}", name, System.identityHashCode(context));
    }

    Class<?> already = compiledClasses.get(name);
    if (already != null)
    {
      if (Expression.trace)
      {
        log.debug("findClass('{}') returning already-defined class from compiledClasses", name);
      }
      return already;
    }

    FunctionMapping<Object, Object, Function<? extends Object, ? extends Object>> functionMapping = context.getFunctionMapping(name);
    if (functionMapping != null)
    {
      if (Expression.trace)
      {
        log.debug("findClass('{}') found mapping instance={} expression={}", name, functionMapping.instance, functionMapping.expression);
      }
      if (functionMapping.instance == null && functionMapping.expression != null)
      {
        // #1027 fix: skip the recursive instantiate() when this mapping's
        // Expression is already mid-compile (compileInProgress=true). The
        // re-entrant findClass call is coming from a JVM-driven field-type
        // resolution during the outer compile; returning the functionClass
        // (an interface or super-type the field can be typed as) breaks
        // the cycle. The outer compile will finish, define the class, and
        // subsequent lookups will hit compiledClasses.
        if (!functionMapping.expression.compileInProgress)
        {
          if (Expression.trace)
          {
            log.debug("findClass('{}') calling instantiate() to compile operand expression", name);
          }
          functionMapping.instantiate();
        }
        else if (Expression.trace)
        {
          log.debug("findClass('{}') skipping instantiate(); compileInProgress", name);
        }
      }
      Class<?> t = functionMapping.type();
      if (Expression.trace)
      {
        log.debug("findClass('{}') returning type={}", name, t);
      }
      return t;
    }

    AtomicReference<Class<?>> mappedClassReference = new AtomicReference<Class<?>>();
    context.functions.values().forEach(mapping ->
    {
      if (name.equals(mapping.functionName) || name.equals(mapping.functionClass.getName()))
      {
        assert mappedClassReference.get() == null : "mappedClassReference is already mapped to " + mapping;
        mappedClassReference.set(mapping.functionClass);

        if (Expression.trace)
        {
          log.debug("Mapped {} to {}", mapping, name);
        }
      }
    });

    Class<?> mappedClass = mappedClassReference.get();
    if (mappedClass != null)
    {
      return mappedClass;
    }

    throw new ClassNotFoundException(name);
  }

  @Override
  public String toString()
  {
    return String.format("ExpressionClassLoader[compiledClasses=%s, context=%s]", compiledClasses, context);
  }
}
