package arb.expressions;

import arb.Complex;
import arb.Initializable;
import arb.Integer;
import arb.Real;
import arb.documentation.BusinessSourceLicenseVersionOnePointOne;
import arb.documentation.TheArb4jLibrary;
import arb.functions.Function;
import arb.functions.IndexCache;
import arb.functions.complex.ComplexFunction;
import arb.functions.integer.ComplexFunctionSequence;
import arb.functions.integer.RealSequence;
import arb.functions.integer.Sequence;
import junit.framework.TestCase;

/**
 * Canonical two-way mutual recursion. The pair f, g references each other
 * through the integer index n, with closed-form values:
 *
 * <pre>
 * f(0) = 1,  f(n) = g(n-1) + 1
 * g(0) = 1,  g(n) = f(n-1) + 2
 *
 * f(1) = g(0) + 1 = 2
 * g(1) = f(0) + 2 = 3
 * f(2) = g(1) + 1 = 4
 * g(2) = f(1) + 2 = 4
 * </pre>
 *
 * This test exists so the generated bytecode for a minimal mutual-recursive
 * cluster can be saved, decompiled and inspected.
 *
 * @see BusinessSourceLicenseVersionOnePointOne © terms of the
 *      {@link TheArb4jLibrary}
 */
public class MutualRecursionTest extends TestCase
{

  /**
   * Hand-written, decompiler-shaped version of the same cluster. The only
   * semantic difference from the generated f/g classes is that peer references
   * are wired by direct assignment before {@code initialize()} runs; the
   * generated classes instead emit a runtime {@code
   * context.lookupFunctionInstance("f")} fallback in {@code initialize()}.
   */
  public static class CanonicalF implements RealSequence, AutoCloseable
  {
    public boolean                     isInitialized;
    private final IndexCache<Real>     cache = new IndexCache<>();
    private final Integer              c0    = new Integer("0");
    private final Integer              c1    = new Integer("1");
    public RealSequence                g;
    private final Real                 tmp   = new Real();
    private final Integer              nTmp  = new Integer();

    @Override
    public Class<Integer> domainType()
    {
      return Integer.class;
    }

    @Override
    public Class<Real> coDomainType()
    {
      return Real.class;
    }

    @Override
    public synchronized Real evaluate(Integer n, int order, int bits, Real result)
    {
      if (!isInitialized)
      {
        initialize();
      }
      Real cached = (Real) Function.peek(cache, n);
      if (cached != null)
      {
        result.set(cached);
        return result;
      }
      switch (n.getSignedValue())
      {
      case 0:
        result.set(c1);
        break;
      default:
        ((Real) g.evaluate(n.sub(c1, bits, nTmp), order, bits, tmp)).add(c1, bits, result);
      }
      Real stored = new Real();
      stored.set(result);
      Function.poke(cache, n, stored);
      return result;
    }

    public void initialize()
    {
      if (isInitialized)
      {
        throw new AssertionError("Already initialized");
      }
      if (g == null)
      {
        throw new AssertionError("g is null");
      }
      isInitialized = true;
    }

    @Override
    public void close()
    {
      c0.close();
      c1.close();
      tmp.close();
      nTmp.close();
    }

    @Override
    public RealSequence derivative()
    {
      throw new UnsupportedOperationException();
    }

    @Override
    public RealSequence integral()
    {
      throw new UnsupportedOperationException();
    }

    @Override
    public String typeset()
    {
      return toString();
    }

    @Override
    public String toString()
    {
      return "f:n➔when(n=0,1,else,g(n-1)+1)";
    }
  }

  public static class CanonicalG implements RealSequence, AutoCloseable
  {
    public boolean                     isInitialized;
    private final IndexCache<Real>     cache = new IndexCache<>();
    private final Integer              c0    = new Integer("0");
    private final Integer              c1    = new Integer("1");
    private final Integer              c2    = new Integer("2");
    public CanonicalF                  f;
    private final Real                 tmp   = new Real();
    private final Integer              nTmp  = new Integer();

    @Override
    public Class<Integer> domainType()
    {
      return Integer.class;
    }

    @Override
    public Class<Real> coDomainType()
    {
      return Real.class;
    }

    @Override
    public synchronized Real evaluate(Integer n, int order, int bits, Real result)
    {
      if (!isInitialized)
      {
        initialize();
      }
      Real cached = (Real) Function.peek(cache, n);
      if (cached != null)
      {
        result.set(cached);
        return result;
      }
      switch (n.getSignedValue())
      {
      case 0:
        result.set(c1);
        break;
      default:
        ((Real) f.evaluate(n.sub(c1, bits, nTmp), order, bits, tmp)).add(c2, bits, result);
      }
      Real stored = new Real();
      stored.set(result);
      Function.poke(cache, n, stored);
      return result;
    }

    public void initialize()
    {
      if (isInitialized)
      {
        throw new AssertionError("Already initialized");
      }
      if (f == null)
      {
        throw new AssertionError("f is null");
      }
      isInitialized = true;
    }

    @Override
    public void close()
    {
      c0.close();
      c1.close();
      c2.close();
      tmp.close();
      nTmp.close();
    }

    @Override
    public RealSequence derivative()
    {
      throw new UnsupportedOperationException();
    }

    @Override
    public RealSequence integral()
    {
      throw new UnsupportedOperationException();
    }

    @Override
    public String typeset()
    {
      return toString();
    }

    @Override
    public String toString()
    {
      return "g:n➔when(n=0,1,else,f(n-1)+2)";
    }
  }

  public static void testCompiledMutualRecursion()
  {
    Context ctx = new Context();
    ctx.declare("g", Integer.class, Real.class, RealSequence.class);

    RealSequence f = RealSequence.express("f:n➔when(n=0,1,else,g(n-1)+1)", ctx);
    RealSequence g = RealSequence.express("g:n➔when(n=0,1,else,f(n-1)+2)", ctx);

    try (Real value = new Real())
    {
      assertEquals("1", f.evaluate(new Integer("0"), 0, 128, value).toString());
      assertEquals("1", g.evaluate(new Integer("0"), 0, 128, value).toString());
      assertEquals("2", f.evaluate(new Integer("1"), 0, 128, value).toString());
      assertEquals("3", g.evaluate(new Integer("1"), 0, 128, value).toString());
      assertEquals("4", f.evaluate(new Integer("2"), 0, 128, value).toString());
      assertEquals("4", g.evaluate(new Integer("2"), 0, 128, value).toString());
    }
  }

  public static void testHandWrittenMutualRecursion()
  {
    try (CanonicalF f = new CanonicalF();
         CanonicalG gShadow = new CanonicalG();
         CanonicalG g = new CanonicalG();
         CanonicalF fShadow = new CanonicalF();
         Real value = new Real())
    {
      // Separate-instance wiring: the canonical f refers to a distinct g
      // instance, and the canonical g refers to a distinct f instance.  Each
      // shadow points back to its canonical partner, so the recursion
      // alternates between two buffers instead of aliasing the same instance.
      f.g = gShadow;
      gShadow.f = f;
      g.f = fShadow;
      fShadow.g = g;

      assertEquals("1", f.evaluate(new Integer("0"), 0, 128, value).toString());
      assertEquals("1", g.evaluate(new Integer("0"), 0, 128, value).toString());
      assertEquals("2", f.evaluate(new Integer("1"), 0, 128, value).toString());
      assertEquals("3", g.evaluate(new Integer("1"), 0, 128, value).toString());
      assertEquals("4", f.evaluate(new Integer("2"), 0, 128, value).toString());
      assertEquals("4", g.evaluate(new Integer("2"), 0, 128, value).toString());
    }
  }

  /**
   * Nested-function mutual recursion equivalent to the a/S cluster that
   * previously exposed cycle-initialization defects. Both a and S are indexed
   * functions of k returning a function of v.
   */
  public static void testCompiledNestedMutualRecursion()
  {
    Context ctx = new Context();
    ctx.declare("a", Integer.class, ComplexFunction.class, ComplexFunctionSequence.class);
    Sequence.compile("S", ComplexFunction.class, "S:k➔v➔a(k-1)(v)·a(k-1)(v)", ComplexFunctionSequence.class, ctx);

    ComplexFunctionSequence a = ComplexFunctionSequence.express("a:k➔v➔when(k=1,v,else,S(k)(v))", ctx);

    try (Integer k = new Integer("2"); Complex v = new Complex(); Complex out = new Complex())
    {
      v.set(2, 0);
      ComplexFunction a2 = a.evaluate(k, 1, 128, null);
      a2.evaluate(v, 1, 128, out);
      assertEquals("4", out.toString());
    }
  }

  /**
   * Hand-written, separate-instance version of the nested a/S cluster.
   * Canonical a and S each point to a distinct shadow peer, breaking the
   * direct object cycle and giving each level its own scratch buffers while
   * still alternating back to the canonical instance for memoization.
   */
  public static class CanonicalA implements ComplexFunctionSequence, AutoCloseable, Initializable
  {
    public boolean                       isInitialized;
    private final IndexCache<ComplexFunction> cache = new IndexCache<>();
    public CanonicalS                    S;
    private final Integer                c1   = new Integer("1");

    @Override
    public Class<Integer> domainType()
    {
      return Integer.class;
    }

    @Override
    public Class<ComplexFunction> coDomainType()
    {
      return ComplexFunction.class;
    }

    @Override
    public synchronized ComplexFunction evaluate(Integer k, int order, int bits, ComplexFunction result)
    {
      if (!isInitialized)
      {
        initialize();
      }
      ComplexFunction cached = Function.peek(cache, k);
      if (cached != null)
      {
        return cached;
      }
      CanonicalAfunc func = new CanonicalAfunc();
      if (func.k == null)
      {
        func.k = new Integer();
      }
      func.k.set(k);
      func.S = this.S;
      func.initialize();
      Function.poke(cache, k, func);
      return func;
    }

    @Override
    public void initialize()
    {
      if (isInitialized)
      {
        throw new AssertionError("Already initialized");
      }
      if (S == null)
      {
        throw new AssertionError("S is null");
      }
      isInitialized = true;
    }

    @Override
    public void close()
    {
      c1.close();
    }

    @Override
    public String typeset()
    {
      return toString();
    }

    @Override
    public String toString()
    {
      return "a:k➔v➔when(k=1,v,else,S(k)(v))";
    }
  }

  public static class CanonicalAfunc implements ComplexFunction, AutoCloseable, Initializable
  {
    public boolean        isInitialized;
    private Complex       lastV;
    private Complex       cachedResult;
    public final Integer  c1 = new Integer("1");
    public CanonicalS     S;
    public Integer        k;

    @Override
    public Class<Complex> domainType()
    {
      return Complex.class;
    }

    @Override
    public Class<Complex> coDomainType()
    {
      return Complex.class;
    }

    @Override
    public synchronized Complex evaluate(Complex v, int order, int bits, Complex result)
    {
      if (!isInitialized)
      {
        initialize();
      }
      if (order > 1)
      {
        throw new UnsupportedOperationException("derivatives not supported");
      }
      if (lastV != null && lastV.equals(v) && cachedResult != null)
      {
        return result.set(cachedResult);
      }
      if (lastV == null)
      {
        lastV = new Complex();
      }
      lastV.set(v);
      switch (k.getSignedValue())
      {
      case 1:
        result.set(v);
        break;
      default:
        ComplexFunction sFunc = S.evaluate(k, order, bits, null);
        result = sFunc.evaluate(v, order, bits, result);
      }
      if (cachedResult == null)
      {
        cachedResult = new Complex();
      }
      cachedResult.set(result);
      return result;
    }

    @Override
    public void initialize()
    {
      if (isInitialized)
      {
        throw new AssertionError("Already initialized");
      }
      if (S == null)
      {
        throw new AssertionError("S is null");
      }
      isInitialized = true;
    }

    @Override
    public void close()
    {
      c1.close();
      if (lastV != null)
      {
        lastV.close();
      }
      if (cachedResult != null)
      {
        cachedResult.close();
      }
    }

    @Override
    public String typeset()
    {
      return toString();
    }

    @Override
    public String toString()
    {
      return String.format("afunc:v➔when(%s=1,v,else,S(%s)(v))", String.valueOf(k));
    }
  }

  public static class CanonicalS implements ComplexFunctionSequence, AutoCloseable, Initializable
  {
    public boolean                       isInitialized;
    private final IndexCache<ComplexFunction> cache = new IndexCache<>();
    public CanonicalA                    a;
    private final Integer                c1   = new Integer("1");

    @Override
    public Class<Integer> domainType()
    {
      return Integer.class;
    }

    @Override
    public Class<ComplexFunction> coDomainType()
    {
      return ComplexFunction.class;
    }

    @Override
    public synchronized ComplexFunction evaluate(Integer k, int order, int bits, ComplexFunction result)
    {
      if (!isInitialized)
      {
        initialize();
      }
      ComplexFunction cached = Function.peek(cache, k);
      if (cached != null)
      {
        return cached;
      }
      CanonicalSfunc func = new CanonicalSfunc();
      if (func.k == null)
      {
        func.k = new Integer();
      }
      func.k.set(k);
      func.a = this.a;
      func.initialize();
      Function.poke(cache, k, func);
      return func;
    }

    @Override
    public void initialize()
    {
      if (isInitialized)
      {
        throw new AssertionError("Already initialized");
      }
      if (a == null)
      {
        throw new AssertionError("a is null");
      }
      isInitialized = true;
    }

    @Override
    public void close()
    {
      c1.close();
    }

    @Override
    public String typeset()
    {
      return toString();
    }

    @Override
    public String toString()
    {
      return "S:k➔v➔(a(k-1)(v))*(a(k-1)(v))";
    }
  }

  public static class CanonicalSfunc implements ComplexFunction, AutoCloseable, Initializable
  {
    public boolean        isInitialized;
    private Complex       lastV;
    private Complex       cachedResult;
    public final Integer  c1 = new Integer("1");
    public CanonicalA     a;
    public Integer        k;
    private final Complex tmpC1 = new Complex();
    private final Complex tmpC2 = new Complex();
    private final Integer tmpN1 = new Integer();
    private final Integer tmpN2 = new Integer();

    @Override
    public Class<Complex> domainType()
    {
      return Complex.class;
    }

    @Override
    public Class<Complex> coDomainType()
    {
      return Complex.class;
    }

    @Override
    public synchronized Complex evaluate(Complex v, int order, int bits, Complex result)
    {
      if (!isInitialized)
      {
        initialize();
      }
      if (order > 1)
      {
        throw new UnsupportedOperationException("derivatives not supported");
      }
      if (lastV != null && lastV.equals(v) && cachedResult != null)
      {
        return result.set(cachedResult);
      }
      if (lastV == null)
      {
        lastV = new Complex();
      }
      lastV.set(v);
      ComplexFunction a1 = a.evaluate(k.sub(c1, bits, tmpN1), order, bits, null);
      Complex r1 = a1.evaluate(v, order, bits, tmpC1);
      ComplexFunction a2 = a.evaluate(k.sub(c1, bits, tmpN2), order, bits, null);
      Complex r2 = a2.evaluate(v, order, bits, tmpC2);
      r1.mul(r2, bits, result);
      if (cachedResult == null)
      {
        cachedResult = new Complex();
      }
      cachedResult.set(result);
      return result;
    }

    @Override
    public void initialize()
    {
      if (isInitialized)
      {
        throw new AssertionError("Already initialized");
      }
      if (a == null)
      {
        throw new AssertionError("a is null");
      }
      isInitialized = true;
    }

    @Override
    public void close()
    {
      c1.close();
      tmpC1.close();
      tmpC2.close();
      tmpN1.close();
      tmpN2.close();
      if (lastV != null)
      {
        lastV.close();
      }
      if (cachedResult != null)
      {
        cachedResult.close();
      }
    }

    @Override
    public String typeset()
    {
      return toString();
    }

    @Override
    public String toString()
    {
      return String.format("Sfunc:v➔(a(%s-1)(v))*(a(%s-1)(v))", String.valueOf(k));
    }
  }

  public static void testHandWrittenNestedMutualRecursion()
  {
    try (CanonicalA a = new CanonicalA();
         CanonicalS shadowS = new CanonicalS();
         CanonicalS S = new CanonicalS();
         CanonicalA shadowA = new CanonicalA();
         Integer k = new Integer("2");
         Complex v = new Complex();
         Complex out = new Complex())
    {
      // Separate-instance wiring for the nested cluster: canonical a refers to
      // a distinct S instance, and canonical S refers to a distinct a instance.
      // Each shadow points back to its canonical partner.
      a.S = shadowS;
      shadowS.a = a;
      S.a = shadowA;
      shadowA.S = S;

      v.set(2, 0);

      ComplexFunction a2 = a.evaluate(k, 1, 128, null);
      a2.evaluate(v, 1, 128, out);
      assertEquals("4", out.toString());

      ComplexFunction S2 = S.evaluate(k, 1, 128, null);
      S2.evaluate(v, 1, 128, out);
      assertEquals("4", out.toString());
    }
  }

}
