package arb.functions.complex;

import arb.Complex;
import arb.ComplexFunction;
import arb.ComplexFunctionSequence;
import arb.ComplexMatrix;
import arb.ComplexPolynomial;
import arb.ComplexPolynomialSequence;
import arb.Integer;
import arb.Real;
import arb.functions.integer.ComplexSequence;
import arb4j.expression.Expression;
import arb4j.expression.compiler.ExpressionCompiler;
import arb4j.expression.compiler.context.Context;
import arb4j.expression.compiler.context.Variable;
import arb4j.expression.compiler.variable.VariableReference;
import arb4j.util.PrecisionExhaustedException;
import arb.solvers.exceptions.HankelDegeneracyException;
import java.util.ArrayList;
import java.util.List;

/**
 * Müntz–Padé approximant for the fractional Riccati equation.
 *
 * <p>
 * Computes the diagonal Padé approximant $[M/M]$ of the transformed function
 * $f(\xi) = \sum_{n=0}^\infty a_n \xi^n$ where $\xi = z^\alpha$, using the
 * Puiseux coefficient sequence generated by the fractional recursion.
 *
 * <p>
 * Maintains the inverse of the nested Hankel family
 * $H_M(i,j) = a_{i+j+1}$ for $0 \le i,j < M$ via Sherman–Morrison rank-1
 * updates as $M$ grows. The approximant is evaluated via the exact stopping
 * criterion $B_M(\xi) = |\Delta_M|^2 / (|\Delta_{M-1}| - |\Delta_M|) < \varepsilon$
 * with pre-asymptotic guard.
 */
public class MuntzPadeApproximant implements AutoCloseable {

  private final ComplexSequence a;
  private final int prec;
  private final Real alpha;
  private final Context context;

  private final ComplexPolynomialSequence Φden;
  private final ComplexPolynomialSequence Φnum;
  private final ComplexFunctionSequence Φ;

  // Hankel inverse hierarchy: invs.get(m-1) holds H_m^{-1} for m >= 1
  private final List<ComplexMatrix> invs = new ArrayList<>();

  // Working vectors for bordered update
  private ComplexMatrix uVec;
  private ComplexMatrix vVec;

  // Scalar scratch
  private final Complex s = new Complex();
  private final Complex alphaScalar = new Complex();
  private final Complex tmp = new Complex();

  // Evaluation temporaries
  private final Complex z = new Complex();
  private final Complex valM = new Complex();
  private final Complex valMm1 = new Complex();
  private final Complex valMm2 = new Complex();
  private final Complex deltaM = new Complex();
  private final Complex deltaMm1 = new Complex();
  private final Complex num = new Complex();
  private final Complex denom = new Complex();
  private final Complex bound = new Complex();
  private final Complex diff = new Complex();

  private boolean closed = false;

  public MuntzPadeApproximant(ComplexSequence a, Real alpha, int prec) {
    this.a = a;
    this.alpha = alpha;
    this.prec = prec;

    this.context = new Context();
    Variable M = context.declareVariable("M", Integer.class);
    Variable zVar = context.declareVariable("z", Complex.class);
    context.registerVariable(new VariableReference<>("a", ComplexSequence.class, a));
    context.registerVariable(new VariableReference<>("qSeq", ComplexPolynomialSequence.class, this::buildDenominatorPolynomial));

    // Φden is Q_M(z) = 1 + q_1·z + ... + q_M·z^M
    this.Φden = ComplexPolynomialSequence.express("Φden:M➔z*qSeq(M)+1", context);

    // Φnum is the Padé numerator P_M(z) with p_n = a_n + sum_{j=1}^n q_j·a_{n-j}
    this.Φnum = ComplexPolynomialSequence.express(
        "Φnum:M➔sum(n➔(a(n+1)+sum(j➔qSeq(M)[j-1]*a(n-j+1){j=1..n}))*z^n{n=0..M})", context);

    // Padé approximant R_M(z) = P_M(z) / Q_M(z)
    this.Φ = ComplexFunctionSequence.express("Φ:M➔z➔Φnum(M)(z)/Φden(M)(z)", context);
  }

  /* ── Hankel inverse maintenance ─────────────────────────────────────── */

  private void growTo(int M) {
    if (invs.isEmpty()) {
      bootstrap();
    }
    while (invs.size() < M) {
      growOnce();
    }
  }

  private void bootstrap() {
    Complex h11 = a.apply(1);
    if (h11.isZero()) {
      throw new HankelDegeneracyException("Singular Hankel at order 1: a_1 = 0");
    }
    ComplexMatrix inv = ComplexMatrix.newMatrix(1, 1);
    tmp.one().div(h11, prec, inv.get(0, 0));
    invs.add(inv);
  }

  private void ensureVecCapacity(int n) {
    if (uVec == null || uVec.getNumRows() < n) {
      if (uVec != null) uVec.close();
      if (vVec != null) vVec.close();
      uVec = ComplexMatrix.newMatrix(n, 1);
      vVec = ComplexMatrix.newMatrix(n, 1);
    }
  }

  private void growOnce() {
    int oldM = invs.size();
    int newM = oldM + 1;

    ensureVecCapacity(oldM);

    // u_i = a_{i + oldM + 1}
    for (int i = 0; i < oldM; i++) {
      uVec.get(i, 0).set(a.apply(i + oldM + 1));
    }

    // v = inv · u
    ComplexMatrix oldInv = invs.get(oldM - 1);
    oldInv.mul(uVec, prec, vVec);

    // d = a_{2·oldM + 1}
    Complex d = a.apply(2 * oldM + 1);

    // s = d − u^T · v
    s.set(d);
    for (int i = 0; i < oldM; i++) {
      uVec.get(i, 0).mul(vVec.get(i, 0), prec, tmp);
      s.sub(tmp, prec, s);
    }

    if (s.isZero()) {
      throw new HankelDegeneracyException("Singular Hankel update at order " + newM);
    }

    // alpha = 1 / s
    alphaScalar.one().div(s, prec, alphaScalar);

    // newInv = [ inv + alpha·v·v^T   −alpha·v ]
    //          [ −alpha·v^T          alpha    ]
    ComplexMatrix newInv = ComplexMatrix.newMatrix(newM, newM);

    // top-left block
    for (int i = 0; i < oldM; i++) {
      for (int j = 0; j < oldM; j++) {
        vVec.get(i, 0).mul(vVec.get(j, 0), prec, tmp);
        tmp.mul(alphaScalar, prec, tmp);
        oldInv.get(i, j).add(tmp, prec, newInv.get(i, j));
      }
    }

    // right border
    for (int i = 0; i < oldM; i++) {
      vVec.get(i, 0).mul(alphaScalar, prec, tmp);
      tmp.neg(newInv.get(i, oldM));
    }

    // bottom border
    for (int j = 0; j < oldM; j++) {
      vVec.get(j, 0).mul(alphaScalar, prec, tmp);
      tmp.neg(newInv.get(oldM, j));
    }

    // bottom-right corner
    newInv.get(oldM, oldM).set(alphaScalar);

    invs.add(newInv);
  }

  private ComplexMatrix solveHankel(int M) {
    growTo(M);
    ComplexMatrix rhs = ComplexMatrix.newMatrix(M, 1);
    for (int i = 0; i < M; i++) {
      rhs.get(i, 0).set(a.apply(M + i + 1)).neg(rhs.get(i, 0));
    }
    ComplexMatrix q = ComplexMatrix.newMatrix(M, 1);
    ComplexMatrix inv = invs.get(M - 1);
    inv.mul(rhs, prec, q);
    rhs.close();
    return q;
  }

  /* ── Padé construction ──────────────────────────────────────────────── */

  private ComplexPolynomial buildDenominatorPolynomial(Integer M) {
    checkOpen();
    int m = M.getSignedValue();
    ComplexMatrix qVec = solveHankel(m);
    ComplexPolynomial qPoly = new ComplexPolynomial();
    for (int j = 0; j < m; j++) {
      qPoly.get(j).set(qVec.get(j, 0));
    }
    qVec.close();
    return qPoly;
  }

  /**
   * Evaluate the Padé approximant at $t$ with certified error $< 2^{-\text{bits}}$.
   */
  public Complex evaluate(Complex t, int bits) {
    checkOpen();
    t.pow(alpha, prec, z);

    Complex threshold = new Complex();
    threshold.set(Real.newReal(2).neg(threshold));
    threshold.pow(Real.newReal(bits).neg(threshold), prec, threshold);

    for (int m = 3; ; m++) {
      try (Complex tmp = new Complex();
           Integer Mi = new Integer(m);
           Integer Mm1 = new Integer(m - 1);
           Integer Mm2 = new Integer(m - 2)) {

        Φ.evaluate(Mi, 1, bits, null).evaluate(z, 1, bits, valM);
        Φ.evaluate(Mm1, 1, bits, null).evaluate(z, 1, bits, valMm1);
        Φ.evaluate(Mm2, 1, bits, null).evaluate(z, 1, bits, valMm2);

        valM.sub(valMm1, prec, deltaM);
        valMm1.sub(valMm2, prec, deltaMm1);

        deltaM.norm(prec, num);
        num.mul(num, prec, num);

        deltaMm1.norm(prec, denom);
        deltaM.norm(prec, tmp);
        denom.sub(tmp, prec, denom);

        if (!denom.isPositive()) {
          deltaM.sub(deltaMm1, prec, diff);
          if (diff.contains(Complex.ZERO) && diff.rad() < threshold.rad()) {
            throw new PrecisionExhaustedException(
                "Precision exhausted at order " + m +
                "; evaluation point may be outside convergence domain");
          }
          continue;
        }

        num.div(denom, prec, bound);

        if (bound.compareTo(threshold) <= 0) {
          return valM;
        }
      }
    }
  }

  @Override
  public void close() {
    if (!closed) {
      closed = true;
      for (ComplexMatrix inv : invs) {
        if (inv != null) inv.close();
      }
      if (uVec != null) uVec.close();
      if (vVec != null) vVec.close();
      s.close();
      alphaScalar.close();
      tmp.close();
      Φ.close();
      Φnum.close();
      Φden.close();
      z.close();
      valM.close();
      valMm1.close();
      valMm2.close();
      deltaM.close();
      deltaMm1.close();
      num.close();
      denom.close();
      bound.close();
      diff.close();
    }
  }

  private void checkOpen() {
    if (closed) {
      throw new IllegalStateException("MuntzPadeApproximant is closed");
    }
  }
}