package arb.functions.complex;

import arb.Complex;
import arb.ComplexFunction;
import arb.ComplexFunctionSequence;
import arb.ComplexPolynomial;
import arb.ComplexPolynomialSequence;
import arb.Integer;
import arb.Real;
import arb.functions.integer.ComplexSequence;
import arb4j.expression.Expression;
import arb4j.expression.compiler.ExpressionCompiler;
import arb4j.expression.compiler.context.Context;
import arb4j.expression.compiler.context.Variable;
import arb4j.expression.compiler.variable.VariableReference;
import arb4j.util.PrecisionExhaustedException;
import arb.solvers.IncrementalHankelSolver;
import arb.solvers.exceptions.HankelDegeneracyException;

/**
 * Müntz–Padé approximant for the fractional Riccati equation.
 *
 * <p>
 * Computes the diagonal Padé approximant $[M/M]$ of the transformed function
 * $f(\xi) = \sum_{n=0}^\infty a_n \xi^n$ where $\xi = z^\alpha$, using the
 * Puiseux coefficient sequence generated by the fractional recursion.
 *
 * <p>
 * The approximant is evaluated via the exact stopping criterion
 * $B_M(\xi) = |\Delta_M|^2 / (|\Delta_{M-1}| - |\Delta_M|) < \varepsilon$
 * with pre-asymptotic guard.
 */
public class MuntzPadeApproximant implements AutoCloseable {

  private final ComplexSequence a;
  private final IncrementalHankelSolver hankel;
  private final int prec;
  private final Real alpha;
  private final Context context;

  private final ComplexPolynomialSequence Φden;
  private final ComplexPolynomialSequence Φnum;
  private final ComplexFunctionSequence Φ;

  private final Complex z = new Complex();
  private final Complex valM = new Complex();
  private final Complex valMm1 = new Complex();
  private final Complex valMm2 = new Complex();
  private final Complex deltaM = new Complex();
  private final Complex deltaMm1 = new Complex();
  private final Complex num = new Complex();
  private final Complex denom = new Complex();
  private final Complex bound = new Complex();
  private final Complex diff = new Complex();

  private boolean closed = false;

  public MuntzPadeApproximant(ComplexSequence a, Real alpha, int prec) {
    this.a = a;
    this.alpha = alpha;
    this.prec = prec;
    this.hankel = new IncrementalHankelSolver(a, prec);

    this.context = new Context();
    Variable M = context.declareVariable("M", Integer.class);
    Variable zVar = context.declareVariable("z", Complex.class);
    context.registerVariable(new VariableReference<>("a", ComplexSequence.class, a));
    context.registerVariable(new VariableReference<>("qSeq", ComplexPolynomialSequence.class, this::buildDenominatorPolynomial));
    context.registerVariable(new VariableReference<>("Φden", ComplexPolynomialSequence.class, this::buildDenominatorPolynomial));

    this.Φden = ComplexPolynomialSequence.express("Φden:M➔z*qSeq(M)+1", context);
    this.Φnum = ComplexPolynomialSequence.express("Φnum:M➔sum(k➔a(k+1)*z^k{k=0..M-1})*Φden(M)", context);
    this.Φ = ComplexFunctionSequence.express("Φ:M➔z➔Φnum(M)(z)/Φden(M)(z)", context);
  }

  private ComplexPolynomial buildDenominatorPolynomial(Integer M) {
    checkOpen();
    int m = M.getSignedValue();
    hankel.growTo(m);
    ComplexMatrix qVec = hankel.solve(m);
    ComplexPolynomial qPoly = new ComplexPolynomial();
    for (int j = 0; j < m; j++) {
      qPoly.get(j).set(qVec.get(j, 0));
    }
    qVec.close();
    return qPoly;
  }

  /**
   * Evaluate the Padé approximant at $t$ with certified error $< 2^{-\text{bits}}$.
   */
  public Complex evaluate(Complex t, int bits) {
    checkOpen();
    t.pow(alpha, prec, z);

    Complex threshold = new Complex();
    threshold.set(Real.newReal(2).neg(threshold));
    threshold.pow(Real.newReal(bits).neg(threshold), prec, threshold);

    for (int m = 3; ; m++) {
      try (Complex tmp = new Complex();
           Integer Mi = new Integer(m);
           Integer Mm1 = new Integer(m - 1);
           Integer Mm2 = new Integer(m - 2)) {

        Φ.evaluate(Mi, 1, bits, null).evaluate(z, 1, bits, valM);
        Φ.evaluate(Mm1, 1, bits, null).evaluate(z, 1, bits, valMm1);
        Φ.evaluate(Mm2, 1, bits, null).evaluate(z, 1, bits, valMm2);

        valM.sub(valMm1, prec, deltaM);
        valMm1.sub(valMm2, prec, deltaMm1);

        deltaM.norm(prec, num);
        num.mul(num, prec, num);

        deltaMm1.norm(prec, denom);
        deltaM.norm(prec, tmp);
        denom.sub(tmp, prec, denom);

        if (!denom.isPositive()) {
          deltaM.sub(deltaMm1, prec, diff);
          if (diff.contains(Complex.ZERO) && diff.rad() < threshold.rad()) {
            throw new PrecisionExhaustedException(
                "Precision exhausted at order " + m +
                "; evaluation point may be outside convergence domain");
          }
          continue;
        }

        num.div(denom, prec, bound);

        if (bound.compareTo(threshold) <= 0) {
          return valM;
        }
      }
    }
  }

  @Override
  public void close() {
    if (!closed) {
      closed = true;
      hankel.close();
      Φ.close();
      Φnum.close();
      Φden.close();
      z.close();
      valM.close();
      valMm1.close();
      valMm2.close();
      deltaM.close();
      deltaMm1.close();
      num.close();
      denom.close();
      bound.close();
      diff.close();
    }
  }

  private void checkOpen() {
    if (closed) {
      throw new IllegalStateException("MuntzPadeApproximant is closed");
    }
  }
}