package arb.expressions.nodes;

import java.util.Collections;

import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.MethodVisitor;
import org.scilab.forge.jlatexmath.LaTeXAtom;

import arb.Complex;
import arb.ComplexMatrix;
import arb.ComplexPolynomial;
import arb.Integer;
import arb.Real;
import arb.RealMatrix;
import arb.RealPolynomial;
import arb.Typesettable;
import arb.expressions.Expression;
import arb.expressions.Variables;
import arb.expressions.nodes.binary.Addition;
import arb.expressions.nodes.binary.BinaryOperation;
import arb.functions.Function;

/**
 * arb4j is made available under the terms of the Business Source License™ v1.1
 * ©2024 which can be found in the root directory of this project in a file
 * named License.pdf, License.txt, or License.tm which are the pdf, text, and
 * TeXmacs formatted versions of the same document respectively.
 */
public abstract class Node<D, R, F extends Function<D, R>> implements
                          Typesettable
{
 
  public Expression<D, R, F> expression;

  public boolean             isResult = false;

  public Node(Expression<D, R, F> expression)
  {
    this.expression = expression;
    this.namespace  = expression.variables;
  }

  final Variables namespace;

  public abstract MethodVisitor generate(ClassVisitor classVisitor, MethodVisitor mv, Class<?> resultType);

  protected static String indent(int depth)
  {
    return String.join("", Collections.nCopies(Math.max(depth, 0), " "));
  }

  public Class<?> getGeneratedType()
  {
    return null;
  }

  public int bits = 128;

  /**
   * Determines whether this {@link Expression} {@link Node} is reusable. If it's
   * reusable, it means that the result generated by this {@link Node} can be
   * reliably used by the progenitor node in the {@link Expression} tree to store
   * its own result, thus saving heap allocations. The method should be overridden
   * by every subclass of {@link Node} to provide an appropriate response. For
   * {@link LiteralConstant} and {@link Variable} nodes, they would always return
   * false (since we cannot reuse them). For {@link BinaryOperation} nodes like
   * {@link Addition}, a method of determining whether they're reusable based on
   * the state of their operands.
   *
   * @return true if the node this reusable, false otherwise.
   */
  public abstract boolean isReusable();

  public abstract MethodVisitor prepareStackForReuse(MethodVisitor mv);

  /**
   * 
   * @return the {@link LaTeXAtom} string that represents this node
   */
  public abstract String typeset();

  /**
   * 
   * @return the type that this node results in when evaluated, should usually be
   *         one of {@link Real}, {@link Complex}, {@link RealPolynomial}, or
   *         {@link RealMatrix}, {@link ComplexMatrix}, {@link ComplexPolynomial},
   *         or {@link Integer}
   */
  public abstract <C> Class<? extends C> type();

}
