package arb.expressions.nodes;

import static java.lang.System.out;

import java.util.Collections;

import org.objectweb.asm.MethodVisitor;
import org.scilab.forge.jlatexmath.LaTeXAtom;

import arb.*;
import arb.Integer;
import arb.expressions.Expression;
import arb.expressions.Variables;
import arb.functions.Function;

/**
 * arb4j is made available under the terms of the Business Source License™ v1.1
 * ©2023 which can be found in the root directory of this project in a file
 * named License.pdf, License.txt, or License.tm which are the pdf, text, and
 * TeXmacs format of the same document respectively.
 */
public abstract class Node<D, R, F extends Function<D, R>> implements
                          Typesettable
{
  public static boolean      verbose  = false;

  public Expression<D, R, F> expression;

  public boolean             isResult = false;

  public Node(Expression<D, R, F> expression, int depth)
  {
    this.expression = expression;
    this.namespace  = expression.variables;
    verbose         = expression.verbose;
  }

  final Variables namespace;

  public abstract MethodVisitor generate(MethodVisitor mv);

  protected static String indent(int depth)
  {
    return String.join("", Collections.nCopies(Math.max(depth, 0), " "));
  }

  public abstract String toString(int depth);

  public int bits = 128;

  public int depth;

  /**
   * Determines whether this {@link Expression} {@link Node} is reusable. If it's
   * reusable, it means that the result {@link Field} instance generated by this
   * node can be safely reused by the parent node in the {@link Expression} tree
   * to store its own result, thus saving heap allocations. The method should be
   * overridden by every subclass of {@link Node} to provide an appropriate
   * response. For {@link LiteralConstant} and {@link Variable} nodes, they would
   * always return false (since we cannot reuse them). For {@link BinaryOperation}
   * nodes like {@link Add}, a method of determining whether they're reusable
   * based on the state of their operands.
   *
   * @return true if the node this reusable, false otherwise.
   */
  public abstract boolean isReusable();

  public abstract MethodVisitor prepareStackForReuse(MethodVisitor mv);

  /**
   * 
   * @return the {@link LaTeXAtom} string that represents this node
   */
  public abstract String typeset();

  /**
   * 
   * @return the type that this node results in when evaluated, should usually be
   *         one of {@link Real}, {@link Complex}, {@link RealPolynomial}, or
   *         {@link RealMatrix}, {@link ComplexMatrix}, {@link ComplexPolynomial},
   *         or {@link Integer}
   */
  public abstract Class<?> type();

  public Node<D, R, F> eliminateSubexpressions()
  {
    /**
     * TODO: create a MemoizedNode that extends Node and simply emits a reference to
     * the intermediate variable
     * 
     * TODO: each time a new intermediate variable is created, store the typeset
     * representation of it and the intermediateVariable it maps to then in this
     * method, iterate thru the expression and when the subexpression your about to
     * generate for matches something in the hasmap then instantiate a new
     * MemoizedNode referencing it and replace the matching node with it
     * 
     */
    out.format( "TODO: eliminate subexpressions in " + typeset() );
    return this;
  }

}
