package arb.expressions.nodes;

import static arb.expressions.Compiler.*;
import static org.objectweb.asm.Opcodes.GETFIELD;

import java.util.Collections;

import org.objectweb.asm.MethodVisitor;

import arb.expressions.Expression;
import arb.expressions.Variables;
import arb.functions.Function;

public abstract class Node<D extends arb.Field<D>, R extends arb.Field<R>, F extends Function<D, R>>
{
  public static boolean      verbose = false;

  public Expression<D, R, F> expression;

  public boolean             isLast  = false;

  public Node(Expression<D, R, F> parser)
  {
    this.expression = parser;
    this.namespace  = parser.variables;
  }

  final Variables<D> namespace;

  public abstract void generate(MethodVisitor mv);

  protected static String indent(int depth)
  {
    return String.join("", Collections.nCopies(Math.max(depth, 0), " "));
  }

  public abstract String toString(int depth);

  public int bits = 128;

  public int depth;

  /**
   * Determines whether this ExpressionNode is reusable. If it's reusable, it
   * means that the result Real instance generated by this node can be safely
   * reused by the parent node in the expression tree to store its own result,
   * thus saving heap allocations. The method should be overridden by every
   * subclass of ExpressionNode to provide an appropriate response. For Constant
   * and Variable nodes, they would always return false (since we cannot reuse
   * them). For binary operator nodes like Add, they would implement a strategy
   * for determining whether they're reusable based on the state of their
   * operands.
   *
   * @return true if the node this reusable, false otherwise.
   */
  public abstract boolean isReusable();

  protected void allocateIntermediateVariable(MethodVisitor mv)
  {
    if (!expression.resultAllocated)
    {
      expression.checkClassCast(loadResult(mv), true);
      expression.resultAllocated = true;
    }
    else
    {
      String fieldName = expression.allocateNewIntermediateVariable();
      loadThis(mv).visitFieldInsn(GETFIELD, expression.className, fieldName, expression.rangeClassDescriptor);
    }

  }

  public abstract MethodVisitor prepareStackForReuse(MethodVisitor mv);

}
