package arb.documentation;

/**
 * 
 * @see BusinessSourceLicenseVersionOnePointOne © terms of the
 *      {@link TheArb4jLibrary}
 */
public class TheArb4jLibrary implements
                             LicensedWork
{

  @Override
  public String getLicensedWorkDefinition()
  {
    return "The Licensed Work is the complete set of files, including source code, that come along with and are associated with the arb4j distribution \n"
                  + "that this license accompanies; including transformations of the source-code (such as but not limited to the compiled.class files or the dynamically \n"
                  + "generated .class files generated by the expression compilation capabilities of arb4j)\n";
  }

}
