/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

public class charcodemap_t {
  protected long swigCPtr;
  protected boolean swigCMemOwn;

  public charcodemap_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(charcodemap_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_charcodemap_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setKey(SWIGTYPE_p_wchar_t value) {
    arblibJNI.charcodemap_t_key_set(swigCPtr, this, SWIGTYPE_p_wchar_t.getCPtr(value));
  }

  public SWIGTYPE_p_wchar_t getKey() {
    return new SWIGTYPE_p_wchar_t(arblibJNI.charcodemap_t_key_get(swigCPtr, this), true);
  }

  public void setCode(SWIGTYPE_p_KeyCode value) {
    arblibJNI.charcodemap_t_code_set(swigCPtr, this, SWIGTYPE_p_KeyCode.getCPtr(value));
  }

  public SWIGTYPE_p_KeyCode getCode() {
    return new SWIGTYPE_p_KeyCode(arblibJNI.charcodemap_t_code_get(swigCPtr, this), true);
  }

  public void setSymbol(SWIGTYPE_p_KeySym value) {
    arblibJNI.charcodemap_t_symbol_set(swigCPtr, this, SWIGTYPE_p_KeySym.getCPtr(value));
  }

  public SWIGTYPE_p_KeySym getSymbol() {
    return new SWIGTYPE_p_KeySym(arblibJNI.charcodemap_t_symbol_get(swigCPtr, this), true);
  }

  public void setGroup(int value) {
    arblibJNI.charcodemap_t_group_set(swigCPtr, this, value);
  }

  public int getGroup() {
    return arblibJNI.charcodemap_t_group_get(swigCPtr, this);
  }

  public void setModmask(int value) {
    arblibJNI.charcodemap_t_modmask_set(swigCPtr, this, value);
  }

  public int getModmask() {
    return arblibJNI.charcodemap_t_modmask_get(swigCPtr, this);
  }

  public void setNeeds_binding(int value) {
    arblibJNI.charcodemap_t_needs_binding_set(swigCPtr, this, value);
  }

  public int getNeeds_binding() {
    return arblibJNI.charcodemap_t_needs_binding_get(swigCPtr, this);
  }

  public charcodemap_t() {
    this(arblibJNI.new_charcodemap_t(), true);
  }

}
