/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

import static arb.RealConstants.*;
import static arb.arblib.*;

public class ComplexMatrix implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ComplexMatrix(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ComplexMatrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(ComplexMatrix obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_ComplexMatrix(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  /**
   * Calls {@link arb#acb_mat_clear(ComplexMatrix)}
   * @return this
   */
  public ComplexMatrix clear()
  {
    if ( swigCMemOwn )
    {
      acb_mat_clear(this);
    }
    
    return this;
  }

  @Override
  public void close()
  { 
      clear();
  }
  
  public ComplexMatrix init(int rows, int cols)
  {
    acb_mat_init(this, rows, cols);
    return this;
  } 
  

  public void setNumRows(int value) {
    arblibJNI.ComplexMatrix_numRows_set(swigCPtr, this, value);
  }

  public int getNumRows() {
    return arblibJNI.ComplexMatrix_numRows_get(swigCPtr, this);
  }

  public void setNumCols(int value) {
    arblibJNI.ComplexMatrix_numCols_set(swigCPtr, this, value);
  }

  public int getNumCols() {
    return arblibJNI.ComplexMatrix_numCols_get(swigCPtr, this);
  }

  public void setRowPointers(long value) {
    arblibJNI.ComplexMatrix_rowPointers_set(swigCPtr, this, value);
  }

  public long getRowPointers() {
    return arblibJNI.ComplexMatrix_rowPointers_get(swigCPtr, this);
  }

  public ComplexMatrix() {
    this(arblibJNI.new_ComplexMatrix(), true);
  }

}
