/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

public class DirichletPrimeGroup {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public DirichletPrimeGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(DirichletPrimeGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(DirichletPrimeGroup obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_DirichletPrimeGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setP(long value) {
    arblibJNI.DirichletPrimeGroup_p_set(swigCPtr, this, value);
  }

  public long getP() {
    return arblibJNI.DirichletPrimeGroup_p_get(swigCPtr, this);
  }

  public void setE(int value) {
    arblibJNI.DirichletPrimeGroup_e_set(swigCPtr, this, value);
  }

  public int getE() {
    return arblibJNI.DirichletPrimeGroup_e_get(swigCPtr, this);
  }

  public void setG(long value) {
    arblibJNI.DirichletPrimeGroup_g_set(swigCPtr, this, value);
  }

  public long getG() {
    return arblibJNI.DirichletPrimeGroup_g_get(swigCPtr, this);
  }

  public DirichletPrimeGroup() {
    this(arblibJNI.new_DirichletPrimeGroup(), true);
  }

}
