/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

public class FastDFTProductScheme {
  protected long swigCPtr;
  protected boolean swigCMemOwn;

  public FastDFTProductScheme(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(FastDFTProductScheme obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_FastDFTProductScheme(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setN(int value) {
    arblibJNI.FastDFTProductScheme_n_set(swigCPtr, this, value);
  }

  public int getN() {
    return arblibJNI.FastDFTProductScheme_n_get(swigCPtr, this);
  }

  public void setNumeratorAddress(int value) {
    arblibJNI.FastDFTProductScheme_numeratorAddress_set(swigCPtr, this, value);
  }

  public int getNumeratorAddress() {
    return arblibJNI.FastDFTProductScheme_numeratorAddress_get(swigCPtr, this);
  }

  public void setCyc(FastDFTStepScheme value) {
    arblibJNI.FastDFTProductScheme_cyc_set(swigCPtr, this, FastDFTStepScheme.getCPtr(value), value);
  }

  public FastDFTStepScheme getCyc() {
    long cPtr = arblibJNI.FastDFTProductScheme_cyc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FastDFTStepScheme(cPtr, false);
  }

  public FastDFTProductScheme() {
    this(arblibJNI.new_FastDFTProductScheme(), true);
  }

}
