/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

  import arb.documentation.BusinessSourceLicenseVersionOnePointOne;
  import arb.documentation.TheArb4jLibrary;

public class GenericRingPolynomial {
  protected long swigCPtr;
  protected boolean swigCMemOwn;

  public GenericRingPolynomial(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GenericRingPolynomial obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_GenericRingPolynomial(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  static { System.loadLibrary("arblib"); }

  /**
   * Construct a fresh, initialised polynomial in the given ring.
   * Wraps {@code gr_poly_init}.
   */
  public static GenericRingPolynomial in(GenericRing ring)
  {
    GenericRingPolynomial p = new GenericRingPolynomial();
    arblib.gr_poly_init(p, ring);
    return p;
  }

  /** Set this polynomial to 0 in the given ring. */
  public GenericRingPolynomial zero(GenericRing ring)
  {
    arblib.gr_poly_zero(this, ring);
    return this;
  }

  /** Set this polynomial to 1 in the given ring. */
  public GenericRingPolynomial one(GenericRing ring)
  {
    arblib.gr_poly_one(this, ring);
    return this;
  }

  /** Set the n-th coefficient of this polynomial to the integer x. */
  public GenericRingPolynomial setCoeff(int n, int x, GenericRing ring)
  {
    arblib.gr_poly_set_coeff_si(this, n, x, ring);
    return this;
  }

  /** Set this polynomial to {@code src} in the given ring. */
  public GenericRingPolynomial set(GenericRingPolynomial src, GenericRing ring)
  {
    arblib.gr_poly_set(this, src, ring);
    return this;
  }

  /** Negate this polynomial into {@code result}. */
  public GenericRingPolynomial neg(GenericRing ring, GenericRingPolynomial result)
  {
    arblib.gr_poly_neg(result, this, ring);
    return result;
  }

  /** {@code result = this + other}. */
  public GenericRingPolynomial add(GenericRingPolynomial other, GenericRing ring, GenericRingPolynomial result)
  {
    arblib.gr_poly_add(result, this, other, ring);
    return result;
  }

  /** {@code result = this - other}. */
  public GenericRingPolynomial sub(GenericRingPolynomial other, GenericRing ring, GenericRingPolynomial result)
  {
    arblib.gr_poly_sub(result, this, other, ring);
    return result;
  }

  /** {@code result = this * other}. */
  public GenericRingPolynomial mul(GenericRingPolynomial other, GenericRing ring, GenericRingPolynomial result)
  {
    arblib.gr_poly_mul(result, this, other, ring);
    return result;
  }

  /** {@code result = this / divisor} — valid only when the ring is a field
   * (e.g. {@link GenericRing#fractionFieldOf}) or the division is exact. */
  public GenericRingPolynomial div(GenericRingPolynomial divisor, GenericRing ring, GenericRingPolynomial result)
  {
    arblib.gr_poly_div(result, this, divisor, ring);
    return result;
  }

  /** {@code result = d(this)/dx}. */
  public GenericRingPolynomial derivative(GenericRing ring, GenericRingPolynomial result)
  {
    arblib.gr_poly_derivative(result, this, ring);
    return result;
  }

  /** Degree of this polynomial (= {@code length - 1}). */
  public int degree()
  {
    return Math.max(0, getLength() - 1);
  }

  public void setCoeffsNative(SWIGTYPE_p_void value) {
    arblibJNI.GenericRingPolynomial_coeffsNative_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getCoeffsNative() {
    long cPtr = arblibJNI.GenericRingPolynomial_coeffsNative_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setLength(int value) {
    arblibJNI.GenericRingPolynomial_length_set(swigCPtr, this, value);
  }

  public int getLength() {
    return arblibJNI.GenericRingPolynomial_length_get(swigCPtr, this);
  }

  public GenericRingPolynomial() {
    this(arblibJNI.new_GenericRingPolynomial(), true);
  }

}
