/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

public class GMPRandomState {
  protected long swigCPtr;
  protected boolean swigCMemOwn;

  public GMPRandomState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GMPRandomState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_GMPRandomState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RandomAlgorithmData getAlgorithmData() {
    long cPtr = arblibJNI.GMPRandomState_algorithmData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new RandomAlgorithmData(cPtr, false);
  }

  public GMPRandomState() {
    this(arblibJNI.new_GMPRandomState(), true);
  }

}
