/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

public class PartialFraction {
  protected long swigCPtr;
  protected boolean swigCMemOwn;

  public PartialFraction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(PartialFraction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_PartialFraction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Complex[] getPolesArray()
  {
    int m = getN();
    Complex[] arr = new Complex[m];
    for (int i = 0; i < m; i++)
    {
      arr[i] = new Complex();
      arblib.arb4j_partial_fraction_get_pole(arr[i], this, i);
    }
    return arr;
  }

  public Complex[] getResiduesArray()
  {
    int m = getN();
    Complex[] arr = new Complex[m];
    for (int i = 0; i < m; i++)
    {
      arr[i] = new Complex();
      arblib.arb4j_partial_fraction_get_residue(arr[i], this, i);
    }
    return arr;
  }

  public void setQuotient(ComplexPolynomial value) {
    arblibJNI.PartialFraction_quotient_set(swigCPtr, this, ComplexPolynomial.getCPtr(value), value);
  }

  public ComplexPolynomial getQuotient() {
    long cPtr = arblibJNI.PartialFraction_quotient_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ComplexPolynomial(cPtr, false);
  }

  public void setPoles(Complex value) {
    arblibJNI.PartialFraction_poles_set(swigCPtr, this, Complex.getCPtr(value), value);
  }

  public Complex getPoles() {
    long cPtr = arblibJNI.PartialFraction_poles_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Complex(cPtr, false);
  }

  public void setResidues(Complex value) {
    arblibJNI.PartialFraction_residues_set(swigCPtr, this, Complex.getCPtr(value), value);
  }

  public Complex getResidues() {
    long cPtr = arblibJNI.PartialFraction_residues_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Complex(cPtr, false);
  }

  public void setN(int value) {
    arblibJNI.PartialFraction_n_set(swigCPtr, this, value);
  }

  public int getN() {
    return arblibJNI.PartialFraction_n_get(swigCPtr, this);
  }

  public PartialFraction() {
    this(arblibJNI.new_PartialFraction(), true);
  }

}
