/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

public class Pointer {
  private transient long swigCPtr;

  protected Pointer(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected Pointer() {
    swigCPtr = 0;
  }

  protected static long getCPtr(Pointer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(Pointer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

