/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.3.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

public class RandomAlgorithmData {
  protected long swigCPtr;
  protected boolean swigCMemOwn;

  public RandomAlgorithmData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(RandomAlgorithmData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_RandomAlgorithmData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RandomAlgorithmData() {
    this(arblibJNI.new_RandomAlgorithmData(), true);
  }

}
