/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

public class RandomAlgorithmData {
  protected long swigCPtr;
  protected boolean swigCMemOwn;

  public RandomAlgorithmData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(RandomAlgorithmData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_RandomAlgorithmData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_mp_lc(SWIGTYPE_p_void value) {
    arblibJNI.RandomAlgorithmData__mp_lc_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void get_mp_lc() {
    long cPtr = arblibJNI.RandomAlgorithmData__mp_lc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public RandomAlgorithmData() {
    this(arblibJNI.new_RandomAlgorithmData(), true);
  }

}
