/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

public class SWIGTYPE_p_gr_srcptr {
  private transient long swigCPtr;

  protected SWIGTYPE_p_gr_srcptr(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_gr_srcptr() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_gr_srcptr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SWIGTYPE_p_gr_srcptr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

