/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

public class XDO {
  protected long swigCPtr;
  protected boolean swigCMemOwn;

  public XDO(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(XDO obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arblibJNI.delete_XDO(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setXdpy(SWIGTYPE_p_Display value) {
    arblibJNI.XDO_xdpy_set(swigCPtr, this, SWIGTYPE_p_Display.getCPtr(value));
  }

  public SWIGTYPE_p_Display getXdpy() {
    long cPtr = arblibJNI.XDO_xdpy_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_Display(cPtr, false);
  }

  public void setDisplay_name(String value) {
    arblibJNI.XDO_display_name_set(swigCPtr, this, value);
  }

  public String getDisplay_name() {
    return arblibJNI.XDO_display_name_get(swigCPtr, this);
  }

  public void setCharcodes(CharacterCodeMap value) {
    arblibJNI.XDO_charcodes_set(swigCPtr, this, CharacterCodeMap.getCPtr(value), value);
  }

  public CharacterCodeMap getCharcodes() {
    long cPtr = arblibJNI.XDO_charcodes_get(swigCPtr, this);
    return (cPtr == 0) ? null : new CharacterCodeMap(cPtr, false);
  }

  public void setCharcodes_len(int value) {
    arblibJNI.XDO_charcodes_len_set(swigCPtr, this, value);
  }

  public int getCharcodes_len() {
    return arblibJNI.XDO_charcodes_len_get(swigCPtr, this);
  }

  public void setModmap(SWIGTYPE_p_XModifierKeymap value) {
    arblibJNI.XDO_modmap_set(swigCPtr, this, SWIGTYPE_p_XModifierKeymap.getCPtr(value));
  }

  public SWIGTYPE_p_XModifierKeymap getModmap() {
    long cPtr = arblibJNI.XDO_modmap_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_XModifierKeymap(cPtr, false);
  }

  public void setKeymap(SWIGTYPE_p_KeySym value) {
    arblibJNI.XDO_keymap_set(swigCPtr, this, SWIGTYPE_p_KeySym.getCPtr(value));
  }

  public SWIGTYPE_p_KeySym getKeymap() {
    long cPtr = arblibJNI.XDO_keymap_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_KeySym(cPtr, false);
  }

  public void setKeycode_high(int value) {
    arblibJNI.XDO_keycode_high_set(swigCPtr, this, value);
  }

  public int getKeycode_high() {
    return arblibJNI.XDO_keycode_high_get(swigCPtr, this);
  }

  public void setKeycode_low(int value) {
    arblibJNI.XDO_keycode_low_set(swigCPtr, this, value);
  }

  public int getKeycode_low() {
    return arblibJNI.XDO_keycode_low_get(swigCPtr, this);
  }

  public void setKeysyms_per_keycode(int value) {
    arblibJNI.XDO_keysyms_per_keycode_set(swigCPtr, this, value);
  }

  public int getKeysyms_per_keycode() {
    return arblibJNI.XDO_keysyms_per_keycode_get(swigCPtr, this);
  }

  public void setClose_display_when_freed(int value) {
    arblibJNI.XDO_close_display_when_freed_set(swigCPtr, this, value);
  }

  public int getClose_display_when_freed() {
    return arblibJNI.XDO_close_display_when_freed_get(swigCPtr, this);
  }

  public void setQuiet(int value) {
    arblibJNI.XDO_quiet_set(swigCPtr, this, value);
  }

  public int getQuiet() {
    return arblibJNI.XDO_quiet_get(swigCPtr, this);
  }

  public void setDebug(int value) {
    arblibJNI.XDO_debug_set(swigCPtr, this, value);
  }

  public int getDebug() {
    return arblibJNI.XDO_debug_get(swigCPtr, this);
  }

  public void setFeatures_mask(int value) {
    arblibJNI.XDO_features_mask_set(swigCPtr, this, value);
  }

  public int getFeatures_mask() {
    return arblibJNI.XDO_features_mask_get(swigCPtr, this);
  }

  public XDO() {
    this(arblibJNI.new_XDO(), true);
  }

}
