package arb.functions;

import static arb.utensils.Utensils.wrapOrThrow;

import java.io.Closeable;
import java.util.*;

import arb.Integer;
import arb.Named;
import arb.Typesettable;
import arb.documentation.BusinessSourceLicenseVersionOnePointOne;
import arb.documentation.TheArb4jLibrary;
import arb.exceptions.CompilerException;
import arb.expressions.*;
import arb.expressions.nodes.VariableNode;
import arb.functions.complex.ComplexFunction;

/**
 * 
 * @param <D>  the domain
 * @param <CO> the co-domain
 * @see BusinessSourceLicenseVersionOnePointOne © terms of the
 *      {@link TheArb4jLibrary}
 */
public interface Function<D, CO> extends
                         Closeable,
                         AutoCloseable,
                         Typesettable,
                         Named
{

  /**
   * Memoization peek over a {@link HashMap} keyed by signed {@code int} index.
   * Replaces the previous {@link ArrayList}-backed cache, which silently returned
   * {@code null} for negative indices and triggered unbounded recompute on
   * recursive sequences whose recurrence reaches negative arguments.
   * {@code HashMap} permits arbitrary integer keys, so every {@code peek} that
   * finds a stored value short-circuits the recursion.
   *
   * @param cache memoization map; never {@code null} for generated classes
   * @param n     signed integer index — may be negative
   * @return the cached value if present, otherwise {@code null}
   */
  static <C> C peek(TreeMap<arb.Integer, C> cache, arb.Integer n)
  {
    return cache.get(n);
  }

  /**
   * Memoization poke over a {@link TreeMap} keyed by signed {@code int} index.
   * See {@link #peek(TreeMap, Integer)} for the rationale.
   *
   * @return the inserted value (for chaining)
   */
  static <C> C poke(TreeMap<arb.Integer, C> cache, arb.Integer n, C value)
  {
    cache.put(new arb.Integer(n), value);
    return value;
  }

  /**
   * Memoization peek by primitive {@code int}. Used by generated bytecode which
   * has already extracted the signed value from the input parameter.
   */

  /**
   * Memoization poke by primitive {@code int}. Used by generated bytecode.
   */

  default Context getContext()
  {
    return null;
  }

  /**
   * Source-Expression back-pointer. Expression-compiled Functions return the
   * {@link Expression} that produced them; hand-written Functions return
   * {@code null} unless they choose to expose one. Consumers may also null out a
   * generated class's {@code expression} field directly if they want to drop the
   * back-pointer.
   */
  default <F extends Function<? extends D, ? extends CO>> Expression<D, CO, F> getExpression()
  {
    return null;
  }

  @Override
  default String getName()
  {
    return null;
  }

  public default Function<D, CO> derivative()
  {
    throw new UnsupportedOperationException("TODO: " + getClass() + " should implement derivative()");
  }

  /**
   * Lazy on-demand partial derivative with respect to the parameter named by
   * {@code variable}. Implementing classes whose dependence on {@code variable}
   * is symbolic should return a fresh {@link Function} computing
   * {@code ∂this/∂variable}; classes that do not depend on {@code variable}
   * should return the zero function in the codomain.
   *
   * <p>
   * The contract mirrors the no-argument {@link #derivative()}: nothing is
   * pre-compiled at the parent's compile time, the work is paid only when this
   * method is called, and concrete classes are expected to memoize.
   *
   * @param variable location-free handle of the parameter to differentiate w.r.t.
   * @return a {@link Function} computing {@code ∂this/∂variable}
   */
  @SuppressWarnings("unchecked")
  public default Function<D, CO> derivative(VariableReference<?, ?, ?> variable)
  {
    Expression<?, ?, ?> expr = getExpression();
    if (expr != null)
    {
      return (Function<D, CO>) expr.derivative(variable);
    }
    throw new UnsupportedOperationException("TODO: " + getClass() + " should implement derivative(VariableReference) or expose getExpression()");
  }

  /**
   * Convenience overload of {@link #derivative(VariableReference)} taking a
   * variable name. The default resolves the name against {@link #getContext()};
   * implementing classes that already hold a {@link VariableReference} should
   * override to skip the round-trip.
   *
   * @param variableName name of the parameter to differentiate w.r.t.
   * @return a {@link Function} computing {@code ∂this/∂variableName}
   */
  public default Function<D, CO> derivative(String variableName)
  {
    return derivative(new VariableReference<D, CO, Function<D, CO>>(variableName));
  }

  /**
   * Prototype-pattern copy: produce a fresh instance of this function whose
   * mutable evaluation state (compiled DSL registers, scratch polynomials,
   * Newton-iteration buffers, etc.) is independent of {@code this}, but whose
   * mathematically-meaningful parameters (slope constants, branch indices,
   * orders, etc.) match {@code this} exactly. The intended use is to spread a
   * single-instance Function across multiple worker threads: each worker obtains
   * its own {@link #cloneFunction()} and evaluates concurrently without sharing
   * the per-evaluation registers that make a generated DSL class non-reentrant.
   *
   * <p>
   * The default throws {@link UnsupportedOperationException}. Implement this on
   * any Function whose {@code evaluate} is not reentrant. Generated DSL classes
   * inherit the default and must be cloned by their owner: a Java class that
   * wraps DSL-compiled subfunctions overrides {@code cloneFunction} to return a
   * fresh wrapper whose subfunctions are themselves freshly built (typically by
   * re-running its constructor).
   *
   * @return a fresh function instance independent of {@code this} for the
   *         purposes of concurrent evaluation
   */
  public default Function<D, CO> cloneFunction()
  {
    throw new UnsupportedOperationException(getClass() + " must override cloneFunction() to be safely shared across threads");
  }

  public default Function<D, CO> derivative(int n)
  {
    Function<D, CO> result = this;
    for (int i = 0; i < n; i++)
    {
      result = result.derivative();
    }
    return result;
  }

  public default Function<D, CO> integral()
  {
    assert false : "TODO: " + getClass() + " should implement this";
    return null;
  }

  /**
   * Multi-variable analogue of {@link #derivative()}: return the Jacobian of this
   * function with respect to a caller-ordered subset of its parameters. The
   * implementing class decides how to produce each partial — symbolic
   * differentiation against its own {@link Context}, ARB jets at the named
   * variable, or anything else appropriate. Unknown variable names should be
   * rejected against this function's parameter list.
   *
   * @param variables ordered list of parameter names whose partials to return
   * @return a {@link Jacobian} whose i-th partial is ∂this/∂variables[i]
   */
  public default <F extends Function<D,CO>> Jacobian<D, CO, F> jacobian(String[] variables)
  {
    throw new UnsupportedOperationException("TODO: " + getClass() + " should implement jacobian(String[])");
  }

  /**
   * Convenience overload of {@link #jacobian(String[])} taking
   * {@link arb.expressions.VariableReference} handles. The default extracts each
   * reference's name and dispatches to {@link #jacobian(String[])}; implementing
   * classes that have direct access to the references (and so can avoid the
   * name-lookup round trip) are free to override.
   */
  public default <F extends Function<D,CO>> Jacobian<D, CO, F> jacobian(VariableReference<?, ?, ?>[] variables)
  {
    String[] names = new String[variables.length];
    for (int i = 0; i < variables.length; i++)
    {
      names[i] = variables[i].name;
    }
    return jacobian(names);
  }

  /**
   * Convenience overload of {@link #jacobian(String[])} taking
   * {@link arb.expressions.nodes.VariableNode} handles. The default extracts each
   * node's name and dispatches to {@link #jacobian(String[])}; implementing
   * classes that have direct access to the nodes are free to override.
   */
  public default <F extends Function<D,CO>>  Jacobian<D, CO, F> jacobian(VariableNode<?, ?, ?>[] variables)
  {
    String[] names = new String[variables.length];
    for (int i = 0; i < variables.length; i++)
    {
      names[i] = variables[i].getName();
    }
    return jacobian(names);
  }

  /**
   * Drop the cached static-subexpression values so that the next
   * {@link #evaluate(Object, int, int, Object) evaluate} call recomputes every
   * subtree that was lifted into {@code evaluateStaticSubexpressions} by
   * fixed-point static hoisting.
   * <p>
   * Generated classes with at least one hoisted static subexpression override
   * this to reset the internal {@code staticPrecision} sentinel to {@code -1}.
   * Call this whenever a parameter field or a {@link Context} variable that
   * participates in a hoisted subtree has been mutated between calls — e.g.
   * during parameter estimation, Monte-Carlo sweeps, or any workflow that rebinds
   * the bound-parameter instance data rather than constructing a fresh function
   * object. Functions with no hoisted state inherit this no-op default.
   *
   * @see arb.expressions.nodes.StaticNode
   */
  public default void invalidateCache()
  {
    invalidateCache(Collections.newSetFromMap(new IdentityHashMap<>()));
  }

  /**
   * Cycle-safe entry point: walks the static-cache invalidation through inlined
   * nested {@link Function} fields exactly once. Generated classes override this
   * to (1) skip if {@code alreadyInvalidated} already contains {@code this}, (2)
   * add {@code this}, (3) reset their own {@code staticPrecision} sentinel, and
   * (4) recurse into each referenced nested function field passing the same set.
   * The mutually-recursive Müntz {@code a ↔ S} cluster (and any other cycle in
   * the function graph) terminates the traversal correctly because the set
   * membership check is identity-based.
   *
   * @param alreadyInvalidated identity-based set of {@link Function} instances
   *                           whose static caches have been invalidated during
   *                           this traversal
   */
  public default void invalidateCache(Set<Function<?, ?>> alreadyInvalidated)
  {

  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Expression<D, H, Q>
         parseAndCompile(Class<? extends D> domainClass, Class<? extends H> coDomainClass, Class<? extends Q> functionClass, String expression, Context context)
  {
    Expression<D, H, Q> parsedExpression = Function.parse(Parser.transformToAcceptableJavaIdentifier(expression),
                                                          expression,
                                                          context,
                                                          domainClass,
                                                          coDomainClass,
                                                          functionClass,
                                                          null,
                                                          null,
                                                          true);
    parsedExpression.compile();

    return parsedExpression;
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Q
         express(Class<? extends D> class1, Class<? extends H> class2, Class<? extends Q> class3, String expression, Context context)
  {
    return express(class1, class2, class3, null, expression, context);

  }

  @SuppressWarnings("unchecked")
  public static <D, H, Q extends Function<? extends D, ? extends H>> Q express(Class<? extends D> domainClass,
                                                                               Class<? extends H> coDomainClass,
                                                                               String expression)
  {
    return (Q) Function.express(expression, new Context(), domainClass, coDomainClass, Function.class, null);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Q
         express(Class<? extends D> domainClass, Class<? extends H> coDomainClass, Class<? extends Q> functionClass, String expression)
  {
    return Function.express(expression, new Context(), domainClass, coDomainClass, functionClass, null);
  }

  @SuppressWarnings("unchecked")
  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Q
         express(Class<? extends D> domainClass, Class<? extends H> coDomainClass, String functionName, String expression, Context context)
  {
    return (Q) Function.express(expression, context, domainClass, coDomainClass, Function.class, functionName);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Q
         express(Class<? extends D> domainClass, Class<? extends H> coDomainClass, Class<? extends Q> functionClass, String expressionName, String expression)
  {
    return express(domainClass, coDomainClass, functionClass, expressionName, expression, null);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>> Q express(Class<? extends D> domainClass,
                                                                               Class<? extends H> coDomainClass,
                                                                               Class<? extends Q> functionClass,
                                                                               String expressionName,
                                                                               String expression,
                                                                               Context context)
  {
    if (context == null)
    {
      context = new Context();
    }

    FunctionMapping<D, H, Q> functionMapping = context.getFunctionMapping(expressionName);
    if (functionMapping != null && functionMapping.instance != null)
    {
      return functionMapping.instance;
    }

    return Function.express(expression, context, domainClass, coDomainClass, functionClass, expressionName);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Q
         express(String functionName, Class<? extends D> domainClass, Class<? extends H> coDomainClass, Class<? extends Q> functionClass, String expression)
  {
    return Function.express(expression, new Context(), domainClass, coDomainClass, functionClass, functionName);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>> Q express(String functionName,
                                                                               Class<? extends D> domainClass,
                                                                               Class<? extends H> coDomainClass,
                                                                               Class<? extends Q> functionClass,
                                                                               String expression,
                                                                               Context context)
  {
    return Function.express(expression, context, domainClass, coDomainClass, functionClass, functionName);
  }

  static <D, H, Q extends Function<? extends D, ? extends H>> Q express(String expression,
                                                                        Context context,
                                                                        Class<? extends D> domainClass,
                                                                        Class<? extends H> coDomainClass,
                                                                        Class<? extends Q> functionClass,
                                                                        String functionName)
  {
    return express(expression, context, domainClass, coDomainClass, functionClass, functionName, true);
  }

  static <D, H, Q extends Function<? extends D, ? extends H>> Q express(String expression,
                                                                        Context context,
                                                                        Class<? extends D> domainClass,
                                                                        Class<? extends H> coDomainClass,
                                                                        Class<? extends Q> functionClass,
                                                                        String functionName,
                                                                        boolean replace)
  {
    Expression<D, H, Q> compiledParsedAndRegisteredExpression = parseCompileAndRegister(expression,
                                                                                        context,
                                                                                        domainClass,
                                                                                        coDomainClass,
                                                                                        functionClass,
                                                                                        functionName,
                                                                                        replace);
    if (compiledParsedAndRegisteredExpression.functionMapping != null && compiledParsedAndRegisteredExpression.functionMapping.instance != null)
    {
      return compiledParsedAndRegisteredExpression.functionMapping.instance;
    }
    Q instance = compiledParsedAndRegisteredExpression.instantiate();
    if (compiledParsedAndRegisteredExpression.functionMapping != null)
    {
      compiledParsedAndRegisteredExpression.functionMapping.instance = instance;
    }
    return instance;
  }

  static <D, H, Q extends Function<? extends D, ? extends H>> Expression<D, H, Q> parseCompileAndRegister(String expression,
                                                                                                          Context context,
                                                                                                          Class<? extends D> domainClass,
                                                                                                          Class<? extends H> coDomainClass,
                                                                                                          Class<? extends Q> functionClass,
                                                                                                          String functionName,
                                                                                                          boolean replace)
  {
    int colonIndex = expression.indexOf(':');
    if (colonIndex != -1)
    {
      var thisFunctionName = expression.substring(0, colonIndex);
      if (functionName != null && !functionName.equals(thisFunctionName))
      {
        throw new CompilerException(String.format("name='%s' specified with : syntax does not match name specified another way '%s'",
                                                  thisFunctionName,
                                                  functionName));
      }
      expression   = expression.substring(colonIndex + 1);
      functionName = thisFunctionName;
    }

    int punctuationMarkIndex = expression.indexOf(":");
    if (punctuationMarkIndex != -1)
    {
      String inlineFunctionName = expression.substring(0, punctuationMarkIndex);
      if (functionName != null && !functionName.equals(inlineFunctionName))
      {
        throw new CompilerException(String.format("functionName='%s' specified via function argument != inlineFunctionName='%s'",
                                                  functionName,
                                                  inlineFunctionName));
      }
      functionName = inlineFunctionName;
      expression   = expression.substring(punctuationMarkIndex + 1, expression.length());
    }
    expression = expression.replaceAll(" ", "");

    FunctionMapping<D, H, Q> mapping = null;
    if (functionName != null && context != null)
    {
      mapping = context.registerFunctionMapping(functionName, null, domainClass, coDomainClass, functionClass, replace, null, expression);
    }

    Expression<D, H, Q> parsedExpression = Parser.parse(expression, context, domainClass, coDomainClass, functionClass, functionName);

    parsedExpression.functionMapping = mapping;
    if (mapping != null)
    {
      mapping.expression = parsedExpression;
    }

    if (context != null)
    {
      context.registerFunctionMapping(functionName, domainClass, coDomainClass, functionClass);
    }

    return parsedExpression;
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Expression<D, H, Q>
         parse(Class<? extends D> domainClass, Class<? extends H> coDomainClass, Class<? extends Q> functionClass, String expression)
  {
    return parse(Parser.normalize(expression), expression, null, domainClass, coDomainClass, functionClass, null, null, true);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Expression<D, H, Q>
         parse(Class<? extends D> domainClass, Class<? extends H> coDomainClass, Class<? extends Q> functionClass, String expression, Context context)
  {
    return parse(Parser.transformToAcceptableJavaIdentifier(expression), expression, context, domainClass, coDomainClass, functionClass, null, null, true);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>> Expression<D, H, Q> parse(Class<? extends D> domainClass,
                                                                                               Class<? extends H> coDomainClass,
                                                                                               Class<? extends Q> functionClass,
                                                                                               String expression,
                                                                                               Context context,
                                                                                               Expression<?, ?, ?> containingExpression)
  {
    String hashString = Parser.transformToAcceptableJavaIdentifier(expression);
    return parse(hashString, expression, context, domainClass, coDomainClass, functionClass, null, containingExpression, true);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>> Expression<D, H, Q> parse(Class<? extends D> domainClass,
                                                                                               Class<? extends H> coDomainClass,
                                                                                               Class<? extends Q> functionClass,
                                                                                               String expression,
                                                                                               Context context,
                                                                                               Expression<?, ?, ?> containingExpression,
                                                                                               boolean simplify)
  {
    String hashString = Parser.transformToAcceptableJavaIdentifier(expression);
    return parse(hashString, expression, context, domainClass, coDomainClass, functionClass, null, containingExpression, simplify);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>, PD, PC, PF extends Function<? extends PD, ? extends PC>, E extends Expression<D, H, Q>>
         E
         parse(String className,
               String expression,
               Context context,
               Class<? extends D> domainClass,
               Class<? extends H> coDomainClass,
               Class<? extends Q> functionClass,
               String functionName,
               Expression<? extends PD, ? extends PC, ? extends PF> containingExpression,
               boolean simplify)
  {
    return Parser.parseExpression(className, expression, context, domainClass, coDomainClass, functionClass, functionName, containingExpression, simplify);
  }

  /**
   * Extracts function name from expression, registers in context, and parses.
   * Returns the parsed Expression with functionMapping wired up.
   */
  public static <D, H, Q extends Function<? extends D, ? extends H>> Expression<D, H, Q> parseAndRegister(String expression,
                                                                                                          Context context,
                                                                                                          Class<? extends D> domainClass,
                                                                                                          Class<? extends H> coDomainClass,
                                                                                                          Class<? extends Q> functionClass,
                                                                                                          String functionName,
                                                                                                          boolean replace)
  {
    int colonIndex = expression.indexOf(':');
    if (colonIndex != -1)
    {
      var thisFunctionName = expression.substring(0, colonIndex);
      if (functionName != null && !functionName.equals(thisFunctionName))
      {
        throw new CompilerException(String.format("name='%s' specified with : syntax does not match name specified another way '%s'",
                                                  thisFunctionName,
                                                  functionName));
      }
      expression   = expression.substring(colonIndex + 1);
      functionName = thisFunctionName;
    }

    int punctuationMarkIndex = expression.indexOf(":");
    if (punctuationMarkIndex != -1)
    {
      String inlineFunctionName = expression.substring(0, punctuationMarkIndex);
      if (functionName != null && !functionName.equals(inlineFunctionName))
      {
        throw new CompilerException(String.format("functionName='%s' specified via function argument != inlineFunctionName='%s'",
                                                  functionName,
                                                  inlineFunctionName));
      }
      functionName = inlineFunctionName;
      expression   = expression.substring(punctuationMarkIndex + 1);
    }
    expression = expression.replaceAll(" ", "");

    FunctionMapping<D, H, Q> mapping = null;
    if (functionName != null && context != null)
    {
      mapping = context.registerFunctionMapping(functionName, null, domainClass, coDomainClass, functionClass, replace, null, expression);
    }

    Expression<D, H, Q> parsedExpression = Parser.parse(expression, context, domainClass, coDomainClass, functionClass, functionName);

    parsedExpression.functionMapping = mapping;
    if (mapping != null)
    {
      mapping.expression = parsedExpression;
    }

    return parsedExpression;
  }

  public default void close()
  {

  }

  public default Class<CO> coDomainType()
  {
    assert false : "this should be implemented by " + getClass();
    return null;
  }

  public default Class<D> domainType()
  {
    assert false : "this should be implemented by " + getClass();
    return null; // for instance, the RealFunction would return Real.class for both the domain
                 // and coDomain
  }

  public default CO evaluate(D t, int bits)
  {
    return evaluate(t, 1, bits);
  }

  /**
   * shortcut that maps to this{@link #evaluate(Object, int, int, Object)} with
   * order=1
   * 
   * @param t
   * @param bits
   * @param res
   * @return result
   */
  public default CO evaluate(D t, int bits, CO res)
  {
    return evaluate(t, 1, bits, res);
  }

  public default CO evaluate(D t, int order, int bits)
  {
    CO result = coDomainType().isInterface() ? null : newCoDomainInstance();
    return evaluate(t, order, bits, result);
  }

  /**
   * <pre>
   * Evaluates this function f(t). When called with order = 0, func should write
   * to out the value of f at the point t, evaluated at a precision of prec bits.
   * 
   * In this case, f can be an arbitrary complex function, which may have branch
   * cuts or even be non-holomorphic.
   * 
   * When called with order = n >= 1, the
   * this{@link #evaluate(Object, int, int, Object)} method should write to res
   * the first n coefficients in the Taylor series expansion of f at the point t,
   * evaluated at a precision of prec bits.
   * 
   * NOTE: In this case, the implementation should verify that f is a
   * {@link ComplexFunction} on the complex interval defined by t, and set the
   * coefficients in the result(res) to non-finite values otherwise.
   * 
   * For algorithms that do not rely on derivatives,
   * this{@link #evaluate(Object, int, int, Object)} will always get called with
   * order = 0 or order = 1, in which case the user only needs to implement
   * evaluation of the direct function value (without derivatives).
   * 
   * With order = 1, func must verify holomorphicity (unlike the order = 0 case).
   * 
   * If f is built from field operations and meromorphic functions, then no
   * special action is necessary when order is positive since division by zero or
   * evaluation of builtin functions at poles automatically produces infinite
   * enclosures.
   * 
   * <b>However,special care is needed for bounded functions with branch cuts.
   * </b> For example, when evaluating f , <b>the output must be set to a
   * non-finite value if it overlaps with the branch cut.</b>
   * 
   * The easiest way to accomplish this is to use versions of basic functions
   * (sqrt, log, pow, etc.) that test holomorphicity of their arguments
   * individually.
   * 
   * Some functions with branch cut detection are available as builtins: see
   * acb_sqrt_analytic(), acb_rsqrt_analytic(), acb_log_analytic(),
   * acb_pow_analytic().
   * 
   * @param t     point
   * @param order
   * @param bits  bits of precision the result should be evaluated with
   * @param res   output result
   * @return res after it has been assigned the values of the function evaluated
   *         at t
   */
  public CO evaluate(D t, int order, int bits, CO res);

  public default D newDomainInstance()
  {
    try
    {
      return domainType().getConstructor().newInstance();
    }
    catch (Throwable e)
    {
      wrapOrThrow(e);
      return null;
    }
  }

  public default CO newCoDomainInstance()
  {
    assert !coDomainType().isInterface() : "cannot instantiate the interface class " + coDomainType();
    try
    {
      return coDomainType().getConstructor().newInstance();
    }
    catch (Throwable e)
    {
      wrapOrThrow(e);
      return null;
    }
  }

  @Override
  default String typeset()
  {
    assert false : getClass() + " needs to implement this";
    return null;
  }

}
