package arb.functions;

import static arb.utensils.Utensils.wrapOrThrow;

import java.io.Closeable;
import java.util.*;

import arb.Integer;
import arb.Named;
import arb.Typesettable;
import arb.documentation.BusinessSourceLicenseVersionOnePointOne;
import arb.documentation.TheArb4jLibrary;
import arb.exceptions.CompilerException;
import arb.expressions.*;
import arb.expressions.nodes.VariableNode;
import arb.functions.complex.ComplexFunction;

/**
 * 
 * @param <D>  the domain
 * @param <CO> the co-domain
 * @see BusinessSourceLicenseVersionOnePointOne © terms of the
 *      {@link TheArb4jLibrary}
 */
public interface Function<D, CO> extends
                         Closeable,
                         AutoCloseable,
                         Typesettable,
                         Named
{

  /**
   * Memoization peek over an {@link IndexCache} keyed by signed {@code int}
   * index. The cache is two ArrayLists (non-negative and negative sides) grown
   * on demand, so this is O(1) array indexing — no tree/hash navigation and no
   * key allocation. It supersedes the {@link TreeMap}{@code <Integer,C>} cache
   * whose {@link arb.Integer#compareTo} comparator path dominated profiles, and
   * still handles the negative indices a plain single-ArrayList cache could not.
   *
   * @param cache memoization cache; never {@code null} for generated classes
   * @param n     signed integer index — may be negative
   * @return the cached value if present, otherwise {@code null}
   */
  static <C> C peek(IndexCache<C> cache, arb.Integer n)
  {
    return cache.get(n.getSignedValue());
  }

  /**
   * Memoization peek keyed by both signed {@code int} index and evaluation
   * {@code order}. A value computed at one order is cached in a slot distinct
   * from the same index at another order, so this peek can run for every order
   * (including before the re-entrancy guard) without ever returning a result of
   * the wrong shape.
   *
   * @param cache memoization cache; never {@code null} for generated classes
   * @param n     signed integer index — may be negative
   * @param order evaluation order
   * @return the cached value if present, otherwise {@code null}
   */
  static <C> C peek(IndexCache<C> cache, arb.Integer n, int order)
  {
    return cache.get(n.getSignedValue(), order);
  }

  /**
   * Memoization poke over an {@link IndexCache} keyed by signed {@code int}
   * index. See {@link #peek(IndexCache, arb.Integer)} for the rationale.
   *
   * @return the inserted value (for chaining)
   */
  static <C> C poke(IndexCache<C> cache, arb.Integer n, C value)
  {
    return cache.put(n.getSignedValue(), value);
  }

  /**
   * Memoization poke keyed by both signed {@code int} index and evaluation
   * {@code order}. See {@link #peek(IndexCache, arb.Integer, int)}.
   *
   * @return the inserted value (for chaining)
   */
  static <C> C poke(IndexCache<C> cache, arb.Integer n, int order, C value)
  {
    return cache.put(n.getSignedValue(), order, value);
  }

  /**
   * Memoization peek by primitive {@code int}. Used by generated bytecode which
   * has already extracted the signed value from the input parameter.
   */

  /**
   * Memoization poke by primitive {@code int}. Used by generated bytecode.
   */

  default Context getContext()
  {
    return null;
  }

  /**
   * Source-Expression back-pointer. Expression-compiled Functions return the
   * {@link Expression} that produced them; hand-written Functions return
   * {@code null} unless they choose to expose one. Consumers may also null out a
   * generated class's {@code expression} field directly if they want to drop the
   * back-pointer.
   */
  default <F extends Function<? extends D, ? extends CO>> Expression<D, CO, F> getExpression()
  {
    return null;
  }

  @Override
  default String getName()
  {
    return null;
  }

  @SuppressWarnings("unchecked")
  public default <F extends Function<D, CO>> F derivative()
  {
    throw new UnsupportedOperationException("TODO: " + getClass() + " should implement derivative()");
  }

  /**
   * Lazy on-demand partial derivative with respect to the parameter named by
   * {@code variable}. Implementing classes whose dependence on {@code variable}
   * is symbolic should return a fresh {@link Function} computing
   * {@code ∂this/∂variable}; classes that do not depend on {@code variable}
   * should return the zero function in the codomain.
   *
   * <p>
   * The contract mirrors the no-argument {@link #derivative()}: nothing is
   * pre-compiled at the parent's compile time, the work is paid only when this
   * method is called, and concrete classes are expected to memoize.
   *
   * @param variable location-free handle of the parameter to differentiate w.r.t.
   * @return a {@link Function} computing {@code ∂this/∂variable}
   */
  @SuppressWarnings("unchecked")
  public default <F extends Function<D, CO>> F  derivative(VariableReference<?, ?, ?> variable)
  {
    Expression<?, ?, ?> expr = getExpression();
    if (expr != null)
    {
      return (F) expr.derivative(variable);
    }
    throw new UnsupportedOperationException("TODO: " + getClass() + " should implement derivative(VariableReference) or expose getExpression()");
  }

  /**
   * Convenience overload of {@link #derivative(VariableReference)} taking a
   * variable name. The default resolves the name against {@link #getContext()};
   * implementing classes that already hold a {@link VariableReference} should
   * override to skip the round-trip.
   *
   * @param variableName name of the parameter to differentiate w.r.t.
   * @return a {@link Function} computing {@code ∂this/∂variableName}
   */
  public default <F extends Function<D, CO>> F  derivative(String variableName)
  {
    return derivative(new VariableReference<D, CO, Function<D, CO>>(variableName));
  }

  /**
   * Prototype-pattern copy: produce a fresh instance of this function whose
   * mutable evaluation state (compiled DSL registers, scratch polynomials,
   * Newton-iteration buffers, etc.) is independent of {@code this}, but whose
   * mathematically-meaningful parameters (slope constants, branch indices,
   * orders, etc.) match {@code this} exactly. The intended use is to spread a
   * single-instance Function across multiple worker threads: each worker obtains
   * its own {@link #cloneFunction()} and evaluates concurrently without sharing
   * the per-evaluation registers that make a generated DSL class non-reentrant.
   *
   * <p>
   * The default throws {@link UnsupportedOperationException}. Implement this on
   * any Function whose {@code evaluate} is not reentrant. Generated DSL classes
   * inherit the default and must be cloned by their owner: a Java class that
   * wraps DSL-compiled subfunctions overrides {@code cloneFunction} to return a
   * fresh wrapper whose subfunctions are themselves freshly built (typically by
   * re-running its constructor).
   *
   * @return a fresh function instance independent of {@code this} for the
   *         purposes of concurrent evaluation
   */
  public default <F extends Function<D, CO>> F cloneFunction()
  {
    throw new UnsupportedOperationException(getClass() + " must override cloneFunction() to be safely shared across threads");
  }

  public default <F extends Function<D, CO>> F  derivative(int n)
  {
    @SuppressWarnings("unchecked")
    F result = (F) this;
    for (int i = 0; i < n; i++)
    {
      result = result.derivative();
    }
    return result;
  }

  /**
   * Pointwise negation: returns a new {@link Function} whose value at every t
   * is −this(t). The wrapper writes into the caller's {@code res} buffer — the
   * underlying function evaluates into {@code res}, and the codomain's fluent
   * {@code neg(res)} then negates that same buffer in place. No new codomain
   * instance is allocated by the wrapper.
   *
   * <p>
   * Available for any {@code CO} that exposes {@code neg(CO result)} — i.e.
   * any {@link arb.Field} or {@link arb.Polynomial}.
   */
  public default Function<D, CO> neg()
  {
    Function<D, CO> self = this;
    return (t, order, bits, res) ->
    {
      self.evaluate(t, order, bits, res);
      try
      {
        @SuppressWarnings({ "unchecked", "rawtypes" })
        java.lang.reflect.Method m = res.getClass().getMethod("neg", res.getClass());
        m.invoke(res, res);
        return res;
      }
      catch (ReflectiveOperationException e)
      {
        throw new UnsupportedOperationException("codomain " + res.getClass()
                                                + " does not implement neg(result)",
                                                e);
      }
    };
  }

  public default <F extends Function<D, CO>> F  integral()
  {
    assert false : "TODO: " + getClass() + " should implement this";
    return null;
  }

  /**
   * Multi-variable analogue of {@link #derivative()}: return the Jacobian of this
   * function with respect to a caller-ordered subset of its parameters. The
   * implementing class decides how to produce each partial — symbolic
   * differentiation against its own {@link Context}, ARB jets at the named
   * variable, or anything else appropriate. Unknown variable names should be
   * rejected against this function's parameter list.
   *
   * @param variables ordered list of parameter names whose partials to return
   * @return a {@link Jacobian} whose i-th partial is ∂this/∂variables[i]
   */
  @SuppressWarnings("unchecked")
  public default <F extends Function<D, CO>> Jacobian<D, CO, F> jacobian(String[] variables)
  {
    Expression<D, CO, F> expr = getExpression();
    if (expr == null)
    {
      throw new UnsupportedOperationException("TODO: " + getClass()
                                              + " must implement jacobian(String[]) or expose getExpression()");
    }
    F[] partials = (F[]) java.lang.reflect.Array.newInstance(expr.functionClass, variables.length);
    for (int i = 0; i < variables.length; i++)
    {
      partials[i] = expr.derivative(new VariableReference<>(variables[i]));
    }
    return new Jacobian<D, CO, F>((F) this,
                                  variables,
                                  partials);
  }

  /**
   * Convenience overload of {@link #jacobian(String[])} taking
   * {@link arb.expressions.VariableReference} handles. The default extracts each
   * reference's name and dispatches to {@link #jacobian(String[])}; implementing
   * classes that have direct access to the references (and so can avoid the
   * name-lookup round trip) are free to override.
   */
  public default <F extends Function<D, CO>> Jacobian<D, CO, F>  jacobian(VariableReference<?, ?, ?>[] variables)
  {
    String[] names = new String[variables.length];
    for (int i = 0; i < variables.length; i++)
    {
      names[i] = variables[i].name;
    }
    return jacobian(names);
  }

  /**
   * Convenience overload of {@link #jacobian(String[])} taking
   * {@link arb.expressions.nodes.VariableNode} handles. The default extracts each
   * node's name and dispatches to {@link #jacobian(String[])}; implementing
   * classes that have direct access to the nodes are free to override.
   */
  public default <F extends Function<D, CO>> Jacobian<D, CO, F>  jacobian(VariableNode<?, ?, ?>[] variables)
  {
    String[] names = new String[variables.length];
    for (int i = 0; i < variables.length; i++)
    {
      names[i] = variables[i].getName();
    }
    return jacobian(names);
  }

  /**
   * Drop the cached static-subexpression values so that the next
   * {@link #evaluate(Object, int, int, Object) evaluate} call recomputes every
   * subtree that was lifted into {@code evaluateStaticSubexpressions} by
   * fixed-point static hoisting.
   * <p>
   * Generated classes with at least one hoisted static subexpression override
   * this to reset the internal {@code staticPrecision} sentinel to {@code -1}.
   * Call this whenever a parameter field or a {@link Context} variable that
   * participates in a hoisted subtree has been mutated between calls — e.g.
   * during parameter estimation, Monte-Carlo sweeps, or any workflow that rebinds
   * the bound-parameter instance data rather than constructing a fresh function
   * object. Functions with no hoisted state inherit this no-op default.
   *
   * @see arb.expressions.nodes.StaticNode
   */
  public default void invalidateCache()
  {

  }

  /**
   * Drop only this function's own hoisted state (index cache / value-backing /
   * static precision) WITHOUT cascading to referenced functions, unlike
   * {@link #invalidateCache()}. Used to refresh the caches that depend on a
   * changed context variable while leaving the caches of upstream producers that
   * do not depend on it intact. Functions with no hoisted state inherit this
   * no-op default; cache-bearing generated classes override it.
   */
  public default void invalidateLocalCache()
  {

  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Expression<D, H, Q>
         parseAndCompile(Class<? extends D> domainClass, Class<? extends H> coDomainClass, Class<Q> functionClass, String expression, Context context)
  {
    return Function.parse(Parser.transformToAcceptableJavaIdentifier(expression),
                          expression,
                          context,
                          domainClass,
                          coDomainClass,
                          functionClass,
                          null,
                          null,
                          true)
                   .compile();
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Q
         express(Class<? extends D> class1, Class<? extends H> class2, Class<? extends Q> class3, String expression, Context context)
  {
    return express(class1, class2, class3, null, expression, context);

  }

  @SuppressWarnings("unchecked")
  public static <D, H, Q extends Function<? extends D, ? extends H>> Q express(Class<? extends D> domainClass,
                                                                               Class<? extends H> coDomainClass,
                                                                               String expression)
  {
    return (Q) Function.express(expression, new Context(), domainClass, coDomainClass, Function.class, null);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Q
         express(Class<? extends D> domainClass, Class<? extends H> coDomainClass, Class<? extends Q> functionClass, String expression)
  {
    return Function.express(expression, new Context(), domainClass, coDomainClass, functionClass, null);
  }

  @SuppressWarnings("unchecked")
  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Q
         express(Class<? extends D> domainClass, Class<? extends H> coDomainClass, String functionName, String expression, Context context)
  {
    return (Q) Function.express(expression, context, domainClass, coDomainClass, Function.class, functionName);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Q
         express(Class<? extends D> domainClass, Class<? extends H> coDomainClass, Class<? extends Q> functionClass, String expressionName, String expression)
  {
    return express(domainClass, coDomainClass, functionClass, expressionName, expression, null);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>> Q express(Class<? extends D> domainClass,
                                                                               Class<? extends H> coDomainClass,
                                                                               Class<? extends Q> functionClass,
                                                                               String expressionName,
                                                                               String expression,
                                                                               Context context)
  {
    if (context == null)
    {
      context = new Context();
    }

    FunctionMapping<D, H, Q> functionMapping = context.getFunctionMapping(expressionName);
    if (functionMapping != null && functionMapping.instance != null)
    {
      return functionMapping.instance;
    }

    return Function.express(expression, context, domainClass, coDomainClass, functionClass, expressionName);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Q
         express(String functionName, Class<? extends D> domainClass, Class<? extends H> coDomainClass, Class<? extends Q> functionClass, String expression)
  {
    return Function.express(expression, new Context(), domainClass, coDomainClass, functionClass, functionName);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>> Q express(String functionName,
                                                                               Class<? extends D> domainClass,
                                                                               Class<? extends H> coDomainClass,
                                                                               Class<? extends Q> functionClass,
                                                                               String expression,
                                                                               Context context)
  {
    return Function.express(expression, context, domainClass, coDomainClass, functionClass, functionName);
  }

  static <D, H, Q extends Function<? extends D, ? extends H>> Q express(String expression,
                                                                        Context context,
                                                                        Class<? extends D> domainClass,
                                                                        Class<? extends H> coDomainClass,
                                                                        Class<? extends Q> functionClass,
                                                                        String functionName)
  {
    return express(expression, context, domainClass, coDomainClass, functionClass, functionName, true);
  }

  static <D, H, Q extends Function<? extends D, ? extends H>> Q express(String expression,
                                                                        Context context,
                                                                        Class<? extends D> domainClass,
                                                                        Class<? extends H> coDomainClass,
                                                                        Class<? extends Q> functionClass,
                                                                        String functionName,
                                                                        boolean replace)
  {
    Expression<D, H, Q> compiledParsedAndRegisteredExpression = compile(expression, context, domainClass, coDomainClass, functionClass, functionName, replace);
    if (compiledParsedAndRegisteredExpression.functionMapping != null && compiledParsedAndRegisteredExpression.functionMapping.instance != null)
    {
      return compiledParsedAndRegisteredExpression.functionMapping.instance;
    }
    Q instance = compiledParsedAndRegisteredExpression.instantiate();
    if (compiledParsedAndRegisteredExpression.functionMapping != null)
    {
      compiledParsedAndRegisteredExpression.functionMapping.instance = instance;
    }
    return instance;
  }

  static <D, H, Q extends Function<? extends D, ? extends H>> Expression<D, H, Q> compile(String expression,
                                                                                          Context context,
                                                                                          Class<? extends D> domainClass,
                                                                                          Class<? extends H> coDomainClass,
                                                                                          Class<? extends Q> functionClass,
                                                                                          String functionName,
                                                                                          boolean replace)
  {
    int colonIndex = expression.indexOf(':');
    if (colonIndex != -1)
    {
      var thisFunctionName = expression.substring(0, colonIndex);
      if (functionName != null && !functionName.equals(thisFunctionName))
      {
        throw new CompilerException(String.format("name='%s' specified with : syntax does not match name specified another way '%s'",
                                                  thisFunctionName,
                                                  functionName));
      }
      expression   = expression.substring(colonIndex + 1);
      functionName = thisFunctionName;
    }

    int punctuationMarkIndex = expression.indexOf(":");
    if (punctuationMarkIndex != -1)
    {
      String inlineFunctionName = expression.substring(0, punctuationMarkIndex);
      if (functionName != null && !functionName.equals(inlineFunctionName))
      {
        throw new CompilerException(String.format("functionName='%s' specified via function argument != inlineFunctionName='%s'",
                                                  functionName,
                                                  inlineFunctionName));
      }
      functionName = inlineFunctionName;
      expression   = expression.substring(punctuationMarkIndex + 1, expression.length());
    }
    expression = expression.replaceAll(" ", "");

    FunctionMapping<D, H, Q> mapping = null;
    if (functionName != null && context != null)
    {
      mapping = context.registerFunctionMapping(functionName, null, domainClass, coDomainClass, functionClass, replace, null, expression);
    }

    Expression<D, H, Q> parsedExpression = Parser.parse(expression, context, domainClass, coDomainClass, functionClass, functionName);

    parsedExpression.functionMapping = mapping;
    if (mapping != null)
    {
      mapping.expression = parsedExpression;
    }

    if (context != null)
    {
      context.declare(functionName, domainClass, coDomainClass, functionClass);
    }

    return parsedExpression;
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Expression<D, H, Q>
         parse(Class<? extends D> domainClass, Class<? extends H> coDomainClass, Class<? extends Q> functionClass, String expression)
  {
    return parse(Parser.normalize(expression), expression, null, domainClass, coDomainClass, functionClass, null, null, true);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>>
         Expression<D, H, Q>
         parse(Class<? extends D> domainClass, Class<? extends H> coDomainClass, Class<? extends Q> functionClass, String expression, Context context)
  {
    return parse(Parser.transformToAcceptableJavaIdentifier(expression), expression, context, domainClass, coDomainClass, functionClass, null, null, true);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>> Expression<D, H, Q> parse(Class<? extends D> domainClass,
                                                                                               Class<? extends H> coDomainClass,
                                                                                               Class<? extends Q> functionClass,
                                                                                               String expression,
                                                                                               Context context,
                                                                                               Expression<?, ?, ?> containingExpression)
  {
    String hashString = Parser.transformToAcceptableJavaIdentifier(expression);
    return parse(hashString, expression, context, domainClass, coDomainClass, functionClass, null, containingExpression, true);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>> Expression<D, H, Q> parse(Class<? extends D> domainClass,
                                                                                               Class<? extends H> coDomainClass,
                                                                                               Class<? extends Q> functionClass,
                                                                                               String expression,
                                                                                               Context context,
                                                                                               Expression<?, ?, ?> containingExpression,
                                                                                               boolean simplify)
  {
    String hashString = Parser.transformToAcceptableJavaIdentifier(expression);
    return parse(hashString, expression, context, domainClass, coDomainClass, functionClass, null, containingExpression, simplify);
  }

  public static <D, H, Q extends Function<? extends D, ? extends H>, PD, PC, PF extends Function<? extends PD, ? extends PC>, E extends Expression<D, H, Q>>
         E
         parse(String className,
               String expression,
               Context context,
               Class<? extends D> domainClass,
               Class<? extends H> coDomainClass,
               Class<? extends Q> functionClass,
               String functionName,
               Expression<? extends PD, ? extends PC, ? extends PF> containingExpression,
               boolean simplify)
  {
    return Parser.parseExpression(className, expression, context, domainClass, coDomainClass, functionClass, functionName, containingExpression, simplify);
  }

  /**
   * Extracts function name from expression, registers in context, and parses.
   * Returns the parsed Expression with functionMapping wired up.
   */
  public static <D, H, Q extends Function<? extends D, ? extends H>> Expression<D, H, Q> parseAndRegister(String expression,
                                                                                                          Context context,
                                                                                                          Class<? extends D> domainClass,
                                                                                                          Class<? extends H> coDomainClass,
                                                                                                          Class<? extends Q> functionClass,
                                                                                                          String functionName,
                                                                                                          boolean replace)
  {
    int colonIndex = expression.indexOf(':');
    if (colonIndex != -1)
    {
      var thisFunctionName = expression.substring(0, colonIndex);
      if (functionName != null && !functionName.equals(thisFunctionName))
      {
        throw new CompilerException(String.format("name='%s' specified with : syntax does not match name specified another way '%s'",
                                                  thisFunctionName,
                                                  functionName));
      }
      expression   = expression.substring(colonIndex + 1);
      functionName = thisFunctionName;
    }

    int punctuationMarkIndex = expression.indexOf(":");
    if (punctuationMarkIndex != -1)
    {
      String inlineFunctionName = expression.substring(0, punctuationMarkIndex);
      if (functionName != null && !functionName.equals(inlineFunctionName))
      {
        throw new CompilerException(String.format("functionName='%s' specified via function argument != inlineFunctionName='%s'",
                                                  functionName,
                                                  inlineFunctionName));
      }
      functionName = inlineFunctionName;
      expression   = expression.substring(punctuationMarkIndex + 1);
    }
    expression = expression.replaceAll(" ", "");

    FunctionMapping<D, H, Q> mapping = null;
    if (functionName != null && context != null)
    {
      mapping = context.registerFunctionMapping(functionName, null, domainClass, coDomainClass, functionClass, replace, null, expression);
    }

    Expression<D, H, Q> parsedExpression = Parser.parse(expression, context, domainClass, coDomainClass, functionClass, functionName);

    parsedExpression.functionMapping = mapping;
    if (mapping != null)
    {
      mapping.expression = parsedExpression;
    }

    return parsedExpression;
  }

  public default void close()
  {

  }

  public default Class<CO> coDomainType()
  {
    assert false : "this should be implemented by " + getClass();
    return null;
  }

  public default Class<D> domainType()
  {
    assert false : "this should be implemented by " + getClass();
    return null; // for instance, the RealFunction would return Real.class for both the domain
                 // and coDomain
  }

  public default CO evaluate(D t, int bits)
  {
    return evaluate(t, 1, bits);
  }

  /**
   * shortcut that maps to this{@link #evaluate(Object, int, int, Object)} with
   * order=1
   * 
   * @param t
   * @param bits
   * @param res
   * @return result
   */
  public default CO evaluate(D t, int bits, CO res)
  {
    return evaluate(t, 1, bits, res);
  }

  public default CO evaluate(D t, int order, int bits)
  {
    CO result = coDomainType().isInterface() ? null : newCoDomainInstance();
    return evaluate(t, order, bits, result);
  }

  /**
   * <pre>
   * Evaluates this function f(t). When called with order = 0, func should write
   * to out the value of f at the point t, evaluated at a precision of prec bits.
   * 
   * In this case, f can be an arbitrary complex function, which may have branch
   * cuts or even be non-holomorphic.
   * 
   * When called with order = n >= 1, the
   * this{@link #evaluate(Object, int, int, Object)} method should write to res
   * the first n coefficients in the Taylor series expansion of f at the point t,
   * evaluated at a precision of prec bits.
   * 
   * NOTE: In this case, the implementation should verify that f is a
   * {@link ComplexFunction} on the complex interval defined by t, and set the
   * coefficients in the result(res) to non-finite values otherwise.
   * 
   * For algorithms that do not rely on derivatives,
   * this{@link #evaluate(Object, int, int, Object)} will always get called with
   * order = 0 or order = 1, in which case the user only needs to implement
   * evaluation of the direct function value (without derivatives).
   * 
   * With order = 1, func must verify holomorphicity (unlike the order = 0 case).
   * 
   * If f is built from field operations and meromorphic functions, then no
   * special action is necessary when order is positive since division by zero or
   * evaluation of builtin functions at poles automatically produces infinite
   * enclosures.
   * 
   * <b>However,special care is needed for bounded functions with branch cuts.
   * </b> For example, when evaluating f , <b>the output must be set to a
   * non-finite value if it overlaps with the branch cut.</b>
   * 
   * The easiest way to accomplish this is to use versions of basic functions
   * (sqrt, log, pow, etc.) that test holomorphicity of their arguments
   * individually.
   * 
   * Some functions with branch cut detection are available as builtins: see
   * acb_sqrt_analytic(), acb_rsqrt_analytic(), acb_log_analytic(),
   * acb_pow_analytic().
   * 
   * @param t     point
   * @param order
   * @param bits  bits of precision the result should be evaluated with
   * @param res   output result
   * @return res after it has been assigned the values of the function evaluated
   *         at t
   */
  public CO evaluate(D t, int order, int bits, CO res);

  public default D newDomainInstance()
  {
    try
    {
      return domainType().getConstructor().newInstance();
    }
    catch (Throwable e)
    {
      wrapOrThrow(e);
      return null;
    }
  }

  public default CO newCoDomainInstance()
  {
    assert !coDomainType().isInterface() : "cannot instantiate the interface class " + coDomainType();
    try
    {
      return coDomainType().getConstructor().newInstance();
    }
    catch (Throwable e)
    {
      wrapOrThrow(e);
      return null;
    }
  }

  default String toNameString()
  {
    return toString();
  }

  @Override
  default String typeset()
  {
    assert false : getClass() + " needs to implement this";
    return null;
  }

}
