package arb.mechanics;

import arb.algebraic.geometry.AlgebraicCurve;

/**
 * 
 * 
 * Linkages are linked (or constrained) mechanical structures such as those used
 * in robots, excavators, engines, etc. They are also extensively used for
 * character animation in modeling systems.
 * 
 * Sylvester, Kempe and Cayley developed the geometry associated with the theory
 * of linkages in the 1870s. Kempe proved that every finite segment of an
 * {@link AlgebraicCurve} can be generated by a linkage in the manner of Watt's
 * curve.
 *
 */
public interface Linkage
{

}
