package arb.mechanics;

import arb.Complex;
import arb.Real;
import arb.algebraic.geometry.AlgebraicCurve;
import arb.geometry.Line;
import arb.geometry.curves.*;

/**
 * A curve named after James Watt (1736-1819), the Scottish engineer who
 * developed the steam engine (MacTutor Archive). The {@link Curve} is produced
 * by a linkage of rods connecting two wheels of equal diameter. Let the two
 * wheels have radius b and let their centers be located a distance 2a apart.
 * Furthermore suppose that a rod of length 2c is fixed at each end to the
 * circumference of the two wheels. Let P be the midpoint of the rod. Then
 * Watt's curve C is the locus of P.
 * 
 * Watt's curve is a tricircular algebraic plane curve of degree six. It is
 * generated by two circles of radius b with centers distance 2a apart (taken to
 * be at (±a, 0)). A line segment of length 2c attaches to a point on each of
 * the circles, and the midpoint of the {@link Line} segment traces out the
 * {@link WattsCurve#} as the {@link Circle}s rotate partially back and forth or
 * completely around. It arose in connection with James Watt's pioneering work
 * on the steam engine.
 *
 */
public class WattsCurve implements
                        PlaneCurve,
                        AlgebraicCurve
{

  @Override
  public Complex evaluate(Real t, int order, int prec, Complex res)
  {
    assert false : "implement me";
    return null;
  }

  @Override
  public int degree()
  {
    return 6;
  }

}
