package arb.functions.polynomials.orthogonal.real;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import arb.Integer;
import arb.Real;
import arb.RealPolynomial;
import arb.documentation.BusinessSourceLicenseVersionOnePointOne;
import arb.documentation.TheArb4jLibrary;
import arb.functions.integer.RealPolynomialSequence;
import arb.functions.integer.RealFunctionSequence;
import junit.framework.TestCase;

/**
 * Hermite polynomials generated by repeated differentiation of the generating
 * function G(t,x)=exp(2*x*t-t²), compared against the built-in
 * {@link HermitePolynomials} three-term-recurrence sequence.
 *
 * <p>
 * Since G(t,x)=exp(x²)*exp(-(x-t)²), each t-derivative at t=0 trades for an
 * x-derivative: ∂ⁿG/∂tⁿ|ₜ₌₀ = (-1)ⁿ*exp(x²)*∂ⁿexp(-x²)/∂xⁿ = H(n,x), and the
 * derivative chain H(n)=2*x*H(n-1)-∂H(n-1)/∂x with H(0)=1 is what repeated
 * differentiation of G produces, because ∂G/∂t=(2*x-2*t)*G.
 * </p>
 *
 * @see BusinessSourceLicenseVersionOnePointOne © terms of the
 *      {@link TheArb4jLibrary}
 */
public class HermiteGeneratingFunctionTest extends
                                           TestCase
{
  private static final Logger log = LoggerFactory.getLogger(HermiteGeneratingFunctionTest.class);

  /**
   * The repeated-differentiation form: H(n)=2*x*H(n-1)-diff(H(n-1),x),
   * expressed recursively via the expression compiler, compared against
   * {@link HermitePolynomials}: exactly for the first five orders, then by
   * ball-overlap at escalating orders up to 2000.
   */
  public void testRepeatedDifferentiationOfGeneratingFunction()
  {
    int bits = 128;
    try ( RealPolynomialSequence H =
                                   RealPolynomialSequence.express("H:n➔when(n=0,1,else,2*x*H(n-1)-diff(H(n-1),x))");
          HermitePolynomials reference = new HermitePolynomials(bits))
    {
      for (int n = 0; n < 5; n++)
      {
        try ( Integer index = new Integer(n); RealPolynomial h = new RealPolynomial();
              RealPolynomial ref = new RealPolynomial())
        {
          H.evaluate(index, 1, bits, h);
          reference.evaluate(index, 1, bits, ref);
          if (log.isDebugEnabled())
          {
            log.debug("H({})={} reference={}", n, h, ref);
          }
          assertEquals("order " + n, ref.toString(), h.toString());
        }
      }
      for (int n : new int[]
      { 8, 16, 32, 64, 128, 256, 512, 1024, 2000 })
      {
        try ( Integer index = new Integer(n); RealPolynomial h = new RealPolynomial();
              RealPolynomial ref = new RealPolynomial())
        {
          long start = System.currentTimeMillis();
          H.evaluate(index, 1, bits, h);
          reference.evaluate(index, 1, bits, ref);
          if (log.isDebugEnabled())
          {
            log.debug("order {} compared in {}ms", n, System.currentTimeMillis() - start);
          }
          assertEquals("degree at order " + n, ref.getLength(), h.getLength());
          assertTrue("order " + n, h.overlaps(ref));
        }
      }
    }
  }

  /**
   * The nth-derivative form ∂ⁿG/∂tⁿ|ₜ₌₀ = (-1)ⁿ*exp(x²)*diff(exp(-x²),x^n),
   * with the order n symbolic in the diff node, compared pointwise against
   * {@link HermitePolynomials} for the first five orders.
   */
  public void testNthDerivativeOfGeneratingFunction()
  {
    int bits = 128;
    try ( RealFunctionSequence H =
                                 RealFunctionSequence.express("H:n➔x➔(-1)^n*exp(x²)*diff(exp(-x²),x^n)");
          HermitePolynomials reference = new HermitePolynomials(bits))
    {
      try ( Real point = new Real("0.75",
                                  bits))
      {
        for (int n = 0; n < 5; n++)
        {
          try ( Integer index = new Integer(n); Real value = new Real(); Real refValue = new Real();
                RealPolynomial ref = new RealPolynomial())
          {
            H.apply(n).evaluate(point, 1, bits, value);
            reference.evaluate(index, 1, bits, ref).evaluate(point, 1, bits, refValue);
            if (log.isDebugEnabled())
            {
              log.debug("H({})({})={} reference={}", n, point, value, refValue);
            }
            assertTrue("order " + n + ": " + value + " vs " + refValue, value.overlaps(refValue));
          }
        }
      }
    }
  }
}
