/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

import static arb.RealConstants.*;

public class ComplexMatrix implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public ComplexMatrix(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(ComplexMatrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arbJNI.delete_ComplexMatrix(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  /**
   * Calls {@link arb#acb_mat_clear(ComplexMatrix)}
   * @return this
   */
  public ComplexMatrix clear()
  {
    if ( swigCMemOwn )
    {
      arb.acb_mat_clear(this);
    }
    
    return this;
  }

  @Override
  public void close()
  { 
      clear();
  }
  
  public ComplexMatrix init(int rows, int cols)
  {
    arb.acb_mat_init(this, rows, cols);
    return this;
  } 
  

  public void setNumRows(int value) {
    arbJNI.ComplexMatrix_numRows_set(swigCPtr, this, value);
  }

  public int getNumRows() {
    return arbJNI.ComplexMatrix_numRows_get(swigCPtr, this);
  }

  public void setNumCols(int value) {
    arbJNI.ComplexMatrix_numCols_set(swigCPtr, this, value);
  }

  public int getNumCols() {
    return arbJNI.ComplexMatrix_numCols_get(swigCPtr, this);
  }

  public void setRowPointers(long value) {
    arbJNI.ComplexMatrix_rowPointers_set(swigCPtr, this, value);
  }

  public long getRowPointers() {
    return arbJNI.ComplexMatrix_rowPointers_get(swigCPtr, this);
  }

  public ComplexMatrix() {
    this(arbJNI.new_ComplexMatrix(), true);
  }

}
