/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

public class GMPRandomState {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public GMPRandomState(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(GMPRandomState obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arbJNI.delete_GMPRandomState(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void set_mp_seed(Integer value) {
    arbJNI.GMPRandomState__mp_seed_set(swigCPtr, this, Integer.getCPtr(value), value);
  }

  public Integer get_mp_seed() {
    long cPtr = arbJNI.GMPRandomState__mp_seed_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Integer(cPtr, false);
  }

  public void set_mp_alg(RandomAlgorithm value) {
    arbJNI.GMPRandomState__mp_alg_set(swigCPtr, this, value.swigValue());
  }

  public RandomAlgorithm get_mp_alg() {
    return RandomAlgorithm.swigToEnum(arbJNI.GMPRandomState__mp_alg_get(swigCPtr, this));
  }

  public __gmp_randstate_struct__mp_algdata get_mp_algdata() {
    long cPtr = arbJNI.GMPRandomState__mp_algdata_get(swigCPtr, this);
    return (cPtr == 0) ? null : new __gmp_randstate_struct__mp_algdata(cPtr, false);
  }

  public GMPRandomState() {
    this(arbJNI.new_GMPRandomState(), true);
  }

}
