/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

public class Mantissa {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Mantissa(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Mantissa obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arbJNI.delete_Mantissa(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNoptr(MantissaNoPointer value) {
    arbJNI.Mantissa_noptr_set(swigCPtr, this, MantissaNoPointer.getCPtr(value), value);
  }

  public MantissaNoPointer getNoptr() {
    long cPtr = arbJNI.Mantissa_noptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MantissaNoPointer(cPtr, false);
  }

  public void setPtr(MantissaPointer value) {
    arbJNI.Mantissa_ptr_set(swigCPtr, this, MantissaPointer.getCPtr(value), value);
  }

  public MantissaPointer getPtr() {
    long cPtr = arbJNI.Mantissa_ptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new MantissaPointer(cPtr, false);
  }

  public Mantissa() {
    this(arbJNI.new_Mantissa(), true);
  }

}
