/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

import static arb.Constants.*;

public class RealMatrix implements AutoCloseable {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public RealMatrix(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(RealMatrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        arbJNI.delete_RealMatrix(swigCPtr);
      }
      swigCPtr = 0;
    }
  }


  /**
   * Calls {@link arb#arb_mat_clear(RealMatrix)}
   * @return this
   */
  public RealMatrix clear()
  {
    if ( swigCMemOwn )
    {      
      arb.arb_mat_clear(this);
    }
    return this;
  }

  @Override
  public void close()
  { 
      clear();
  }
  
  
  public RealMatrix init(int rows, int cols)
  {
    arb.arb_mat_init(this, rows, cols);
    return this;
  } 
  

  public void setEntries(Real value) {
    arbJNI.RealMatrix_entries_set(swigCPtr, this, Real.getCPtr(value), value);
  }

  public Real getEntries() {
    long cPtr = arbJNI.RealMatrix_entries_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Real(cPtr, false);
  }

  public void setR(int value) {
    arbJNI.RealMatrix_r_set(swigCPtr, this, value);
  }

  public int getR() {
    return arbJNI.RealMatrix_r_get(swigCPtr, this);
  }

  public void setC(int value) {
    arbJNI.RealMatrix_c_set(swigCPtr, this, value);
  }

  public int getC() {
    return arbJNI.RealMatrix_c_get(swigCPtr, this);
  }

  public void setRows(SWIGTYPE_p_p_arb_struct value) {
    arbJNI.RealMatrix_rows_set(swigCPtr, this, SWIGTYPE_p_p_arb_struct.getCPtr(value));
  }

  public SWIGTYPE_p_p_arb_struct getRows() {
    long cPtr = arbJNI.RealMatrix_rows_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_arb_struct(cPtr, false);
  }

  public RealMatrix() {
    this(arbJNI.new_RealMatrix(), true);
  }

}
