/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package arb;

public class SWIGTYPE_p_mpfr_prec_t {
  private transient long swigCPtr;

  public SWIGTYPE_p_mpfr_prec_t(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  public SWIGTYPE_p_mpfr_prec_t() {
    swigCPtr = 0;
  }

  public static long getCPtr(SWIGTYPE_p_mpfr_prec_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

