<TeXmacs|2.1.1>

<style|<tuple|generic|alt-colors|boring-white|framed-theorems>>

<\body>
  <doc-data|<doc-title|Aronszajn's Theorem on Positive Definite
  Kernels>|<doc-author|<author-data|<author-name|Stephen Crowley and the
  Collective Unconscious \<less\>via ChatGPT\<gtr\>>|<\author-affiliation>
    <date|>
  </author-affiliation>>>>

  \;

  <\theorem>
    <strong|[Aronszajn's Theorem>] A positive definite kernel
    <math|K<around|(|x,y|)>> on a set <math|X> is a reproducing kernel for
    some Hilbert space <math|\<cal-H\>> of functions on <math|X>.
  </theorem>

  <\proof>
    Given a positive definite kernel <math|K>, we define the function
    <math|K<rsub|x>\<assign\>K<around|(|x,\<cdot\>|)>> for each
    <math|x\<in\>X>. We consider the space of functions generated by finite
    linear combinations of the functions <math|K<rsub|x>>. This space is
    pre-Hilbert with the inner product defined by

    <\equation>
      <around|\<langle\>|K<rsub|x>,K<rsub|y>|\<rangle\>>=K<around|(|x,y|)>.
    </equation>

    We then complete this space with respect to the norm induced by the inner
    product to obtain a Hilbert space <math|\<cal-H\>>.

    To show the reproducing property, we take any <math|f\<in\>\<cal-H\>> and
    <math|x\<in\>X>. By the definition of the Hilbert space <math|\<cal-H\>>,
    there exists a sequence <math|<around|{|f<rsub|n>|}>> of finite linear
    combinations of <math|K<rsub|y>> functions such that
    <math|f<rsub|n>\<rightarrow\>f> in <math|\<cal-H\>>. The continuity of
    the inner product gives us

    <\equation>
      f<around|(|x|)>=lim<rsub|n\<to\>\<infty\>>
      f<rsub|n><around|(|x|)>=lim<rsub|n\<to\>\<infty\>><around|\<langle\>|f<rsub|n>,K<rsub|x>|\<rangle\>>=<around|\<langle\>|f,K<rsub|x>|\<rangle\>>.
    </equation>

    This shows that <math|K> has the reproducing property, and thus it is a
    reproducing kernel for <math|\<cal-H\>>.
  </proof>

  In the context of RKHS(ReproducingKernekHilbertSpaces), Bochner's Theorem
  implies that the covariance function of a wide-sense stationary stochastic
  process is a positive definite function and, by Aronszajn's Theorem, such a
  function can be seen as a reproducing kernel of an RKHS. This means that
  the space of square-integrable functions with respect to the measure given
  by Bochner's Theorem can be studied within the framework of an RKHS
  provided by Aronszajn's Theorem.

  \;
</body>

<\initial>
  <\collection>
    <associate|magnification|1.2>
    <associate|page-height|auto>
    <associate|page-medium|paper>
    <associate|page-type|letter>
    <associate|page-width|auto>
  </collection>
</initial>