<TeXmacs|2.1.4>

<style|<tuple|generic|framed-theorems>>

<\body>
  <\hide-preamble>
    <assign|R|<macro|\<bbb-R\>>>

    <assign|B|<macro|\<cal-B\>>>

    <assign|Sig|<macro|\<Sigma\>>>

    <assign|one|<macro|<with|math-font-family|bf|1>>>

    \;
  </hide-preamble>

  <doc-data|<doc-title|Characteristic Functions of Measurable Sets:
  Definition and Equivalence Theorem>|<doc-author|<author-data|<author-name|Stephen
  Crowley>|<\author-affiliation>
    <date|>
  </author-affiliation>>>|<doc-date|>>

  <section*|Notions and Setup>

  Throughout, let <math|<around|(|X,<Sig>|)>> denote a measurable space,
  where <math|X> is a set and <math|<Sig>> is a <math|\<sigma\>>-algebra of
  subsets of <math|X>.<footnote|A <math|\<sigma\>>-algebra
  <math|<Sig>\<subseteq\>\<cal-P\><around|(|X|)>> is a nonempty family of
  subsets of <math|X> that is closed under complementation and countable
  unions. Equivalently: (i) <math|X\<in\><Sig>>, (ii) if <math|A\<in\><Sig>>
  then <math|X\<setminus\>A\<in\><Sig>>, and (iii) if
  <math|<around|(|A<rsub|n>|)><rsub|n\<in\>\<bbb-N\>>\<subseteq\><Sig>>, then
  <math|<big|cup><rsub|n=1><rsup|\<infty\>>A<rsub|n>\<in\><Sig>>.>

  The <em|Borel <math|\<sigma\>>-algebra> on <math|<R>>, denoted
  <math|<B><around|(|<R>|)>> or simply <math|<B>>, is the
  <math|\<sigma\>>-algebra generated by the open subsets of <math|<R>>.

  <\definition>
    [Measurable function] Let <math|<around|(|X,<Sig>|)>> be a measurable
    space and let <math|<around|(|Y,\<cal-T\>|)>> be a measurable space. A
    function <math|f:X\<to\>Y> is said to be
    <math|<around|(|<Sig>,\<cal-T\>|)>><em|-measurable> (or simply
    <em|measurable> when the <math|\<sigma\>>-algebras are understood) if for
    every <math|B\<in\>\<cal-T\>>, the preimage
    <math|f<rsup|-1><around|(|B|)>> belongs to <math|<Sig>>.
  </definition>

  In particular, for real-valued functions <math|f:X\<to\><R>>, measurability
  means <math|f<rsup|-1><around|(|B|)>\<in\><Sig>> for every Borel set
  <math|B\<in\><B>>. It is often sufficient (and equivalent) to check
  <math|f<rsup|-1><around|(|<around|(|-\<infty\>,\<alpha\>|)>|)>\<in\><Sig>>
  for all <math|\<alpha\>\<in\><R>>, because the family
  <math|<around|{|<around|(|-\<infty\>,\<alpha\>|)>:\<alpha\>\<in\><R>|}>>
  generates <math|<B>>.

  <\definition>
    [Characteristic (indicator) function] For a subset <math|E\<subseteq\>X>,
    the <em|characteristic function> (also called the <em|indicator
    function>) of <math|E> is the map <math|\<chi\><rsub|E>:X\<to\><R>>
    defined by

    <\equation>
      \<chi\><rsub|E><around|(|x|)>\<assign\><choice|<tformat|<table|<row|<cell|1,>|<cell|x\<in\>E>>|<row|<cell|0,>|<cell|x\<nin\>E>>>>>
    </equation>
  </definition>

  <\definition>
    [Simple function] A function <math|s:X\<to\><R>> is called a <em|simple
    function> if it takes only finitely many real values. Equivalently, there
    exist real numbers <math|a<rsub|1>,\<ldots\>,a<rsub|n>> and pairwise
    disjoint measurable subsets <math|E<rsub|1>,\<ldots\>,E<rsub|n>\<in\><Sig>>
    with <math|<big|cup><rsub|k=1><rsup|n>E<rsub|k>=X> such that

    <\equation>
      s<around|(|x|)>=<big|sum><rsub|k=1><rsup|n>a<rsub|k>*<space|0.17em>\<chi\><rsub|E<rsub|k>><around|(|x|)>*<space|1em><text|>\<forall\>x\<in\>X
    </equation>

    A simple function is said to be <em|measurable> if each <math|E<rsub|k>>
    belongs to <math|<Sig>>.
  </definition>

  <section*|Main Result>

  <\theorem>
    [Equivalence of measurability for characteristic functions and sets] Let
    <math|<around|(|X,<Sig>|)>> be a measurable space and let
    <math|E\<subseteq\>X>. The following are equivalent:

    <\enumerate>
      <item><math|E\<in\><Sig>>

      <item>The characteristic function <math|\<chi\><rsub|E>:<around|(|X,<Sig>|)>\<to\><around|(|<R>,<B>|)>>
      is measurable
    </enumerate>
  </theorem>

  <\proof>
    The proof is divided into two implications.

    <vspace*|1fn><no-indent><em|(1) <math|\<Rightarrow\>> (2):> Assume
    <math|E\<in\><Sig>>. To show that <math|\<chi\><rsub|E>> is measurable,
    it suffices to verify that <math|\<chi\><rsub|E><rsup|-1><around|(|<around|(|-\<infty\>,\<alpha\>|)>|)>\<in\><Sig>>
    for all <math|\<alpha\>\<in\><R>>. For any <math|x\<in\>X>, the only
    possible values are <math|\<chi\><rsub|E><around|(|x|)>\<in\><around|{|0,1|}>>.
    Hence, for a fixed <math|\<alpha\>\<in\><R>>, the set
    <math|<around|{|x\<in\>X:\<chi\><rsub|E><around|(|x|)>\<less\>\<alpha\>|}>>
    can be determined by comparing <math|\<alpha\>> with <math|0> and
    <math|1>. Consider the following exhaustive cases:

    <\itemize>
      <item>If <math|\<alpha\>\<le\>0>, then
      <math|\<chi\><rsub|E><around|(|x|)>\<ge\>0> for all <math|x>, so
      <math|<around|{|x:\<chi\><rsub|E><around|(|x|)>\<less\>\<alpha\>|}>=\<varnothing\>>,
      which belongs to <math|<Sig>> because <math|\<varnothing\>\<in\><Sig>>.

      <item>If <math|0\<less\>\<alpha\>\<le\>1>, then
      <math|\<chi\><rsub|E><around|(|x|)>\<less\>\<alpha\>> holds if and only
      if <math|\<chi\><rsub|E><around|(|x|)>=0>, equivalently
      <math|x\<nin\>E>. Thus <math|<around|{|x:\<chi\><rsub|E><around|(|x|)>\<less\>\<alpha\>|}>=X\<setminus\>E>,
      which belongs to <math|<Sig>> because <math|<Sig>> is closed under
      complementation and <math|E\<in\><Sig>>.

      <item>If <math|\<alpha\>\<gtr\>1>, then
      <math|\<chi\><rsub|E><around|(|x|)>\<less\>\<alpha\>> for all
      <math|x\<in\>X>, hence <math|<around|{|x:\<chi\><rsub|E><around|(|x|)>\<less\>\<alpha\>|}>=X>,
      which belongs to <math|<Sig>> since <math|X\<in\><Sig>>.
    </itemize>

    Since in all cases <math|\<chi\><rsub|E><rsup|-1><around|(|<around|(|-\<infty\>,\<alpha\>|)>|)>\<in\><Sig>>,
    the function <math|\<chi\><rsub|E>> is measurable.

    <vspace*|1fn><no-indent><em|(2) <math|\<Rightarrow\>> (1):> Assume
    <math|\<chi\><rsub|E>> is measurable. Consider the Borel set
    <math|<around|(|0,\<infty\>|)>\<in\><B>>. Observing that
    <math|\<chi\><rsub|E><around|(|x|)>\<gtr\>0> holds if and only if
    <math|x\<in\>E>, one has

    <\equation>
      E<space|0.27em>=<space|0.27em><around|{|x\<in\>X:\<chi\><rsub|E><around|(|x|)>\<gtr\>0|}><space|0.27em>=<space|0.27em>\<chi\><rsub|E><rsup|-1><around|(|<around|(|0,\<infty\>|)>|)>
    </equation>

    By measurability of <math|\<chi\><rsub|E>>, the preimage
    <math|\<chi\><rsub|E><rsup|-1><around|(|<around|(|0,\<infty\>|)>|)>>
    belongs to <math|<Sig>>. Therefore <math|E\<in\><Sig>>.

    <vspace*|1fn>Both implications have been established, completing the
    proof of the equivalence.
  </proof>

  <section*|Additional Remarks>

  <\remark>
    Equivalent characterizations can be obtained using other generating
    families of <math|<B>>, for example by verifying that
    <math|\<chi\><rsub|E><rsup|-1><around|(|<around|(|-\<infty\>,\<alpha\>|]>|)>\<in\><Sig>>
    for all <math|\<alpha\>\<in\><R>>, which leads to the same case analysis
    with the sets <math|\<varnothing\>>, <math|X\<setminus\>E>, and <math|X>.
  </remark>

  <\remark>
    Linear combinations of characteristic functions produce simple functions.
    Conversely, every simple function can be written as a finite linear
    combination of characteristic functions of measurable subsets. This
    relationship underlies the construction of nonnegative measurable
    functions as monotone limits of measurable simple functions, a key step
    in the development of the Lebesgue integral.
  </remark>
</body>

<\initial>
  <\collection>
    <associate|magnification|1.2>
    <associate|page-height|auto>
    <associate|page-medium|paper>
    <associate|page-type|letter>
    <associate|page-width|auto>
  </collection>
</initial>

<\references>
  <\collection>
    <associate|auto-1|<tuple|?|1|../../.TeXmacs/texts/scratch/no_name_2.tm>>
    <associate|auto-2|<tuple|2|2|../../.TeXmacs/texts/scratch/no_name_2.tm>>
    <associate|auto-3|<tuple|3|2|../../.TeXmacs/texts/scratch/no_name_2.tm>>
    <associate|footnote-1|<tuple|1|1|../../.TeXmacs/texts/scratch/no_name_2.tm>>
    <associate|footnr-1|<tuple|1|1|../../.TeXmacs/texts/scratch/no_name_2.tm>>
  </collection>
</references>

<\auxiliary>
  <\collection>
    <\associate|toc>
      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|Notions
      and Setup> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-1><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|Main
      Result> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-2><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|Additional
      Remarks> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-3><vspace|0.5fn>
    </associate>
  </collection>
</auxiliary>