<TeXmacs|2.1.1>

<style|<tuple|generic|alt-colors|boring-white|framed-theorems>>

<\body>
  <doc-data|<doc-title|Interconnections of Aronszajn's, Riesz, and Bochner's
  Theorems>|<doc-author|<author-data|<author-name|Stephen Crowley and the
  Collective Unconscious \<less\>via ChatGPT\<gtr\>>|<\author-affiliation>
    <date|>
  </author-affiliation>>>>

  <\theorem>
    [Aronszajn's Theorem] A positive definite kernel <math|K<around|(|x,y|)>>
    on a set <math|X> is a reproducing kernel for some Hilbert space
    <math|\<cal-H\>> of functions on <math|X>.
  </theorem>

  <\proof>
    Given a positive definite kernel <math|K>, we define the function
    <math|K<rsub|x>\<assign\>K<around|(|x,\<cdot\>|)>> for each
    <math|x\<in\>X>. We consider the space of functions generated by finite
    linear combinations of the functions <math|K<rsub|x>>. This space is
    pre-Hilbert with the inner product defined by

    <\equation*>
      <around|\<langle\>|K<rsub|x>,K<rsub|y>|\<rangle\>>=K<around|(|x,y|)>.
    </equation*>

    We then complete this space with respect to the norm induced by the inner
    product to obtain a Hilbert space <math|\<cal-H\>>.

    To show the reproducing property, we take any <math|f\<in\>\<cal-H\>> and
    <math|x\<in\>X>. By the definition of the Hilbert space <math|\<cal-H\>>,
    there exists a sequence <math|<around|{|f<rsub|n>|}>> of finite linear
    combinations of <math|K<rsub|y>> functions such that
    <math|f<rsub|n>\<rightarrow\>f> in <math|\<cal-H\>>. The continuity of
    the inner product gives us

    <\equation*>
      f<around|(|x|)>=lim<rsub|n\<to\>\<infty\>>
      f<rsub|n><around|(|x|)>=lim<rsub|n\<to\>\<infty\>><around|\<langle\>|f<rsub|n>,K<rsub|x>|\<rangle\>>=<around|\<langle\>|f,K<rsub|x>|\<rangle\>>.
    </equation*>

    This shows that <math|K> has the reproducing property, and thus it is a
    reproducing kernel for <math|\<cal-H\>>.
  </proof>

  <section*|Connection to Riesz and Bochner's Theorems>

  The Riesz Representation Theorem and Bochner's Theorem are closely related
  to Aronszajn's Theorem in the context of Hilbert space theory.

  <\theorem>
    [Riesz Representation Theorem] Every continuous linear functional on a
    Hilbert space <math|\<cal-H\>> can be represented as an inner product
    with a unique element from <math|\<cal-H\>>.
  </theorem>

  This theorem underpins the reproducing property in Aronszajn's Theorem,
  showing that point evaluations in RKHS are continuous linear functionals
  that can be represented by the inner product with kernel functions.

  <\theorem>
    [Bochner's Theorem] A function <math|f> on the real line is the Fourier
    transform of a positive measure if and only if it is continuous and
    positive definite.
  </theorem>

  Bochner's Theorem characterizes the positive definite functions as Fourier
  transforms of positive measures, which in the context of RKHS, relates to
  the covariance function of wide-sense stationary stochastic processes.

  \;
</body>

<\initial>
  <\collection>
    <associate|magnification|1.2>
    <associate|page-height|auto>
    <associate|page-medium|paper>
    <associate|page-type|letter>
    <associate|page-width|auto>
  </collection>
</initial>

<\references>
  <\collection>
    <associate|auto-1|<tuple|1|1|../../.TeXmacs/texts/scratch/no_name_5.tm>>
  </collection>
</references>

<\auxiliary>
  <\collection>
    <\associate|toc>
      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|Connection
      to Riesz and Bochner's Theorems> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-1><vspace|0.5fn>
    </associate>
  </collection>
</auxiliary>