<TeXmacs|2.1.1>

<style|<tuple|generic|alt-colors|boring-white|framed-theorems>>

<\body>
  \;

  <section*|The approximation of functions in the Sobolev space>

  Suppose <math|\<Omega\>=<around|[|0,1|]>>, then for any
  <math|\<gamma\>\<in\>\<bbb-N\><rsub|0>> (the set of all non-negative
  integers), the weighted Sobolev space <math|H<rsub|w><rsup|\<gamma\>><around|(|\<Omega\>|)>>
  can be defined in the usual way, which indicates its inner product,
  semi-norm and norm by

  <\equation>
    <around|(|u,v|)><rsub|w,\<Omega\>><rsup|<around|(|\<gamma\>|)>>
  </equation>

  <\equation>
    <around|\||v|\|><rsub|w,\<Omega\>><rsup|<around|(|\<gamma\>|)>>
  </equation>

  and

  <\equation>
    <around|\<\|\|\>|v|\<\|\|\>><rsub|w,\<Omega\>><rsup|<around|(|\<gamma\>|)>>
  </equation>

  respectively. In particular,

  <\equation>
    L<rsub|2><around|(|\<Omega\>|)>=H<rsub|w><rsup|0><around|(|\<Omega\>|)>
  </equation>

  <\equation>
    <around|\<\|\|\>|v|\<\|\|\>><rsub|w,\<Omega\>>=<around|\<\|\|\>|v|\<\|\|\>><rsub|w,\<Omega\>><rsup|<around|(|0|)>>
  </equation>

  and

  <\equation>
    H<rsub|w><rsup|\<gamma\>><around|(|\<Omega\>|)>=<around|{|f\<mid\>f<text|can
    be measured>,<around|\<\|\|\>|f|\<\|\|\>><rsub|w,\<Omega\>>\<less\>\<infty\>|}>
  </equation>

  \;

  <\equation>
    <around|\<\|\|\>|f|\<\|\|\>><rsub|w,\<Omega\>><rsup|\<gamma\>>=<sqrt|<around*|(|<big|sum><rsub|i=0><rsup|\<infty\>><around|\||f<rsup|<around|(|i|)>>|\|><rsup|2><rsub|w,\<Omega\>>|)>>
  </equation>

  <\equation>
    <around|\||f|\|><rsub|w,\<Omega\>><rsup|\<gamma\>>=<around|\||f<rsup|<around|(|\<gamma\>|)>>|\|><rsub|w,\<Omega\>>
  </equation>

  Now we can suppose the function <math|f\<in\>H<rsub|w><rsup|\<gamma\>><around|(|\<Omega\>|)>>
  in

  <\equation>
    p<rsub|m,\<alpha\>,\<beta\>><around|(|\<Omega\>|)>=<text|span><around|{|p<rsub|0><rsup|\<alpha\>,\<beta\>><around|(|x|)>,p<rsub|1><rsup|\<alpha\>,\<beta\>><around|(|x|)>,\<ldots\>,p<rsub|m><rsup|\<alpha\>,\<beta\>><around|(|x|)>|}><text|>
  </equation>

  as presented in the following formula:

  <\equation>
    f<around|(|x|)>=<big|sum><rsub|i=0><rsup|\<infty\>>k<rsub|i>*p<rsub|i><rsup|\<alpha\>,\<beta\>><around|(|x|)><text|>
  </equation>

  In which the coefficients <math|k<rsub|i>> are generated by:

  <\equation>
    k<rsub|i>=<frac|1|g<rsub|i><rsup|2>>*<big|int><rsub|0><rsup|1>p<rsub|i><rsup|\<alpha\>,\<beta\>><around|(|x|)>*w<rsub|\<alpha\>,\<beta\>><around|(|x|)>*d*x,<space|1em>i=0,\<ldots\>.<text|>
  </equation>

  In practice, only the first <math|m>-terms shifted Jacobi polynomials are
  taken into account. Then we have:

  <\equation>
    f<around|(|x|)>=<big|sum><rsub|i=0><rsup|m-1>k<rsub|i>*p<rsub|i><rsup|\<alpha\>,\<beta\>><around|(|x|)>=K<rsup|T>*P<text|>
  </equation>

  with

  <\equation>
    K=<around|[|k<rsub|0>,k<rsub|1>,\<ldots\>,k<rsub|m-1>|]><rsup|T><text|>
  </equation>

  <\equation>
    P=<around|[|p<rsub|0><rsup|\<alpha\>,\<beta\>><around|(|x|)>,p<rsub|1><rsup|\<alpha\>,\<beta\>><around|(|x|)>,\<ldots\>,p<rsub|m-1><rsup|\<alpha\>,\<beta\>><around|(|x|)>|]>
  </equation>

  In as much as <math|p<rsub|m,\<alpha\>,\<beta\>>> is a finite dimensional
  vector space, <math|f> has a unique best approximation from
  <math|p<rsub|m,\<alpha\>,\<beta\>>>, say
  <math|f<rsub|m><around|(|x|)>\<in\>p<rsub|m,\<alpha\>,\<beta\>>> that is:

  <\equation>
    \<forall\>y\<in\>p<rsub|m,\<alpha\>,\<beta\>>,<around|\<\|\|\>|f<around|(|x|)>-f<rsub|m><around|(|x|)>|\<\|\|\>><rsub|w,\<Omega\>>\<leq\><around|\<\|\|\>|f<around|(|x|)>-y|\<\|\|\>><rsub|w,\<Omega\>><text|>
  </equation>

  Guo and Wang (2004), came to the conclusion that for any
  <math|f\<in\>H<rsub|w><rsup|\<gamma\>><around|(|\<Omega\>|)>>,
  <math|\<gamma\>\<in\>\<bbb-N\><rsub|0>> and
  <math|0\<leq\>\<mu\>\<leq\>\<gamma\>>, a generic positive constant <math|C>
  independent of any function, <math|m>, <math|\<alpha\>> and <math|\<beta\>>
  exists so that:

  <\equation>
    <around|\<\|\|\>|f<around|(|x|)>-f<rsub|m><around|(|x|)>|\<\|\|\>><rsub|w,\<Omega\>><rsup|\<gamma\>,\<mu\>>\<leq\>C*<around|(|<around|(|m-1|)>*\<Gamma\>*<around|(|\<alpha\>+\<beta\>+1|)>|)><rsup|-\<mu\>><frac|1|2><around|\||f|\|><rsub|w,\<Omega\>><rsup|\<gamma\>><text|>
  </equation>

  <section*|The operational matrix of fractional integral>

  We can express Riemann-Liouville fractional integral operator of order
  <math|\<mu\>> of the vector by:

  <\equation>
    I<rsup|\<mu\>>*P\<approx\>Q<rsup|<around|(|\<mu\>|)>>*P<text|>
  </equation>

  where <math|Q<rsup|<around|(|\<mu\>|)>>> is the <math|m\<times\>n>
  operational matrix of Riemann-Liouville fractional integral of order
  <math|\<mu\>>.

  <subsection*|Theorem 3.1.>

  If <math|Q<rsup|<around|(|\<mu\>|)>>> is the <math|m\<times\>n> operational
  matrix of Riemann-Liouville fractional integral of order <math|\<mu\>>,
  then the elements of this matrix are taken as:

  <\equation>
    Q<rsup|<around|(|\<mu\>|)>><rsub|i,j>=<around*|{|q<rsub|i,j><rsup|<around|(|\<mu\>|)>>|}><rsub|i,j=0><rsup|n-1>=<big|sum><rsub|k=0><rsup|i><binom|i|k>P<rsub|i-k><rsup|<around|(|\<mu\>|)>><around|(|j|)>*<around*|[|\<Gamma\>*<around|(|k+1|)>*B<around|(|k+l+\<mu\>+\<beta\>+1,\<alpha\>+1|)>|]><text|>
  </equation>

  Now, we define the error vector <math|E>, as

  <\equation>
    E=I<rsup|\<mu\>>*P-Q<rsup|<around|(|\<mu\>|)>>*P<text|>
  </equation>

  <\equation*>
    <around|\<\|\|\>|E<rsub|n>|\<\|\|\>>\<leq\><choice|<tformat|<table|<row|<cell|<frac|m!|\<Gamma\>*<around|(|m-\<mu\>+1|)>><around*|(|<frac|L|x<rsub|0>>|)><rsup|\<mu\>><frac|m+\<beta\>|m>*B<around|(|\<alpha\>+1,\<beta\>+1|)>>|<cell|\<beta\>\<geq\>0>>|<row|<cell|<frac|m!|\<Gamma\>*<around|(|m-\<mu\>+1|)>><around*|(|<frac|L|x<rsub|0>>|)><rsup|\<mu\>>*B<around|(|\<alpha\>+1,\<beta\>+1|)>>|<cell|\<beta\>\<less\>0>>>>><space|1em><around|(|3.3|)>
  </equation*>

  where <math|x<rsub|0>\<gtr\>0> and <math|L=max
  <around|{|1,-x<rsub|0>,x<rsub|b>|}>>.

  <section*|4. Main Results>

  <with|font-series|bold|Lemma 4.1.> Let

  <\equation>
    K=<around|[|k<rsub|0>,k<rsub|1>,\<ldots\>,k<rsub|n-1>|]><rsup|T>
  </equation>

  <\equation>
    P=<around|[|P<rsub|0><rsup|\<alpha\>,\<beta\>><around|(|x|)>,P<rsub|1><rsup|\<alpha\>,\<beta\>><around|(|x|)>,\<ldots\>,P<rsub|n-1><rsup|\<alpha\>,\<beta\>><around|(|x|)>|]>
  </equation>

  Now if we suppose that <math|Q<rsup|<around|(|\<mu\>|)>>> is the same in
  Theorem (3.1). Then,

  <\equation*>
    P<rsup|T><around|(|Q<rsup|<around|(|\<mu\>|)>>|)><rsup|T>*K=H*P<space|1em><around|(|4.1|)>
  </equation*>

  where

  <\equation>
    H=<around|(|h<rsub|i,j>|)><rsub|i,j=0,1,\<ldots\>,n-1>
  </equation>

  with

  <\equation*>
    h<rsub|i,j>=<frac|2<rsup|\<alpha\>+\<beta\>>|\<gamma\><rsub|i><rsup|\<alpha\>,\<beta\>>>*<big|int><rsub|0><rsup|1>P<rsub|i><rsup|\<alpha\>,\<beta\>><around|(|x|)>*P<rsub|j><rsup|\<alpha\>,\<beta\>><around|(|x|)><around*|(|<big|sum><rsub|\<ell\>=0><rsup|n-1>P<rsub|\<ell\>><rsup|\<alpha\>,\<beta\>><around|(|x|)>*k<rsub|\<ell\>>|)>*\<omega\><rsub|\<alpha\>,\<beta\>><around|(|x|)>*<space|0.17em>d*x
  </equation*>

  <math|\<forall\>i,j=0,1,\<ldots\>,n-1>

  <with|font-series|bold|Proof:> We denote
  <math|P<rsub|i><rsup|\<alpha\>,\<beta\>><around|(|x|)>> as
  <math|p<rsub|i>>, <math|i=0,1,\<ldots\>,n-1>. We have

  <\equation*>
    P<rsup|T><around|(|Q<rsup|<around|(|\<mu\>|)>>|)><rsup|T>*K=<around*|[|<tabular*|<tformat|<table|<row|<cell|p<rsub|0>>>|<row|<cell|p<rsub|1>>>|<row|<cell|\<vdots\>>>|<row|<cell|p<rsub|n-1>>>>>>|]><rsup|T><around*|[|<tabular*|<tformat|<table|<row|<cell|q<rsup|<around|(|\<mu\>|)>><rsub|00>>|<cell|q<rsup|<around|(|\<mu\>|)>><rsub|01>>|<cell|\<cdots\>>|<cell|q<rsup|<around|(|\<mu\>|)>><rsub|0,n-1>>>|<row|<cell|q<rsup|<around|(|\<mu\>|)>><rsub|10>>|<cell|q<rsup|<around|(|\<mu\>|)>><rsub|11>>|<cell|\<cdots\>>|<cell|q<rsup|<around|(|\<mu\>|)>><rsub|1,n-1>>>|<row|<cell|\<vdots\>>|<cell|\<vdots\>>|<cell|\<ddots\>>|<cell|\<vdots\>>>|<row|<cell|q<rsup|<around|(|\<mu\>|)>><rsub|n-1,0>>|<cell|q<rsup|<around|(|\<mu\>|)>><rsub|n-1,1>>|<cell|\<cdots\>>|<cell|q<rsup|<around|(|\<mu\>|)>><rsub|n-1,n-1>>>>>>|]><around*|[|<tabular*|<tformat|<table|<row|<cell|k<rsub|0>>>|<row|<cell|k<rsub|1>>>|<row|<cell|\<vdots\>>>|<row|<cell|k<rsub|n-1>>>>>>|]>
  </equation*>

  <\equation*>
    =<around*|[|<tabular*|<tformat|<table|<row|<cell|k<rsub|0>*<big|sum><rsub|i=0><rsup|n-1>p<rsub|0>*q<rsup|<around|(|\<mu\>|)>><rsub|0*i>+k<rsub|1>*<big|sum><rsub|i=0><rsup|n-1>p<rsub|0>*q<rsup|<around|(|\<mu\>|)>><rsub|1*i>+\<cdots\>+k<rsub|n-1>*<big|sum><rsub|i=0><rsup|n-1>p<rsub|0>*q<rsup|<around|(|\<mu\>|)>><rsub|n-1,i>>>|<row|<cell|\<vdots\>>>|<row|<cell|k<rsub|0>*<big|sum><rsub|i=0><rsup|n-1>p<rsub|n-1>*q<rsup|<around|(|\<mu\>|)>><rsub|0*i>+k<rsub|1>*<big|sum><rsub|i=0><rsup|n-1>p<rsub|n-1>*q<rsup|<around|(|\<mu\>|)>><rsub|1*i>+\<cdots\>+k<rsub|n-1>*<big|sum><rsub|i=0><rsup|n-1>p<rsub|n-1>*q<rsup|<around|(|\<mu\>|)>><rsub|n-1,i>>>>>>|]>
  </equation*>
</body>

<\initial>
  <\collection>
    <associate|magnification|1.2>
    <associate|page-height|auto>
    <associate|page-medium|paper>
    <associate|page-type|letter>
    <associate|page-width|auto>
  </collection>
</initial>

<\references>
  <\collection>
    <associate|auto-1|<tuple|?|1>>
    <associate|auto-2|<tuple|16|2>>
    <associate|auto-3|<tuple|17|2>>
    <associate|auto-4|<tuple|19|?>>
  </collection>
</references>

<\auxiliary>
  <\collection>
    <\associate|toc>
      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|The
      approximation of functions in the Sobolev space>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-1><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|The
      operational matrix of fractional integral>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-2><vspace|0.5fn>

      <with|par-left|<quote|1tab>|Theorem 3.1.
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-3>>
    </associate>
  </collection>
</auxiliary>