<TeXmacs|2.1.1>

<style|<tuple|article|alt-colors|boring-white|framed-theorems>>

<\body>
  <doc-data|<\doc-title>
    Nonintegrable Kernel Functions on Noncompact Domains: Mercer's and
    Bochner's Theorems
  </doc-title>|<doc-author|<author-data|<author-name|Stephen
  Crowley>|<\author-affiliation>
    <date|>
  </author-affiliation>>>>

  <\table-of-contents|toc>
    <vspace*|1fn><with|font-series|bold|math-font-series|bold|1<space|2spc>Introduction>
    <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-1><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|2<space|2spc>Mercer's
    Theorem> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-2><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|3<space|2spc>Bochner's
    Theorem and Harmonic Analysis> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-3><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|Bibliography>
    <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-4><vspace|0.5fn>
  </table-of-contents>

  <section|Introduction>

  In this article, we explore the powerful combination of Mercer's and
  Bochner's theorems, particularly in the context of non-integrable kernels
  on non-compact domains. A classic example of such a kernel is
  <math|K<around|(|x,y|)>=J<rsub|0><around|(|<around|\||x-y|\|>|)>>, where
  <math|J<rsub|0>> denotes the Bessel function of the first kind.

  <section|Mercer's Theorem>

  The following is reproduced directly from <cite-detail|RieszNagyFA|98
  p.245>

  <\theorem>
    If the transformation <math|A> generated by the continuous symmetric
    kernel <math|A<around|(|x,y|)>>, that is, if
    <math|A<around|(|f|)>\<geq\>0\<forall\>f> or, equivalently, if all the
    characteristic numbers are positive <math|\<mu\><rsub|i>\<geq\>0\<forall\>i>
    , the development (20) is uniformly convergent.\ 
  </theorem>

  This theorem extends immediately to the case where all but a finite number
  of the <math|\<mu\>\<neq\>0> are of the same sign, positive or negative. We
  observe first that since the kernel <math|A<around|(|x,y|)>> is continuous,
  all the image functions

  <\equation>
    A<around|(|f|)><around|(|x|)>=<big|int>A<around|(|x,y|)>*f<around|(|y|)>*<space|0.17em>d*y
  </equation>

  are continuous; therefore, in particular, all the characteristic functions

  <\equation>
    \<varphi\><rsub|n><around|(|x|)>=<frac|1|\<mu\><rsub|n>>*A<around|(|\<varphi\><rsub|n>|)><around|(|x|)>
  </equation>

  \ are continuous. Consequently the \Premainders\Q

  <\equation>
    A<rsub|n><around|(|x,y|)>=A<around|(|x,y|)>-<big|sum><rsub|i=1><rsup|n>\<mu\><rsub|i>*\<varphi\><rsub|i><around|(|x|)>*\<varphi\><rsub|i><around|(|y|)>
  </equation>

  are also continuous functions. Since we have

  <\equation>
    <big|int><big|int>A<rsub|n><around|(|x,y|)>*f<around|(|x|)>*f<around|(|y|)>*<space|0.17em>d*x*<space|0.17em>d*y=<big|sum><rsub|i=n+1><rsup|\<infty\>>\<mu\><rsub|i><around*|(|<big|int>f*\<varphi\><rsub|i>|)><rsup|2>\<geq\>0<label|doubleint>
  </equation>

  for every element <math|f> of <math|L<rsup|2>>.

  From this we deduce that <math|A<rsub|n><around|(|x,y|)>\<geq\>0>. In fact,
  if we had <math|A<rsub|n><around|(|x<rsub|0>,y<rsub|0>|)>\<less\>0>, we
  should have by continuity <math|A<rsub|n><around|(|x,y|)>\<less\>0> in a
  certain neighborhood of the point <math|<around|(|x<rsub|0>,y<rsub|0>|)>>.
  Setting <math|f<around|(|x|)>=1> for <math|x<rsub|0>-\<delta\>\<less\>x\<less\>x<rsub|0>+\<delta\>>
  and <math|f<around|(|x|)>=0> elsewhere, integral (<reference|doubleint>)
  would become negative, a contradiction. Hence we have

  <\equation>
    A<rsub|n><around|(|x,x|)>=A<around|(|x,x|)>-<big|sum><rsub|i=1><rsup|n>\<mu\><rsub|i>*\<varphi\><rsub|i><rsup|2><around|(|x|)>\<geq\>0
  </equation>

  for <math|n=1,2,\<ldots\>>. From this we conclude that the series of
  positive terms

  <\equation>
    <big|sum><rsub|i=1><rsup|\<infty\>>\<mu\><rsub|i>*\<varphi\><rsub|i><rsup|2><around|(|x|)>
  </equation>

  is convergent and that its sum is <math|\<leq\>A<around|(|x,x|)>>. Denoting
  by <math|M> the maximum of the continuous function
  <math|A<around|(|x,x|)>>, we have by Cauchy's inequality:

  <\equation>
    <around*|(|<big|sum><rsub|i=1><rsup|n>\<mu\><rsub|i>*\<varphi\><rsub|i><around|(|x|)>*\<varphi\><rsub|i><around|(|y|)>|)><rsup|2>\<leq\><big|sum><rsub|i=1><rsup|n>\<mu\><rsub|i>*\<varphi\><rsub|i><rsup|2><around|(|x|)>*<big|sum><rsub|i=1><rsup|n>\<mu\><rsub|i>*\<varphi\><rsub|i><rsup|2><around|(|y|)>\<leq\>M<rsup|2>
  </equation>

  From this it follows that the series

  <\equation>
    <big|sum><rsub|i=1><rsup|\<infty\>>\<mu\><rsub|i>*\<phi\><rsub|i><around|(|x|)>*\<phi\><rsub|i><around|(|y|)>
  </equation>

  converges, for every fixed value of <math|x>, uniformly in <math|y>; its
  sum <math|B<around|(|x,y|)>> is therefore a continuous function of
  <math|y>, and for every continuous function <math|f<around|(|y|)>> we have

  <\equation>
    <big|int><rsub|a><rsup|b>B<around|(|x,y|)>*f<around|(|y|)>*d*y=<big|sum><rsub|i=1><rsup|\<infty\>>\<mu\><rsub|i>*\<phi\><rsub|i><around|(|x|)>*<big|int><rsub|a><rsup|b>\<phi\><rsub|i><around|(|y|)>*f<around|(|y|)>*d*y
  </equation>

  Now by one of the theorems proved in the preceding section, the series in
  the second member converges to <math|A<around|(|f|)><around|(|x|)>>. Hence
  we have.

  <\equation>
    <big|int><rsub|a><rsup|b><around|[|B<around|(|x,y|)>-A*<around|(|x,y|)>|]>*f<around|(|y|)>*d*y=0
  </equation>

  setting in particular <math|f<around|(|y|)>=B<around|(|x,y|)>-A*<around|(|x,y|)>>
  (for a fixed value of <math|x>), it follows that
  <math|B<around|(|x,y|)>-A*<around|(|x,y|)>=0> for <math|a\<leq\>y\<leq\>b>,
  hence

  <\equation>
    A*<around|(|x,x|)>=B<around|(|x,x|)>=<big|sum><rsub|i=1><rsup|\<infty\>>\<mu\><rsub|i>*\<phi\><rsub|i><around|(|x|)><rsup|2>
  </equation>

  Since the terms of this series are positive continuous functions of
  <math|x> and its sum <math|A*<around|(|x,x|)>> is a continuous function, it
  follows from a known theorem of Dini that the series converges
  <with|font-shape|italic|uniformly>. Applying Cauchy's inequality (24)
  again, we deduce from this that series (25) converges uniformly with
  respect to <math|x> as well as to <math|y>, and <with|font-shape|italic|a
  fortiori> simultaneously, which was to be proved.

  Whatever be the continuous symmetric kernel <math|A*<around|(|x,y|)>>, its
  iterate

  <\equation>
    A<rsup|<around|(|2|)>>*<around|(|x,y|)>=<big|int><rsub|a><rsup|b>A*<around|(|x,z|)>*A*<around|(|z,y|)>*d*z
  </equation>

  is continuous and of positive type. In fact,

  <\equation>
    <around|(|A<rsup|<around|(|2|)>>*f,f|)>=<around|(|A*f,A*f|)>\<geq\>0
  </equation>

  The characteristic functions <math|\<phi\><rsub|i><around|(|x|)>> of
  <math|A> are also characteristic functions for <math|A<rsup|2>>, but they
  correspond to the squares of the characteristic values
  <math|\<mu\><rsub|i>> of <math|A>:

  <\equation>
    A<rsup|2>*\<phi\><rsub|i>=A*<around|(|A*\<phi\><rsub|i>|)>=A*<around|(|\<mu\><rsub|i>*\<phi\><rsub|i>|)>=\<mu\><rsub|i><rsup|2>*\<phi\><rsub|i>
  </equation>

  The sequence <math|\<mu\><rsub|1><rsup|2>,\<mu\><rsub|2><rsup|2>,\<ldots\>>
  contains all the characteristic values of <math|A<rsup|2>> different from
  0, each as many times as its multiplicity indicates. If not, there would be
  a characteristic function <math|\<phi\>> corresponding to a characteristic
  value <math|\<mu\><rsup|2>\<neq\>0> of <math|A<rsup|2>> and orthogonal to
  all the <math|\<phi\><rsub|i>>. This would be in contradiction to the fact
  that

  <\equation>
    \<mu\>*\<phi\>=A<rsup|2>*\<phi\>=<big|sum><rsub|i=1><rsup|\<infty\>><around|(|A*\<phi\>,\<phi\><rsub|i>|)>*\<phi\><rsub|i>=<big|sum><rsub|i=1><rsup|\<infty\>><around|(|\<phi\>,A*\<phi\><rsub|i>|)>*\<phi\><rsub|i>=<big|sum><rsub|i=1><rsup|\<infty\>>\<mu\><rsub|i>*<around|(|\<phi\>,\<phi\><rsub|i>|)>*\<phi\><rsub|i>=0
  </equation>

  By the theorem of Mercer we therefore have, for the iterate of an arbitrary
  continuous kernel <math|A*<around|(|x,y|)>>, the
  <with|font-shape|italic|uniformly convergent> development:

  <\equation>
    A<rsup|<around|(|2|)>>*<around|(|x,y|)>=<big|sum><rsub|i=1><rsup|\<infty\>>\<mu\><rsub|i><rsup|<around|(|2|)>>*\<phi\><rsub|i><rsup|<around|(|2|)>><around|(|x|)>*\<phi\><rsub|i><rsup|<around|(|2|)>><around|(|y|)>
  </equation>

  <section|Bochner's Theorem and Harmonic Analysis>

  Bochner's theorem complements this by characterizing positive-definite
  functions on locally compact abelian groups. It states that a continuous
  function <math|\<varphi\>> is positive-definite if and only if it is the
  Fourier transform of a finite, non-negative, regular Borel measure. This
  perspective is particularly beneficial for kernels like <math|J<rsub|0>>,
  which are significant in harmonic analysis.

  TODO: reproduce Bochners theorem from one of the authoritative texts

  <\bibliography|bib|tm-plain|refs>
    <\bib-list|1>
      <bibitem*|1><label|bib-RieszNagyFA>Frigyes Riesz<localize| and >Béla
      Sz®kefalvi-Nagy. <newblock><with|font-shape|italic|Functional
      Analysis>. <newblock>F. Ungar Pub. Co., New York, 1955.<newblock>
    </bib-list>
  </bibliography>
</body>

<\initial>
  <\collection>
    <associate|magnification|1.2>
    <associate|page-height|auto>
    <associate|page-medium|paper>
    <associate|page-type|letter>
    <associate|page-width|auto>
  </collection>
</initial>

<\references>
  <\collection>
    <associate|auto-1|<tuple|1|1|../../.TeXmacs/texts/scratch/no_name_15.tm>>
    <associate|auto-2|<tuple|2|1|../../.TeXmacs/texts/scratch/no_name_15.tm>>
    <associate|auto-3|<tuple|3|3|../../.TeXmacs/texts/scratch/no_name_15.tm>>
    <associate|auto-4|<tuple|3|4|../../.TeXmacs/texts/scratch/no_name_15.tm>>
    <associate|bib-RieszNagyFA|<tuple|1|4|../../.TeXmacs/texts/scratch/no_name_15.tm>>
    <associate|doubleint|<tuple|4|2|../../.TeXmacs/texts/scratch/no_name_15.tm>>
  </collection>
</references>

<\auxiliary>
  <\collection>
    <\associate|bib>
      RieszNagyFA
    </associate>
    <\associate|toc>
      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|1<space|2spc>Introduction>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-1><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|2<space|2spc>Mercer's
      Theorem> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-2><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|3<space|2spc>Bochner's
      Theorem and Harmonic Analysis> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-3><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|Bibliography>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-4><vspace|0.5fn>
    </associate>
  </collection>
</auxiliary>