<TeXmacs|2.1.4>

<style|<tuple|generic|framed-theorems>>

<\body>
  <doc-data|<doc-title|Oscillatory Processes Generated by Unitary Bijective
  Time Changes<next-line>of Stationary Gaussian
  Processes>|<doc-author|<author-data|<author-name|Stephen
  Crowley>|<author-email|stephencrowley214@gmail.com>>>|<doc-date|August 1,
  2025>>

  <abstract-data|<\abstract>
    This article establishes that Gaussian processes obtained via unitary,
    measure-preserving bijective time transformations of stationary processes
    are a subclass of oscillatory processes in the sense of Priestley. The
    central object is the unitary composition operator
    <math|M<rsub|\<theta\>>> (and its inverse), which implements the time
    change at the Hilbert-space level and conjugates covariance and spectral
    structures. Comprehensive theorems and proofs are provided for all main
    statements, including the oscillatory spectral representation,
    <math|L<rsup|2>>-isometry, evolutionary spectrum, and expected zero
    formula.
  </abstract>>

  <\table-of-contents|toc>
    <vspace*|1fn><with|font-series|bold|math-font-series|bold|1<space|2spc>Scaling
    Functions and Oscillatory Processes> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-1><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|2<space|2spc>Unitary
    Time-Change Operator and its Inverse>
    <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-2><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|3<space|2spc>Oscillatory
    Representation of Unitary Time-Changed Stationary Processes>
    <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-3><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|4<space|2spc><with|mode|math|L<rsup|2>>-Norm
    Preservation by Unitary Time-Change> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-4><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|5<space|2spc>Expected
    Zero Formula> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-5><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|6<space|2spc>Conclusion>
    <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-6><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|Bibliography>
    <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-7><vspace|0.5fn>
  </table-of-contents>

  <section|Scaling Functions and Oscillatory Processes>

  <\definition>
    [Scaling Functions]<label|def:scaling> Let <math|\<cal-F\>> denote the
    set of functions <math|\<theta\>:\<bbb-R\>\<to\>\<bbb-R\>> such that:

    <\enumerate>
      <item><math|\<theta\>> is continuously differentiable and
      <math|\<theta\><rprime|'><around|(|t|)>\<gtr\>0> for all <math|t>

      <item><math|\<theta\>> is strictly increasing and bijective
    </enumerate>
  </definition>

  <\remark>
    From the inverse function theorem, any <math|\<theta\>\<in\>\<cal-F\>>
    has an everywhere differentiable inverse with
    <math|<around|(|\<theta\><rsup|-1>|)><rprime|'><around|(|s|)>=1/\<theta\><rprime|'><around|(|\<theta\><rsup|-1><around|(|s|)>|)>>
    for all <math|s> in the range of <math|\<theta\>>.
  </remark>

  <\definition>
    [Oscillatory Process]<label|def:oscillatory> A complex-valued,
    second-order stochastic process <math|<around|{|X<rsub|t>|}><rsub|t\<in\>\<bbb-R\>>>
    is called <em|oscillatory> if there exists

    <\enumerate>
      <item>a family of functions <math|<around|{|\<phi\><rsub|t><around|(|\<omega\>|)>|}>>
      with <math|\<phi\><rsub|t><around|(|\<omega\>|)>=A<rsub|t><around|(|\<omega\>|)>*e<rsup|i*\<omega\>*t>>
      where <math|A<rsub|t><around|(|\<cdummy\>|)>\<in\>L<rsup|2><around|(|\<mu\>|)>>

      <item>a complex orthogonal-increment process
      <math|Z<around|(|\<omega\>|)>> with
      <math|E*<around|\||d*Z<around|(|\<omega\>|)>|\|><rsup|2>=d*\<mu\><around|(|\<omega\>|)>>
    </enumerate>

    such that

    <\equation>
      <label|eq:oscrep>X<rsub|t>=<big|int><rsub|-\<infty\>><rsup|\<infty\>>\<phi\><rsub|t><around|(|\<omega\>|)>*<space|0.17em>d*Z<around|(|\<omega\>|)>
    </equation>
  </definition>

  <section|Unitary Time-Change Operator and its Inverse>

  <\definition>
    [Unitary Time-Change Operator]<label|def:unitary> Let
    <math|\<theta\>\<in\>\<cal-F\>>. Define the operator
    <math|M<rsub|\<theta\>>:L<rsup|2><around|(|\<bbb-R\>|)>\<to\>L<rsup|2><around|(|\<bbb-R\>|)>>
    by

    <\equation>
      <label|eq:unitaryM><around|(|M<rsub|\<theta\>>*f|)><around|(|t|)>\<assign\><sqrt|\<theta\><rprime|'><around|(|t|)>>*<space|0.17em>f<around|(|\<theta\><around|(|t|)>|)>
    </equation>
  </definition>

  <\lemma>
    [Unitarity of <math|M<rsub|\<theta\>>>]<label|lem:unitary> The operator
    <math|M<rsub|\<theta\>>> is unitary; that is, for all
    <math|f\<in\>L<rsup|2><around|(|\<bbb-R\>|)>>,

    <\equation>
      <label|eq:unitnorm><big|int><rsub|-\<infty\>><rsup|\<infty\>><around|\||<around|(|M<rsub|\<theta\>>*f|)><around|(|t|)>*<around|\||<rsup|2><space|0.17em>d*t=<big|int><rsub|-\<infty\>><rsup|\<infty\>>|\|>*f<around|(|s|)>|\|><rsup|2>*d*s
    </equation>
  </lemma>

  <\proof>
    Substitute <math|s=\<theta\><around|(|t|)>>, and
    <math|d*s=\<theta\><rprime|'><around|(|t|)>*d*t>, then:

    <\align*>
      <tformat|<table|<row|<cell|<big|int><rsub|\<bbb-R\>><around|\||<around|(|M<rsub|\<theta\>>*f|)><around|(|t|)>|\|><rsup|2>*d*t>|<cell|=<big|int><rsub|\<bbb-R\>><around|\||<sqrt|\<theta\><rprime|'><around|(|t|)>>*f<around|(|\<theta\><around|(|t|)>|)>|\|><rsup|2>*d*t>>|<row|<cell|>|<cell|=<big|int><rsub|\<bbb-R\>>\<theta\><rprime|'><around|(|t|)><around|\||f<around|(|\<theta\><around|(|t|)>|)>|\|><rsup|2>*d*t>>|<row|<cell|>|<cell|=<big|int><rsub|\<bbb-R\>><around|\||f<around|(|s|)>|\|><rsup|2>*d*s>>>>
    </align*>

    Because <math|\<theta\>> is bijective and smooth, this covers all of
    <math|\<bbb-R\>>.
  </proof>

  <\definition>
    [Inverse Operator]<label|def:Mtheta_inv> The inverse of
    <math|M<rsub|\<theta\>>> is given by

    <\equation>
      <label|eq:unitaryM_inverse><around|(|M<rsub|\<theta\>><rsup|-1>*g|)><around|(|s|)>\<assign\><frac|g<around|(|\<theta\><rsup|-1><around|(|s|)>|)>|<sqrt|\<theta\><rprime|'><around|(|\<theta\><rsup|-1><around|(|s|)>|)>>>
    </equation>
  </definition>

  <\lemma>
    [Verification of Inverse]<label|lem:invert> For any
    <math|f\<in\>L<rsup|2><around|(|\<bbb-R\>|)>>,
    <math|M<rsub|\<theta\>><rsup|-1>*M<rsub|\<theta\>>*f=f> and
    <math|M<rsub|\<theta\>>*M<rsub|\<theta\>><rsup|-1>*g=g> for all
    <math|g\<in\>L<rsup|2><around|(|\<bbb-R\>|)>>.
  </lemma>

  <\proof>
    <no-indent>For <math|f>:

    <\equation*>
      <around|(|M<rsub|\<theta\>><rsup|-1>*M<rsub|\<theta\>>*f|)><around|(|s|)>=<frac|M<rsub|\<theta\>>*f<around|(|\<theta\><rsup|-1><around|(|s|)>|)>|<sqrt|\<theta\><rprime|'><around|(|\<theta\><rsup|-1><around|(|s|)>|)>>>=<frac|<sqrt|\<theta\><rprime|'><around|(|\<theta\><rsup|-1><around|(|s|)>|)>>*f<around|(|\<theta\><around|(|\<theta\><rsup|-1><around|(|s|)>|)>|)>|<sqrt|\<theta\><rprime|'><around|(|\<theta\><rsup|-1><around|(|s|)>|)>>>=f<around|(|s|)>
    </equation*>

    For <math|g>:

    <\equation*>
      <around|(|M<rsub|\<theta\>>*M<rsub|\<theta\>><rsup|-1>*g|)><around|(|t|)>=<sqrt|\<theta\><rprime|'><around|(|t|)>>\<cdot\><frac|g<around|(|\<theta\><around|(|\<theta\><rsup|-1><around|(|\<theta\><around|(|t|)>|)>|)>|)>|<sqrt|\<theta\><rprime|'><around|(|\<theta\><rsup|-1><around|(|\<theta\><around|(|t|)>|)>|)>>>=g<around|(|\<theta\><around|(|t|)>|\<nobracket\>>
    </equation*>

    But under the substitution <math|s=\<theta\><around|(|t|)>>, so
    <math|g<around|(|\<theta\><around|(|t|)>|)>> traverses all of
    <math|L<rsup|2>> as <math|t> traverses <math|\<bbb-R\>>, confirming
    mutual inverseness.
  </proof>

  <section|Oscillatory Representation of Unitary Time-Changed Stationary
  Processes>

  Let <math|<around|{|S<rsub|t>|}>> be a stationary Gaussian process with
  continuous spectral representation

  <\equation>
    <label|eq:stat_spectral>S<rsub|t>=<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*\<omega\>*t>*<space|0.17em>d*Z<around|(|\<omega\>|)>
  </equation>

  For <math|\<theta\>\<in\>\<cal-F\>>, define the transformed process

  <\equation>
    <label|eq:osc_process>X<rsub|t>\<assign\><sqrt|\<theta\><rprime|'><around|(|t|)>>*<space|0.17em>S<rsub|\<theta\><around|(|t|)>>
  </equation>

  <\theorem>
    [Oscillatory Spectral Representation]<label|thm:spectral> The process
    defined by <eqref|eq:osc_process> has the oscillatory representation

    <\equation>
      <label|eq:oscillatoryrep>X<rsub|t>=<big|int><rsub|-\<infty\>><rsup|\<infty\>><sqrt|\<theta\><rprime|'><around|(|t|)>>*e<rsup|i*\<omega\>*\<theta\><around|(|t|)>>*d*Z<around|(|\<omega\>|)>
    </equation>

    i.e., with <math|\<phi\><rsub|t><around|(|\<omega\>|)>=<sqrt|\<theta\><rprime|'><around|(|t|)>>*e<rsup|i*\<omega\>*\<theta\><around|(|t|)>>>.
    Moreover, <math|\<phi\><rsub|t><around|(|\<omega\>|)>> can be written in
    the standard form:

    <\equation>
      \<phi\><rsub|t><around|(|\<omega\>|)>=A<rsub|t><around|(|\<omega\>|)>*e<rsup|i*\<omega\>*t>,<space|2em>A<rsub|t><around|(|\<omega\>|)>=<sqrt|\<theta\><rprime|'><around|(|t|)>>*e<rsup|i*\<omega\>*<around|(|\<theta\><around|(|t|)>-t|)>>
    </equation>
  </theorem>

  <\proof>
    Substituting <eqref|eq:stat_spectral> into <eqref|eq:osc_process>:

    <\align*>
      <tformat|<table|<row|<cell|X<rsub|t>>|<cell|=<sqrt|\<theta\><rprime|'><around|(|t|)>>*S<rsub|\<theta\><around|(|t|)>>=<sqrt|\<theta\><rprime|'><around|(|t|)>>*<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*\<omega\>*\<theta\><around|(|t|)>>*d*Z<around|(|\<omega\>|)>=<big|int><rsub|-\<infty\>><rsup|\<infty\>><sqrt|\<theta\><rprime|'><around|(|t|)>>*e<rsup|i*\<omega\>*\<theta\><around|(|t|)>>*d*Z<around|(|\<omega\>|)>.>>>>
    </align*>

    To write in oscillatory standard form:

    <\equation>
      <sqrt|\<theta\><rprime|'><around|(|t|)>>*e<rsup|i*\<omega\>*\<theta\><around|(|t|)>>=<sqrt|\<theta\><rprime|'><around|(|t|)>>*e<rsup|i*\<omega\>*<around|(|\<theta\><around|(|t|)>-t|)>>*<space|0.17em>e<rsup|i*\<omega\>*t>=A<rsub|t><around|(|\<omega\>|)>*e<rsup|i*\<omega\>*t>
    </equation>

    The square-integrability in <math|\<omega\>> follows because
    <math|\<mu\>> is finite and <math|\<theta\><rprime|'>> is everywhere
    positive and finite.
  </proof>

  <\theorem>
    [Evolutionary Spectrum]<label|thm:evolve> For the above process, the
    evolutionary power spectrum at time <math|t> is

    <\equation>
      d*F<rsub|t><around|(|\<omega\>|)>=<around|\||A<rsub|t><around|(|\<omega\>|)>|\|><rsup|2>*d*\<mu\><around|(|\<omega\>|)>=\<theta\><rprime|'><around|(|t|)>*d*\<mu\><around|(|\<omega\>|)>
    </equation>
  </theorem>

  <\proof>
    By definition, <math|d*F<rsub|t><around|(|\<omega\>|)>=<around|\||A<rsub|t><around|(|\<omega\>|)>|\|><rsup|2>*d*\<mu\><around|(|\<omega\>|)>>.
    Since

    <\equation*>
      <around|\||A<rsub|t><around|(|\<omega\>|)>|\|><rsup|2>=<around|\||<sqrt|\<theta\><rprime|'><around|(|t|)>>|\|><rsup|2>\<cdot\><around|\||e<rsup|i*\<omega\>*<around|(|\<theta\><around|(|t|)>-t|)>>|\|><rsup|2>=\<theta\><rprime|'><around|(|t|)>
    </equation*>

    the result follows.
  </proof>

  <section|<math|L<rsup|2>>-Norm Preservation by Unitary Time-Change>

  <\theorem>
    [<math|L<rsup|2>>-Norm Preservation]<label|thm:L2> The unitary
    time-change preserves the <math|L<rsup|2>>-norms of the stochastic
    processes: for any measurable <math|I\<subseteq\>\<bbb-R\>>,

    <\equation>
      <big|int><rsub|I>\<bbb-E\><around*|[|<around|\||X<rsub|t>|\|><rsup|2>|]>*d*t=<big|int><rsub|\<theta\><around|(|I|)>>\<bbb-E\><around*|[|<around|\||S<rsub|s>|\|><rsup|2>|]>*d*s
    </equation>
  </theorem>

  <\proof>
    Using <math|X<rsub|t>=<sqrt|\<theta\><rprime|'><around|(|t|)>>*S<rsub|\<theta\><around|(|t|)>>>
    and stationarity of <math|S>:

    <\align*>
      <tformat|<table|<row|<cell|\<bbb-E\><around|[|<around|\||X<rsub|t>|\|><rsup|2>|]>>|<cell|=\<theta\><rprime|'><around|(|t|)>*<space|0.17em>\<bbb-E\><around|[|<around|\||S<rsub|\<theta\><around|(|t|)>>|\|><rsup|2>|]>>>|<row|<cell|>|<cell|=\<theta\><rprime|'><around|(|t|)>*<space|0.17em>\<bbb-E\><around|[|<around|\||S<rsub|0>|\|><rsup|2>|]>>>|<row|<cell|>|<cell|=\<theta\><rprime|'><around|(|t|)>*<space|0.17em>\<sigma\><rsup|2><space|1em><text|(where
      <math|\<sigma\><rsup|2>> is constant)>>>>>
    </align*>

    Thus,

    <\align*>
      <tformat|<table|<row|<cell|<big|int><rsub|I>\<bbb-E\><around|[|<around|\||X<rsub|t>|\|><rsup|2>|]>*d*t=\<sigma\><rsup|2>*<big|int><rsub|I>\<theta\><rprime|'><around|(|t|)>*d*t=\<sigma\><rsup|2>*<big|int><rsub|\<theta\><around|(|I|)>>d*s=<big|int><rsub|\<theta\><around|(|I|)>>\<bbb-E\><around|[|<around|\||S<rsub|s>|\|><rsup|2>|]>*d*s>>>>
    </align*>
  </proof>

  <section|The Kac-Rice Formula for Zero Counting>

  <\theorem>
    <dueto|Kac-Rice Formula><label|thm:kac_rice>Let <math|Z<around|(|t|)>> be
    a real-valued stochastic process on <math|\<bbb-R\>> with continuous
    sample paths that are almost surely <math|C<rsup|1>>. Assume that for
    each <math|t>, the random vector <math|<around|(|Z<around|(|t|)>,Z<rprime|'><around|(|t|)>|)>>
    has a jointly continuous probability density function
    <math|p<rsub|Z,Z<rprime|'>><around|(|z,v,t|)>>. Then the expected number
    of zeros of <math|Z> in an interval <math|<around|[|a,b|]>> is given by:

    <\equation>
      <tabular*|<tformat|<cwith|1|-1|1|1|cell-halign|l>|<cwith|1|-1|1|1|cell-lborder|0ln>|<cwith|1|-1|2|2|cell-halign|l>|<cwith|1|-1|2|2|cell-rborder|0ln>|<table|<row|<cell|\<bbb-E\><around|[|N<rsub|<around|[|a,b|]>>|]>>|<cell|=<big|int><rsub|a><rsup|b>\<bbb-E\>*<around|[|<around|\||Z<rprime|'><around|(|t|)>|\|>\<mid\>Z<around|(|t|)>=0|]>*p<rsub|Z><around|(|0,t|)>*d*t>>|<row|<cell|>|<cell|=<big|int><rsub|a><rsup|b><big|int><rsub|-\<infty\>><rsup|\<infty\>><around|\||v|\|>*p<rsub|Z,Z<rprime|'>><around|(|0,v,t|)>*d*v*d*t>>>>>
    </equation>

    where <math|p<rsub|Z><around|(|z,t|)>> is the marginal density of
    <math|Z<around|(|t|)>> and <math|N<rsub|<around|[|a,b|]>>> denotes the
    number of zeros in <math|<around|[|a,b|]>>.
  </theorem>

  <\proof>
    The proof uses the co-area formula from geometric measure theory.
    Consider the zero set <math|\<cal-Z\>=<around|{|t\<in\><around|[|a,b|]>:Z<around|(|t,\<omega\>|)>=0|}>>
    for a fixed sample path <math|\<omega\>>. Under the regularity
    conditions, <math|\<cal-Z\>> is a discrete set of points
    <math|<around|{|t<rsub|i>|}>> where <math|Z<around|(|t<rsub|i>|)>=0> and
    <math|Z<rprime|'><around|(|t<rsub|i>|)>\<neq\>0> almost surely.

    The counting measure on zeros can be expressed using the Dirac delta:

    <\equation>
      N<rsub|<around|[|a,b|]>>=<big|int><rsub|a><rsup|b>\<delta\><around|(|Z<around|(|t|)>|)><around|\||Z<rprime|'><around|(|t|)>|\|>*d*t
    </equation>

    Taking expectations and applying Fubini's theorem (justified by the
    regularity assumptions):

    <\equation>
      \<bbb-E\><around|[|N<rsub|<around|[|a,b|]>>|]>=<big|int><rsub|a><rsup|b>\<bbb-E\><around|[|\<delta\><around|(|Z<around|(|t|)>|)><around|\||Z<rprime|'><around|(|t|)>|\|>|]>*d*t
    </equation>

    Using the joint density of <math|<around|(|Z<around|(|t|)>,Z<rprime|'><around|(|t|)>|)>>:

    <\equation>
      \<bbb-E\><around|[|\<delta\><around|(|Z<around|(|t|)>|)><around|\||Z<rprime|'><around|(|t|)>|\|>|]>=<big|int><rsub|-\<infty\>><rsup|\<infty\>><big|int><rsub|-\<infty\>><rsup|\<infty\>>\<delta\><around|(|z|)><around|\||v|\|>*p<rsub|Z,Z<rprime|'>><around|(|z,v,t|)>*d*z*d*v
    </equation>

    Evaluating the delta function:

    <\equation>
      =<big|int><rsub|-\<infty\>><rsup|\<infty\>><around|\||v|\|>*p<rsub|Z,Z<rprime|'>><around|(|0,v,t|)>*d*v
    </equation>

    The first form follows by noting that:

    <\equation>
      <big|int><rsub|-\<infty\>><rsup|\<infty\>><around|\||v|\|>*p<rsub|Z,Z<rprime|'>><around|(|0,v,t|)>*d*v=\<bbb-E\>*<around|[|<around|\||Z<rprime|'><around|(|t|)>|\|>\<mid\>Z<around|(|t|)>=0|]>\<cdot\>p<rsub|Z><around|(|0,t|)>
    </equation>
  </proof>

  <section|The Kac-Rice Formula for Zero Counting>

  <\theorem>
    <dueto|Kac-Rice Formula><label|thm:kac_rice>Let <math|Z<around|(|t|)>> be
    a real-valued stochastic process on <math|\<bbb-R\>> with continuous
    sample paths that are almost surely <math|C<rsup|1>>. Assume that for
    each <math|t>, the random vector <math|<around|(|Z<around|(|t|)>,Z<rprime|'><around|(|t|)>|)>>
    has a jointly continuous probability density function
    <math|p<rsub|Z,Z<rprime|'>><around|(|z,v,t|)>>. Then the expected number
    of zeros of <math|Z> in an interval <math|<around|[|a,b|]>> is given by:

    <\equation>
      <tabular*|<tformat|<cwith|1|-1|1|1|cell-halign|l>|<cwith|1|-1|1|1|cell-lborder|0ln>|<cwith|1|-1|2|2|cell-halign|l>|<cwith|1|-1|2|2|cell-rborder|0ln>|<table|<row|<cell|\<bbb-E\><around|[|N<rsub|<around|[|a,b|]>>|]>>|<cell|=<big|int><rsub|a><rsup|b>\<bbb-E\>*<around|[|<around|\||Z<rprime|'><around|(|t|)>|\|>\<mid\>Z<around|(|t|)>=0|]>*p<rsub|Z><around|(|0,t|)>*d*t>>|<row|<cell|>|<cell|=<big|int><rsub|a><rsup|b><big|int><rsub|-\<infty\>><rsup|\<infty\>><around|\||v|\|>*p<rsub|Z,Z<rprime|'>><around|(|0,v,t|)>*d*v*d*t>>>>>
    </equation>

    where <math|p<rsub|Z><around|(|z,t|)>> is the marginal density of
    <math|Z<around|(|t|)>> and <math|N<rsub|<around|[|a,b|]>>> denotes the
    number of zeros in <math|<around|[|a,b|]>>.
  </theorem>

  <\proof>
    The proof uses the co-area formula from geometric measure theory.
    Consider the zero set <math|\<cal-Z\>=<around|{|t\<in\><around|[|a,b|]>:Z<around|(|t,\<omega\>|)>=0|}>>
    for a fixed sample path <math|\<omega\>>. Under the regularity
    conditions, <math|\<cal-Z\>> is a discrete set of points
    <math|<around|{|t<rsub|i>|}>> where <math|Z<around|(|t<rsub|i>|)>=0> and
    <math|Z<rprime|'><around|(|t<rsub|i>|)>\<neq\>0> almost surely.

    The counting measure on zeros can be expressed using the Dirac delta:

    <\equation>
      N<rsub|<around|[|a,b|]>>=<big|int><rsub|a><rsup|b>\<delta\><around|(|Z<around|(|t|)>|)><around|\||Z<rprime|'><around|(|t|)>|\|>*d*t
    </equation>

    Taking expectations and applying Fubini's theorem (justified by the
    regularity assumptions):

    <\equation>
      \<bbb-E\><around|[|N<rsub|<around|[|a,b|]>>|]>=<big|int><rsub|a><rsup|b>\<bbb-E\><around|[|\<delta\><around|(|Z<around|(|t|)>|)><around|\||Z<rprime|'><around|(|t|)>|\|>|]>*d*t
    </equation>

    Using the joint density of <math|<around|(|Z<around|(|t|)>,Z<rprime|'><around|(|t|)>|)>>:

    <\equation>
      \<bbb-E\><around|[|\<delta\><around|(|Z<around|(|t|)>|)><around|\||Z<rprime|'><around|(|t|)>|\|>|]>=<big|int><rsub|-\<infty\>><rsup|\<infty\>><big|int><rsub|-\<infty\>><rsup|\<infty\>>\<delta\><around|(|z|)><around|\||v|\|>*p<rsub|Z,Z<rprime|'>><around|(|z,v,t|)>*d*z*d*v
    </equation>

    Evaluating the delta function:

    <\equation>
      =<big|int><rsub|-\<infty\>><rsup|\<infty\>><around|\||v|\|>*p<rsub|Z,Z<rprime|'>><around|(|0,v,t|)>*d*v
    </equation>

    The first form follows by noting that:

    <\equation>
      <big|int><rsub|-\<infty\>><rsup|\<infty\>><around|\||v|\|>*p<rsub|Z,Z<rprime|'>><around|(|0,v,t|)>*d*v=\<bbb-E\>*<around|[|<around|\||Z<rprime|'><around|(|t|)>|\|>\<mid\>Z<around|(|t|)>=0|]>\<cdot\>p<rsub|Z><around|(|0,t|)>
    </equation>
  </proof>

  <\theorem>
    <dueto|Expected Zero Count for Oscillatory
    Processes><label|thm:zerocount>Let <math|K<around|(|\<tau\>|)>> be the
    covariance function of <math|S<rsub|t>> (assumed twice differentiable at
    <math|0>), and <math|\<theta\>\<in\>\<cal-F\>>. For the oscillatory
    process <math|X<rsub|t>=<sqrt|\<theta\><rprime|'><around|(|t|)>>*S<rsub|\<theta\><around|(|t|)>>>,
    the expected number of real zeros on <math|<around|[|a,b|]>> is

    <\equation>
      \<bbb-E\><around|[|N<rsub|<around|[|a,b|]>>|]>=<sqrt|-<wide|K|\<ddot\>><around|(|0|)>>*<around|(|\<theta\><around|(|b|)>-\<theta\><around|(|a|)>|)>
    </equation>
  </theorem>

  <\proof>
    By the Kac-Rice formula:

    <\equation>
      \<bbb-E\><around|[|N<rsub|<around|[|a,b|]>>|]>=<big|int><rsub|a><rsup|b><sqrt|-lim<rsub|s\<to\>t>
      <frac|\<partial\><rsup|2>|\<partial\>*s*\<partial\>*t><math-up|cov><around|(|X<rsub|s>,X<rsub|t>|)>>*d*t
    </equation>

    For <math|X<rsub|t>=<sqrt|\<theta\><rprime|'><around|(|t|)>>*S<rsub|\<theta\><around|(|t|)>>>,
    we have

    <\equation*>
      <math-up|cov><around|(|X<rsub|s>,X<rsub|t>|)>=<sqrt|\<theta\><rprime|'><around|(|s|)>*\<theta\><rprime|'><around|(|t|)>>*K*<around|(|\<theta\><around|(|t|)>-\<theta\><around|(|s|)>|)>
    </equation*>

    Computing the mixed partial derivative:

    <\align>
      <tformat|<table|<row|<cell|<frac|\<partial\>|\<partial\>*s><math-up|cov><around|(|X<rsub|s>,X<rsub|t>|)>>|<cell|=<frac|\<partial\>|\<partial\>*s>*<around*|[|<sqrt|\<theta\><rprime|'><around|(|s|)>*\<theta\><rprime|'><around|(|t|)>>*K*<around|(|\<theta\><around|(|t|)>-\<theta\><around|(|s|)>|)>|]><eq-number>>>|<row|<cell|>|<cell|=<frac|\<theta\><rprime|''><around|(|s|)>|2*<sqrt|\<theta\><rprime|'><around|(|s|)>*\<theta\><rprime|'><around|(|t|)>>>*K*<around|(|\<theta\><around|(|t|)>-\<theta\><around|(|s|)>|)>+<sqrt|\<theta\><rprime|'><around|(|s|)>*\<theta\><rprime|'><around|(|t|)>>*K<rprime|'>*<around|(|\<theta\><around|(|t|)>-\<theta\><around|(|s|)>|)>\<cdot\><around|(|-\<theta\><rprime|'><around|(|s|)>|)><eq-number>>>|<row|<cell|>|<cell|=<frac|\<theta\><rprime|''><around|(|s|)>|2*<sqrt|\<theta\><rprime|'><around|(|s|)>*\<theta\><rprime|'><around|(|t|)>>>*K*<around|(|\<theta\><around|(|t|)>-\<theta\><around|(|s|)>|)>-\<theta\><rprime|'><around|(|s|)><sqrt|\<theta\><rprime|'><around|(|s|)>*\<theta\><rprime|'><around|(|t|)>>*K<rprime|'>*<around|(|\<theta\><around|(|t|)>-\<theta\><around|(|s|)>|)><eq-number>>>>>
    </align>

    Taking the derivative with respect to <math|t>:

    <\align>
      <tformat|<table|<row|<cell|<frac|\<partial\><rsup|2>|\<partial\>*s*\<partial\>*t><math-up|cov><around|(|X<rsub|s>,X<rsub|t>|)>>|<cell|=<frac|\<partial\>|\<partial\>*t>*<around*|[|<frac|\<theta\><rprime|''><around|(|s|)>|2*<sqrt|\<theta\><rprime|'><around|(|s|)>*\<theta\><rprime|'><around|(|t|)>>>*K*<around|(|\<theta\><around|(|t|)>-\<theta\><around|(|s|)>|)>-\<theta\><rprime|'><around|(|s|)><sqrt|\<theta\><rprime|'><around|(|s|)>*\<theta\><rprime|'><around|(|t|)>>*K<rprime|'>*<around|(|\<theta\><around|(|t|)>-\<theta\><around|(|s|)>|)>|]><eq-number>>>|<row|<cell|>|<cell|=<frac|\<theta\><rprime|''><around|(|s|)>|2*<sqrt|\<theta\><rprime|'><around|(|s|)>>>*<around*|[|-<frac|\<theta\><rprime|''><around|(|t|)>|2<around|(|\<theta\><rprime|'><around|(|t|)>|)><rsup|3/2>>*K*<around|(|\<theta\><around|(|t|)>-\<theta\><around|(|s|)>|)>+<frac|\<theta\><rprime|'><around|(|t|)>|<sqrt|\<theta\><rprime|'><around|(|t|)>>>*K<rprime|'>*<around|(|\<theta\><around|(|t|)>-\<theta\><around|(|s|)>|)>|]><eq-number>>>|<row|<cell|>|<cell|<space|1em>-\<theta\><rprime|'><around|(|s|)>*<around*|[|<frac|\<theta\><rprime|''><around|(|t|)>|2*<sqrt|\<theta\><rprime|'><around|(|s|)>*\<theta\><rprime|'><around|(|t|)>>>*K<rprime|'>*<around|(|\<theta\><around|(|t|)>-\<theta\><around|(|s|)>|)>+<sqrt|\<theta\><rprime|'><around|(|s|)>*\<theta\><rprime|'><around|(|t|)>>*K<rprime|''>*<around|(|\<theta\><around|(|t|)>-\<theta\><around|(|s|)>|)>\<cdot\>\<theta\><rprime|'><around|(|t|)>|]><eq-number>>>>>
    </align>

    Taking the limit as <math|s\<to\>t>:

    <\equation>
      <tabular|<tformat|<table|<row|<cell|lim<rsub|s\<to\>t>
      <frac|\<partial\><rsup|2>|\<partial\>*s*\<partial\>*t><math-up|cov><around|(|X<rsub|s>,X<rsub|t>|)>>|<cell|=<frac|\<theta\><rprime|''><around|(|t|)>|2*\<theta\><rprime|'><around|(|t|)>>*K<around|(|0|)>+\<theta\><rprime|'><around|(|t|)>*K<rprime|'><around|(|0|)>-<frac|\<theta\><rprime|''><around|(|t|)>|2*\<theta\><rprime|'><around|(|t|)>>*K<rprime|'><around|(|0|)>-\<theta\><rprime|'><around|(|t|)><rsup|2>*K<rprime|''><around|(|0|)>>>|<row|<cell|>|<cell|=<frac|\<theta\><rprime|''><around|(|t|)>|2*\<theta\><rprime|'><around|(|t|)>>\<cdot\>0+\<theta\><rprime|'><around|(|t|)>\<cdot\>0-<frac|\<theta\><rprime|''><around|(|t|)>|2*\<theta\><rprime|'><around|(|t|)>>\<cdot\>0-\<theta\><rprime|'><around|(|t|)><rsup|2>*K<rprime|''><around|(|0|)>>>|<row|<cell|>|<cell|=-\<theta\><rprime|'><around|(|t|)><rsup|2>*K<rprime|''><around|(|0|)>>>>>>
    </equation>

    where we used <math|K<around|(|0|)>=\<sigma\><rsup|2>> and
    <math|K<rprime|'><around|(|0|)>=0> by stationarity. Therefore:

    <\equation>
      <tabular|<tformat|<table|<row|<cell|\<bbb-E\><around|[|N<rsub|<around|[|a,b|]>>|]>>|<cell|=<big|int><rsub|a><rsup|b><sqrt|-<around|(|-\<theta\><rprime|'><around|(|t|)><rsup|2>*K<rprime|''><around|(|0|)>|)>>*d*t>>|<row|<cell|>|<cell|=<big|int><rsub|a><rsup|b><sqrt|\<theta\><rprime|'><around|(|t|)><rsup|2>*<around|(|-K<rprime|''><around|(|0|)>|)>>*d*t>>|<row|<cell|>|<cell|=<big|int><rsub|a><rsup|b>\<theta\><rprime|'><around|(|t|)><sqrt|-K<rprime|''><around|(|0|)>>*d*t>>|<row|<cell|>|<cell|=<sqrt|-K<rprime|''><around|(|0|)>>*<big|int><rsub|a><rsup|b>\<theta\><rprime|'><around|(|t|)>*d*t>>|<row|<cell|>|<cell|=<sqrt|-K<rprime|''><around|(|0|)>>*<around|(|\<theta\><around|(|b|)>-\<theta\><around|(|a|)>|)>>>>>>
    </equation>

    \;
  </proof>

  <\remark>
    <dueto|Connection to Zero Localization Measure>Theorem
    <reference|thm:zerocount> demonstrates that the time-change function
    <math|\<theta\>> directly controls the expected zero density of the
    oscillatory process generated by the unitary operator
    <math|U<rsub|\<theta\>>>. The expected zero density per unit length in
    the original time scale is <math|<sqrt|-<wide|K|\<ddot\>><around|(|0|)>>*\<theta\><rprime|'><around|(|t|)>>,
    which varies with time according to the derivative of the time-change
    function. While the Kac-Rice formula computes ensemble averages over all
    realizations, the zero localization measure
    <math|\<mu\>*<around|(|d*t|)>=\<delta\><around|(|X<around|(|t|)>|)><around|\||X<rprime|'><around|(|t|)>|\|>*d*t>
    and the spectrum <math|\<sigma\><around|(|L|)>=<around|{|t<rsub|0>:X<around|(|t<rsub|0>|)>=0|}>>
    of the multiplication operator are defined for a single fixed
    realization. The Kac-Rice result thus provides the expected structure of
    the spectrum when averaging over the probability space, with
    <math|\<theta\>> serving as a control parameter for the expected spectral
    density.
  </remark>

  <section|Conclusion>

  The class of processes <math|X<rsub|t>\<assign\><sqrt|\<theta\><rprime|'><around|(|t|)>>*S<rsub|\<theta\><around|(|t|)>>>
  forms a subclass of oscillatory processes corresponding to
  measure-preserving, unitary time changes of stationary Gaussian processes.
  The unitary composition operator <math|M<rsub|\<theta\>>> implements this
  transformation at the Hilbert space level, preserving all <math|L<rsup|2>>
  inner products and yields oscillatory spectral representations with
  evolving spectra. The zero set and energy properties of the process are
  determined by the geometry of <math|\<theta\>> and the spectrum of the
  underlying stationary process, as proved above.

  <\thebibliography|99>
    <bibitem|priestley1965>M.B. Priestley, <em|Evolutionary spectra and
    non-stationary processes>. J. Roy. Statist. Soc. Ser. B 27 (1965),
    204\U237.

    <bibitem|cramer1967>H. Cramér and M.R. Leadbetter, <em|Stationary and
    Related Stochastic Processes>. Wiley, 1967.

    <bibitem|kac1943>M. Kac. On the average number of real roots of a random
    algebraic equation. <em|Bulletin of the American Mathematical Society>,
    49(4):314\U320, 1943.

    <bibitem|rice1945>S. O. Rice, Mathematical analysis of random noise.
    <em|Bell Syst. Tech. J.>, 24 (1945), 46\U156.
  </thebibliography>
</body>

<\initial>
  <\collection>
    <associate|magnification|1.2>
    <associate|page-height|auto>
    <associate|page-medium|paper>
    <associate|page-type|letter>
    <associate|page-width|auto>
  </collection>
</initial>

<\references>
  <\collection>
    <associate|auto-1|<tuple|1|1>>
    <associate|auto-2|<tuple|2|2>>
    <associate|auto-3|<tuple|3|3>>
    <associate|auto-4|<tuple|4|4>>
    <associate|auto-5|<tuple|5|5>>
    <associate|auto-6|<tuple|6|5>>
    <associate|auto-7|<tuple|7|5>>
    <associate|auto-8|<tuple|7|?>>
    <associate|bib-cramer1967|<tuple|cramer1967|5>>
    <associate|bib-kac1943|<tuple|kac1943|5>>
    <associate|bib-priestley1965|<tuple|priestley1965|5>>
    <associate|bib-rice1945|<tuple|rice1945|5>>
    <associate|def:Mtheta_inv|<tuple|6|2>>
    <associate|def:oscillatory|<tuple|3|2>>
    <associate|def:scaling|<tuple|1|1>>
    <associate|def:unitary|<tuple|4|2>>
    <associate|eq:osc_process|<tuple|6|3>>
    <associate|eq:oscillatoryrep|<tuple|7|3>>
    <associate|eq:oscrep|<tuple|1|2>>
    <associate|eq:stat_spectral|<tuple|5|3>>
    <associate|eq:unitaryM|<tuple|2|2>>
    <associate|eq:unitaryM_inverse|<tuple|4|2>>
    <associate|eq:unitnorm|<tuple|3|2>>
    <associate|lem:invert|<tuple|7|3>>
    <associate|lem:unitary|<tuple|5|2>>
    <associate|thm:L2|<tuple|10|4>>
    <associate|thm:evolve|<tuple|9|4>>
    <associate|thm:kac_rice|<tuple|12|?>>
    <associate|thm:spectral|<tuple|8|3>>
    <associate|thm:zerocount|<tuple|13|5>>
  </collection>
</references>

<\auxiliary>
  <\collection>
    <\associate|toc>
      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|1<space|2spc>Scaling
      Functions and Oscillatory Processes>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-1><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|2<space|2spc>Unitary
      Time-Change Operator and its Inverse>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-2><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|3<space|2spc>Oscillatory
      Representation of Unitary Time-Changed Stationary Processes>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-3><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|4<space|2spc><with|mode|<quote|math>|L<rsup|2>>-Norm
      Preservation by Unitary Time-Change>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-4><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|5<space|2spc>Expected
      Zero Formula> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-5><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|6<space|2spc>Conclusion>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-6><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|Bibliography>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-7><vspace|0.5fn>
    </associate>
  </collection>
</auxiliary>