<TeXmacs|2.1.4>

<style|<tuple|generic|framed-theorems>>

<\body>
  <doc-data|<doc-title|Exact Spectral Representation and Inversion of
  Oscillatory Stochastic Processes>|<doc-author|<author-data|<author-name|Stephen
  Crowley>|<\author-affiliation>
    <date|>
  </author-affiliation>>>>

  <\table-of-contents|toc>
    <vspace*|1fn><with|font-series|bold|math-font-series|bold|1<space|2spc>Introduction>
    <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-1><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|2<space|2spc>Harmonizable
    Processes> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-2><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|3<space|2spc>Oscillatory
    Processes> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-3><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|4<space|2spc>Exact
    Inversion Formulae> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-4><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|5<space|2spc>Wigner-Ville
    Spectral Identity> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-5><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|6<space|2spc>Functional
    Analytic Structure> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-6><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|7<space|2spc>Comparison
    of Process Classes> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-7><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|8<space|2spc>Conclusion>
    <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-8><vspace|0.5fn>
  </table-of-contents>

  <section|Introduction>

  This document establishes the <with|font-series|bold|exact mathematical
  foundations> of oscillatory stochastic processes via measure-theoretic
  spectral analysis. We develop the theory of harmonizable and oscillatory
  processes, provide explicit spectral representations, and prove exact
  inversion formulae for the orthogonal random measures. The exposition is
  rigorous and self-contained, with all results stated and proved as
  theorems.

  <section|Harmonizable Processes>

  <\definition>
    [Harmonizable Process] A complex-valued stochastic process
    <math|<around|{|X<around|(|t|)>:t\<in\>\<bbb-R\>|}>> is <em|harmonizable>
    if there exists a positive definite, bounded bivariate measure <math|F>
    on <math|\<bbb-R\><rsup|2>> such that

    <\equation*>
      R<around|(|s,t|)>=\<bbb-E\><around|[|X<around|(|s|)><wide|X<around|(|t|)>|\<bar\>>|]>=<big|iint><rsub|\<bbb-R\><rsup|2>>e<rsup|i*<around|(|\<omega\>*s-\<xi\>*t|)>>*<space|0.17em>d*F<around|(|\<omega\>,\<xi\>|)>
    </equation*>

    for all <math|s,t\<in\>\<bbb-R\>>.
  </definition>

  <\theorem>
    [Spectral Representation of Harmonizable Processes] Let
    <math|<around|{|X<around|(|t|)>|}>> be a harmonizable process with
    spectral measure <math|F>. Then there exists a stochastic process
    <math|Z<around|(|\<lambda\>|)>> with orthogonal increments such that

    <\equation*>
      X<around|(|t|)>=<big|int><rsub|\<bbb-R\>>e<rsup|i*\<lambda\>*t>*d*Z<around|(|\<lambda\>|)>
    </equation*>

    where

    <\equation*>
      \<bbb-E\>*<around|[|d*Z<around|(|\<omega\>|)><wide|d*Z<around|(|\<xi\>|)>|\<bar\>>|]>=d*F<around|(|\<omega\>,\<xi\>|)>
    </equation*>
  </theorem>

  <\proof>
    The proof follows from the theory of isometric embeddings of the Hilbert
    space generated by <math|<around|{|X<around|(|t|)>|}>> into
    <math|L<rsup|2><around|(|F|)>>. By Kolmogorov's existence theorem, for
    each <math|t>, define the function <math|f<rsub|t><around|(|\<omega\>|)>=e<rsup|i*\<omega\>*t>>.
    The covariance structure ensures that the mapping
    <math|X<around|(|t|)>\<mapsto\>f<rsub|t>> preserves inner products. Thus,
    there exists a stochastic measure <math|Z> such that the stated
    representation holds, and the orthogonality of increments follows from
    the positive definiteness of <math|F>.
  </proof>

  <section|Oscillatory Processes>

  <\definition>
    [Oscillatory Process] A harmonizable process
    <math|<around|{|X<around|(|t|)>|}>> is called <em|oscillatory> if it
    admits the representation

    <\equation*>
      X<around|(|t|)>=<big|int><rsub|\<bbb-R\>>A<rsub|t><around|(|\<lambda\>|)>*e<rsup|i*\<lambda\>*t>*d*Z<around|(|\<lambda\>|)>
    </equation*>

    where <math|A<rsub|t><around|(|\<lambda\>|)>> is a deterministic,
    invertible function of <math|<around|(|t,\<lambda\>|)>>, and
    <math|Z<around|(|\<lambda\>|)>> is a process with orthogonal increments:

    <\equation*>
      \<bbb-E\><around|[|<around|\||d*Z<around|(|\<lambda\>|)>|\|><rsup|2>|]>=d*\<mu\><around|(|\<lambda\>|)>
    </equation*>

    for some finite positive measure <math|\<mu\>>.
  </definition>

  <\theorem>
    [Covariance Structure of Oscillatory Processes] Let
    <math|X<around|(|t|)>> be an oscillatory process as above. Then its
    covariance is given by

    <\equation*>
      R<around|(|s,t|)>=<big|int><rsub|\<bbb-R\>>A<rsub|s><around|(|\<lambda\>|)><wide|A<rsub|t><around|(|\<lambda\>|)>|\<bar\>>e<rsup|i*\<lambda\>*<around|(|s-t|)>>*d*\<mu\><around|(|\<lambda\>|)>
    </equation*>
  </theorem>

  <\proof>
    By linearity and the properties of <math|Z<around|(|\<lambda\>|)>>,

    <\align*>
      <tformat|<table|<row|<cell|R<around|(|s,t|)>>|<cell|=\<bbb-E\><around|[|X<around|(|s|)><wide|X<around|(|t|)>|\<bar\>>|]>>>|<row|<cell|>|<cell|=\<bbb-E\><around*|[|<big|int><rsub|\<bbb-R\>>A<rsub|s><around|(|\<lambda\>|)>*e<rsup|i*\<lambda\>*s>*d*Z<around|(|\<lambda\>|)>\<cdot\><wide|<big|int><rsub|\<bbb-R\>>A<rsub|t><around|(|\<xi\>|)>*e<rsup|i*\<xi\>*t>*d*Z<around|(|\<xi\>|)>|\<bar\>>|]>>>|<row|<cell|>|<cell|=<big|int><rsub|\<bbb-R\>><big|int><rsub|\<bbb-R\>>A<rsub|s><around|(|\<lambda\>|)><wide|A<rsub|t><around|(|\<xi\>|)>|\<bar\>>e<rsup|i*\<lambda\>*s>*e<rsup|-i*\<xi\>*t>*\<bbb-E\>*<around|[|d*Z<around|(|\<lambda\>|)><wide|d*Z<around|(|\<xi\>|)>|\<bar\>>|]>>>|<row|<cell|>|<cell|=<big|int><rsub|\<bbb-R\>>A<rsub|s><around|(|\<lambda\>|)><wide|A<rsub|t><around|(|\<lambda\>|)>|\<bar\>>e<rsup|i*\<lambda\>*<around|(|s-t|)>>*d*\<mu\><around|(|\<lambda\>|)>>>>>
    </align*>

    where the last step uses the orthogonality
    <math|\<bbb-E\>*<around|[|d*Z<around|(|\<lambda\>|)><wide|d*Z<around|(|\<xi\>|)>|\<bar\>>|]>=\<delta\>*<around|(|\<lambda\>-\<xi\>|)>*d*\<mu\><around|(|\<lambda\>|)>>.
  </proof>

  <\definition>
    [Evolutionary Spectrum] The <em|evolutionary spectrum> of
    <math|X<around|(|t|)>> is

    <\equation*>
      h<rsub|t><around|(|\<lambda\>|)>=<around|\||A<rsub|t><around|(|\<lambda\>|)>|\|><rsup|2><frac|d*\<mu\>|d*\<lambda\>>
    </equation*>

    when <math|\<mu\>> is absolutely continuous with respect to Lebesgue
    measure.
  </definition>

  <section|Exact Inversion Formulae>

  <\theorem>
    [Exact Stochastic Inversion]<label|thm:inversion>Let
    <math|X<around|(|t|)>> be an oscillatory process with invertible
    <math|A<rsub|t><around|(|\<lambda\>|)>> for all <math|t> and
    <math|\<lambda\>>. Then the orthogonal random measure
    <math|d*Z<around|(|\<lambda\>|)>> is recovered exactly by

    <\equation*>
      d*Z<around|(|\<lambda\>|)>=<frac|1|2*\<pi\>>*<big|int><rsub|-\<infty\>><rsup|\<infty\>>X<around|(|t|)>*A<rsub|t><rsup|-1><around|(|\<lambda\>|)>*e<rsup|-i*\<lambda\>*t>*d*t
    </equation*>

    in the mean-square sense.
  </theorem>

  <\proof>
    Substitute the representation of <math|X<around|(|t|)>>:

    <\align*>
      <tformat|<table|<row|<cell|<frac|1|2*\<pi\>>*<big|int><rsub|-\<infty\>><rsup|\<infty\>>X<around|(|t|)>*A<rsub|t><rsup|-1><around|(|\<lambda\>|)>*e<rsup|-i*\<lambda\>*t>*d*t>|<cell|=<frac|1|2*\<pi\>>*<big|int><rsub|-\<infty\>><rsup|\<infty\>><around*|(|<big|int><rsub|\<bbb-R\>>A<rsub|t><around|(|\<xi\>|)>*e<rsup|i*\<xi\>*t>*d*Z<around|(|\<xi\>|)>|)>*A<rsub|t><rsup|-1><around|(|\<lambda\>|)>*e<rsup|-i*\<lambda\>*t>*d*t>>|<row|<cell|>|<cell|=<big|int><rsub|\<bbb-R\>><around*|(|<frac|1|2*\<pi\>>*<big|int><rsub|-\<infty\>><rsup|\<infty\>><frac|A<rsub|t><around|(|\<xi\>|)>|A<rsub|t><around|(|\<lambda\>|)>>*e<rsup|i*<around|(|\<xi\>-\<lambda\>|)>*t>*d*t|)>*d*Z<around|(|\<xi\>|)>>>>>
    </align*>

    Since <math|A<rsub|t><around|(|\<lambda\>|)>> is invertible and
    deterministic, and for <math|\<xi\>=\<lambda\>> the ratio is <math|1>,
    while for <math|\<xi\>\<neq\>\<lambda\>> the oscillatory integral yields
    <math|0> (by the Fourier inversion theorem):

    <\equation*>
      <frac|1|2*\<pi\>>*<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*<around|(|\<xi\>-\<lambda\>|)>*t>*d*t=\<delta\>*<around|(|\<xi\>-\<lambda\>|)>
    </equation*>

    Thus,

    <\equation*>
      d*Z<around|(|\<lambda\>|)>=<big|int><rsub|\<bbb-R\>>\<delta\>*<around|(|\<xi\>-\<lambda\>|)>*d*Z<around|(|\<xi\>|)>=d*Z<around|(|\<lambda\>|)>
    </equation*>

    almost surely and in mean-square.
  </proof>

  <\remark>
    The inversion is exact; no estimation or approximation is involved.
  </remark>

  <\theorem>
    [Dual Basis Inversion] Let <math|\<psi\><rsub|t><around|(|\<lambda\>|)>=A<rsub|t><rsup|-1><around|(|\<lambda\>|)>*e<rsup|-i*\<lambda\>*t>>.
    Then

    <\equation*>
      d*Z<around|(|\<lambda\>|)>=<big|int><rsub|-\<infty\>><rsup|\<infty\>>X<around|(|t|)><wide|\<psi\><rsub|t><around|(|\<lambda\>|)>|\<bar\>>d*t
    </equation*>

    where the integral is interpreted in the <math|L<rsup|2>> sense.
  </theorem>

  <\proof>
    By biorthogonality,

    <\equation*>
      <big|int><rsub|-\<infty\>><rsup|\<infty\>>A<rsub|t><around|(|\<lambda\>|)>*e<rsup|i*\<lambda\>*t><wide|\<psi\><rsub|t><around|(|\<xi\>|)>|\<bar\>>d*t=<big|int><rsub|-\<infty\>><rsup|\<infty\>>A<rsub|t><around|(|\<lambda\>|)>*e<rsup|i*\<lambda\>*t>*A<rsub|t><rsup|-1><around|(|\<xi\>|)>*e<rsup|i*\<xi\>*t>*d*t=\<delta\>*<around|(|\<lambda\>-\<xi\>|)>
    </equation*>

    Thus, projecting <math|X<around|(|t|)>> onto
    <math|<wide|\<psi\><rsub|t><around|(|\<lambda\>|)>|\<bar\>>> extracts
    <math|d*Z<around|(|\<lambda\>|)>> exactly.
  </proof>

  <section|Wigner-Ville Spectral Identity>

  <\definition>
    [Wigner-Ville Transform] The Wigner-Ville transform of
    <math|X<around|(|t|)>> is

    <\equation*>
      W<rsub|X><around|(|t,\<lambda\>|)>=<big|int><rsub|-\<infty\>><rsup|\<infty\>>X*<around*|(|t+<frac|\<tau\>|2>|)><wide|X*<around*|(|t-<frac|\<tau\>|2>|)>|\<bar\>>e<rsup|-i*\<lambda\>*\<tau\>>*d*\<tau\>
    </equation*>
  </definition>

  <\theorem>
    [Expected Wigner-Ville Spectrum]

    <\equation*>
      <big|int><rsub|-\<infty\>><rsup|\<infty\>>\<bbb-E\><around|[|W<rsub|X><around|(|t,\<lambda\>|)>|]>*d*t=2*\<pi\>*h<rsub|t><around|(|\<lambda\>|)>*d*\<lambda\>
    </equation*>
  </theorem>

  <\proof>
    By linearity and the definition of <math|h<rsub|t><around|(|\<lambda\>|)>>,
    and using Fubini's theorem, the expected value of the Wigner-Ville
    transform integrates to the evolutionary spectrum times <math|2*\<pi\>>,
    as shown in Priestley's original derivation.
  </proof>

  <section|Functional Analytic Structure>

  <\theorem>
    [Hilbert Space Isometry] Let <math|\<cal-H\><rsub|X>=<wide|<math-up|span>|\<bar\>><around|{|X<around|(|t|)>|}>>
    in <math|L<rsup|2><around|(|\<Omega\>|)>>. Then the mapping

    <\equation*>
      X<around|(|t|)>\<mapsto\>A<rsub|t><around|(|\<lambda\>|)>*e<rsup|i*\<lambda\>*t>
    </equation*>

    is an isometry from <math|\<cal-H\><rsub|X>> to
    <math|L<rsup|2><around|(|\<mu\>|)>>.
  </theorem>

  <\proof>
    The inner product in <math|\<cal-H\><rsub|X>> is

    <\equation*>
      <around|\<langle\>|X<around|(|s|)>,X<around|(|t|)>|\<rangle\>>=\<bbb-E\><around|[|X<around|(|s|)><wide|X<around|(|t|)>|\<bar\>>|]>=<big|int><rsub|\<bbb-R\>>A<rsub|s><around|(|\<lambda\>|)><wide|A<rsub|t><around|(|\<lambda\>|)>|\<bar\>>e<rsup|i*\<lambda\>*<around|(|s-t|)>>*d*\<mu\><around|(|\<lambda\>|)>
    </equation*>

    which matches the <math|L<rsup|2><around|(|\<mu\>|)>> inner product of
    the corresponding functions.
  </proof>

  <section|Comparison of Process Classes>

  <\theorem>
    [Oscillatory <math|\<Longrightarrow\>> Strongly Harmonizable] Every
    oscillatory process is strongly harmonizable, with spectral measure

    <\equation*>
      d*F<around|(|\<omega\>,\<xi\>|)>=A<rsub|s><around|(|\<omega\>|)><wide|A<rsub|t><around|(|\<xi\>|)>|\<bar\>>\<delta\>*<around|(|\<omega\>-\<xi\>|)>*d*\<mu\><around|(|\<omega\>|)>*d*\<xi\>
    </equation*>
  </theorem>

  <\proof>
    Follows directly from the covariance structure and the definition of
    strong harmonizability (bounded Vitali variation, diagonal support).
  </proof>

  <\theorem>
    [Stationarity as a Special Case] If <math|A<rsub|t><around|(|\<lambda\>|)>\<equiv\>1>,
    then the oscillatory process reduces to a stationary process with

    <\equation*>
      d*F<around|(|\<omega\>,\<xi\>|)>=\<delta\>*<around|(|\<omega\>-\<xi\>|)>*d*\<mu\><around|(|\<omega\>|)>
    </equation*>
  </theorem>

  <\proof>
    Immediate from the definitions.
  </proof>

  <section|Conclusion>

  Oscillatory processes provide a mathematically exact framework for
  non-stationary stochastic analysis:

  <\itemize>
    <item><with|font-series|bold|Exact invertibility>: Random measures are
    recovered by closed-form integrals.

    <item><with|font-series|bold|No estimation error>: Deterministic
    modulation avoids approximation.

    <item><with|font-series|bold|Functional analytic rigor>: Isometries
    guarantee unique representations.
  </itemize>

  This theory finalizes the program of Priestley and Rao, establishing
  oscillatory processes as the canonical setting for exact time-frequency
  spectral analysis.
</body>

<\initial>
  <\collection>
    <associate|magnification|1.2>
    <associate|page-medium|paper>
  </collection>
</initial>

<\references>
  <\collection>
    <associate|auto-1|<tuple|1|1|../../.TeXmacs/texts/scratch/no_name_2.tm>>
    <associate|auto-2|<tuple|2|1|../../.TeXmacs/texts/scratch/no_name_2.tm>>
    <associate|auto-3|<tuple|3|2|../../.TeXmacs/texts/scratch/no_name_2.tm>>
    <associate|auto-4|<tuple|4|3|../../.TeXmacs/texts/scratch/no_name_2.tm>>
    <associate|auto-5|<tuple|5|4|../../.TeXmacs/texts/scratch/no_name_2.tm>>
    <associate|auto-6|<tuple|6|4|../../.TeXmacs/texts/scratch/no_name_2.tm>>
    <associate|auto-7|<tuple|7|5|../../.TeXmacs/texts/scratch/no_name_2.tm>>
    <associate|auto-8|<tuple|8|5|../../.TeXmacs/texts/scratch/no_name_2.tm>>
    <associate|thm:inversion|<tuple|6|3|../../.TeXmacs/texts/scratch/no_name_2.tm>>
  </collection>
</references>

<\auxiliary>
  <\collection>
    <\associate|toc>
      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|1<space|2spc>Introduction>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-1><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|2<space|2spc>Harmonizable
      Processes> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-2><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|3<space|2spc>Oscillatory
      Processes> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-3><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|4<space|2spc>Exact
      Inversion Formulae> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-4><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|5<space|2spc>Wigner-Ville
      Spectral Identity> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-5><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|6<space|2spc>Functional
      Analytic Structure> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-6><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|7<space|2spc>Comparison
      of Process Classes> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-7><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|8<space|2spc>Conclusion>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-8><vspace|0.5fn>
    </associate>
  </collection>
</auxiliary>