#!/usr/bin/env bash
# create-103-subissues.sh
#
# Create detailed sub-issues for issue #103 in crowlogic/bonanzai using the
# GitHub CLI (gh). This script:
#  - creates issues 103-A .. 103-J with full, production-ready bodies
#  - posts a comment to the parent issue #103 listing the created issues
#
# Usage:
#   1) Install & authenticate gh: `gh auth login`
#   2) Save this script, chmod +x ./create-103-subissues.sh
#   3) Run: ./create-103-subissues.sh
#
# Preconditions:
#   - gh must be installed and authenticated as a user with permission to create
#     issues in the repository crowlogic/bonanzai.
#
# Safety:
#   - Script creates issues only. It does not modify repo files or branches.
#
set -euo pipefail

REPO="crowlogic/bonanzai"
PARENT_ISSUE=103

# Sanity checks ---------------------------------------------------------------
command -v gh >/dev/null 2>&1 || { echo "ERROR: gh (GitHub CLI) not found in PATH."; exit 1; }
if ! gh repo view "$REPO" >/dev/null 2>&1; then
  echo "ERROR: gh cannot access repository $REPO. Ensure you are authenticated and have permissions."
  exit 1
fi

# Temporary files cleanup
TMP_FILES=()
cleanup() {
  for f in "${TMP_FILES[@]:-}"; do
    [[ -f "$f" ]] && rm -f "$f"
  done
}
trap cleanup EXIT

# Helper: create an issue from a here-doc body
create_issue_from_heredoc() {
  local key="$1"
  local title="$2"
  local tmp
  tmp="$(mktemp "/tmp/${key}.XXXXXX.md")"
  TMP_FILES+=("$tmp")
  # Body provided via stdin (heredoc called by caller)
  cat > "$tmp"
  echo "Creating issue $key -> $title"
  # Use gh to create issue; return number
  num=$(gh issue create --repo "$REPO" --title "$title" --body-file "$tmp" --json number --jq '.number')
  echo "Created issue #$num for $key"
  echo "$num"
}

# We'll create each issue with a full, detailed body. Each create call calls the
# function and supplies the body via a here-doc. The bodies are intentionally
# verbose and complete, containing implementation steps, tests, files to modify,
# and exit criteria.

declare -A CREATED_ISSUES=()

# 103-A
num=$(create_issue_from_heredoc "103-A" "103-A: [arb4j] Implement bytecode generation for ∞ convergence loops" <<'BODY'
Title: 103-A: [arb4j] Implement bytecode generation for ∞ convergence loops

Summary
-------
Design and implement the compiler bytecode emission so that NAry operations
(SumNode/ProductNode) detect an infinite upper bound (`upperLimit.isPositiveInfinity()`)
and emit a convergence-driven loop instead of a fixed-bound index loop. This is
the foundational change enabling automatic, data-driven truncation (Σ{..∞}).

Why
---
Current behavior emits bytecode that executes a fixed `for k = a..N` loop.
N is currently supplied as a context variable and mutated externally. That
approach is incorrect for convergent series: the correct termination is data-driven
(convergence), not a prior allocated integer bound.

Goals
-----
- Detect ∞ upper bound in NAry operation nodes
- Emit inline convergence-based loop in the generated bytecode
- Provide deterministic divergence detection (running-max / peakCount)
- Unit tests for dispatch & basic convergence/divergence behaviors

Design / Implementation Plan
----------------------------
Phase 1 — Design the canonical loop (pseudocode):
  tolerance = 2^{-bits}
  runningMax = 0
  peakCount = 0
  index = lowerLimit
  accumulator = identity

  loop:
    term = operand.evaluate(index, 1, bits, scratch)
    if term is null: throw ArithmeticException("operand returned null")
    termAbs = |term|
    if termAbs < tolerance:
      accumulator = accumulator ∘ term
      break
    if termAbs > runningMax:
      runningMax = termAbs
      peakCount++
      if peakCount >= 3:
        throw ArithmeticException("series diverges: 3 consecutive new peaks")
    accumulator = accumulator ∘ term
    index++
    goto loop

Phase 2 — Locate generator entrypoints:
- File(s):
  - arb/expressions/nodes/nary/NAryOperationNode.java
  - arb/expressions/nodes/nary/SumNode.java
  - arb/expressions/nodes/nary/ProductNode.java
- Find the methods generating bounded loops and identify where the upperLimit comparison is emitted.

Phase 3 — Add ∞ detection & dispatch:
- Add utility: `boolean upperIsInfinity(Node upperLimit)` or reuse existing API if present.
- Emit conditional in code generation: if upperIsInfinity -> call convergence loop emitter; else -> emit existing bounded loop.

Phase 4 — Convergence bytecode emission:
- Emit local variables for:
  - tolerance (computed from bits): Real tolerance = 2^{-bits}
  - runningMax (Real)
  - peakCount (int)
  - index (Integer / primitive int, whichever is appropriate for index variable)
  - accumulator (type matches R)
- Emit operand evaluation at each iteration:
  - Must set operand's index variable into the operand instance prior to calling operand's evaluate.
  - Use same operand scratch variable strategy the compiler currently uses.
- Emit comparisons: absolute value, compare to tolerance; update runningMax and peakCount; throw ArithmeticException when peakCount >= 3 with diagnostic message including index, runningMax, last term magnitude and bits.
- Emit accumulation via existing fold operation (add/mul).

Diagnostics & Error Messages
----------------------------
When throwing ArithmeticException for divergence include:
- index
- peakCount
- runningMax
- last term magnitude
- tolerance and bits

This helps debugging mis-parameters (e.g. unsuitable model parameters) vs. code bugs.

Testing (unit and integration)
------------------------------
- Unit tests to verify dispatch:
  - SumNode chooses convergence path for ∞ and bounded path for finite upper limit.
- Convergence case tests:
  - Series Σ (1/2)^k converges to 2. Verify generator terminates early and returns ~2 within tolerance.
  - Series Σ 1/k^2 converges. Validate correctness.
  - Verify tolerance calculation scales with bits.
- Divergence tests:
  - Series with strictly increasing terms (e.g., k) should throw ArithmeticException after ~3 peaks.
  - Alternating series that converges (conditionally) must NOT be flagged as divergent incorrectly.
- Integration test:
  - Compile a small expression using Σ{..∞} and execute. Verify correct numeric output and no resource leak.

Files to Change
---------------
- arb/expressions/nodes/nary/NAryOperationNode.java — add the converge-path emission and dispatch.
- arb/expressions/nodes/nary/SumNode.java — ensure parse/AST accepts ∞ as upper bound (if not, add recognition).
- Tests: Add SumNodeConvergenceDispatchTest, NAryOperationNodeConvergentAccumulationTest

Exit Criteria
-------------
- Compiler emits the convergence loop when upper limit is ∞.
- Convergent numeric tests pass.
- Divergent numeric tests throw clearly diagnostic exceptions.
- No regression in finite-bound sum behavior.
BODY
)
CREATED_ISSUES["103-A"]=$num

# 103-B
num=$(create_issue_from_heredoc "103-B" "103-B: [arb4j] Rewrite NAryOperationNode.generateConvergentAccumulation()" <<'BODY'
Title: 103-B: [arb4j] Rewrite NAryOperationNode.generateConvergentAccumulation()

Summary
-------
Refactor NAryOperationNode to emit inline convergence-terminated accumulation bytecode
instead of calling static helper methods. This implements the canonical loop for the
infinite-sum case and ensures a single uniform algorithm for accumulation.

Why
---
Previously helper methods duplicated accumulation semantics or were invoked in Java.
After 103-A determines when infinite-bound behavior is required, this method must
emit the full loop with tolerance and divergence checks inline into generated bytecode.

Implementation Plan
-------------------
1) Extract current bounded-loop emission into a helper
   - Create `generateBoundedAccumulation(...)` that emits existing `for k=a..b` code.
   - Unit-test bounded path remains unchanged.

2) Implement `generateConvergenceTerminatedAccumulation(...)`
   - Emit variables:
     - tolerance = 2^(-bits) (Real)
     - runningMax (Real, initialized to zero)
     - peakCount (int, 0)
     - index = lowerLimit (Integer or primitive index representation)
     - accumulator = identity()
   - Loop emission:
     - Label loopStart
     - Evaluate operand.evaluate(index, 1, bits, scratch)
     - Null-check the returned term
     - Compute termAbs = abs(term)
     - If termAbs < tolerance: accumulator ∘= term; goto exitSuccess
     - If termAbs > runningMax:
       - runningMax = termAbs
       - peakCount++
       - if peakCount >= 3: throw ArithmeticException with diagnostics
     - accumulator ∘= term
     - index++; goto loopStart
     - Label exitSuccess: return accumulator
   - Use existing operation fold (add/mul) for accumulation.

3) Replace calls to static helpers
   - Delete or stop calling accumulateReal/accumulatePolynomial from other code.
   - Ensure all call sites flow through NAryOperationNode's new methods.

4) Emit compact diagnostic messages
   - When throwing divergence, include index, peakCount, runningMax, lastTerm, tolerance, bits.

Testing
-------
- Bounded loop regression tests (existing tests must pass).
- Convergent series tests: geometric series, 1/k^2, etc.
- Divergence test: increasing series -> ArithmeticException.
- Bytecode validation: optionally disassemble the generated class to ensure loop labels and local slots exist (javap -c).

Files to Modify
--------------
- arb/expressions/nodes/nary/NAryOperationNode.java (primary)
- Add tests:
  - src/test/java/arb/expressions/nodes/nary/NAryOperationNodeConvergentAccumulationTest.java

Exit Criteria
-------------
- Convergence loop is emitted and behaves per design.
- All tests pass, including bounded-loop regression tests.
BODY
)
CREATED_ISSUES["103-B"]=$num

# 103-C
num=$(create_issue_from_heredoc "103-C" "103-C: [arb4j] Delete static accumulateReal/accumulatePolynomial and cleanup" <<'BODY'
Title: 103-C: [arb4j] Delete static accumulateReal/accumulatePolynomial and cleanup

Summary
-------
Remove the old static helper methods accumulateReal and accumulatePolynomial which
duplicated accumulation logic. After 103-B, all accumulation is emitted inline in
NAryOperationNode. Delete dead code and update tests accordingly.

Plan
----
1) Find all references to accumulateReal and accumulatePolynomial:
   - Search the repository for these method names; list all call sites.

2) Replace call sites:
   - Ensure generateConvergentAccumulation() (103-B) provides the same semantics inline.
   - Update callers (if any) to use the new bytecode emission path.

3) Delete the static helper methods:
   - Remove the methods from NAryOperationNode.java
   - Remove any JavaDoc referencing them.

4) Update tests:
   - Remove unit tests that directly exercised these helper methods.
   - Add/refactor integration tests to exercise the emitted convergence loops.

5) Run full test-suite to ensure no leftover references.

Files to Modify
--------------
- arb/expressions/nodes/nary/NAryOperationNode.java (delete static methods)
- Tests updated or deleted as necessary.

Exit Criteria
-------------
- No compile-time references to accumulateReal/accumulatePolynomial remain.
- Test-suite passes.
BODY
)
CREATED_ISSUES["103-C"]=$num

# 103-D
num=$(create_issue_from_heredoc "103-D" "103-D: [arb4j] Add running-max divergence detection" <<'BODY'
Title: 103-D: [arb4j] Add running-max divergence detection

Summary
-------
Implement running-max / peakCount divergence detection inside the convergence loop.
If the sequence exhibits 3 consecutive new peaks (each new term's absolute value
exceeds the previous running maximum) without hitting convergence, throw an
ArithmeticException with diagnostic metadata.

Rationale
---------
This enforces the necessary condition a_k → 0 for convergence via a contrapositive:
if the sequence keeps producing larger peaks repeatedly, it cannot converge and the
evaluation should fail fast.

Implementation Detail
---------------------
- In the convergence loop emitted by 103-B, maintain:
  - runningMax : Real (absolute magnitude of largest term seen so far)
  - peakCount  : integer (count of times a new runningMax was observed)
- After computing termAbs = |term|:
  - if termAbs > runningMax:
      runningMax = termAbs
      peakCount++
      if peakCount >= 3:
        throw new ArithmeticException("series diverges: 3 consecutive new peaks; index=..., runningMax=..., lastTerm=..., bits=...")
- Else continue normal accumulation.

Diagnostic message must include:
- index where divergence was detected
- runningMax
- lastTerm magnitude
- bits/tolerance used
- suggestion: "Check model parameters or increase precision"

Testing
-------
- Divergent case: Σ k -> should throw after ~3 peaks.
- Oscillating but convergent case: Σ (-1)^k/(k+1) -> should not throw.
- Convergent geometric series -> must not throw and must produce correct sum.
- Integration with rough-Heston mis-parameterized case producing non-decaying coefficients -> must throw.

Files to Modify
--------------
- arb/expressions/nodes/nary/NAryOperationNode.java (convergence loop)
- Add NAryDivergenceDetectionTest.java covering above cases.

Exit Criteria
-------------
- Divergence detection reliably throws with detailed diagnostics.
- No false positives on convergent series.
BODY
)
CREATED_ISSUES["103-D"]=$num

# 103-E
num=$(create_issue_from_heredoc "103-E" "103-E: [arb4j] Refactor MuntzPadeCumulantGenerator to use compiled {k=0..∞}" <<'BODY'
Title: 103-E: [arb4j] Refactor MuntzPadeCumulantGenerator to use compiled {k=0..∞}

Summary
-------
Replace the hand-written evaluate() loop in MuntzPadeCumulantGenerator with a compiled
ComplexPolynomialNullaryFunction expression that uses an infinite upper bound and
relies on the compiler's convergence loop (103-A/103-B). Remove the N truncation
field and scratch temporaries.

Goals
-----
- Remove N as a constructor parameter and context variable
- Replace manual accumulation with a compiled expression "Φ:v➔Σk➔(...){k=0..∞}"
- Delete scratch fields and manual evaluate() implementation
- Ensure numerical equivalence with the pre-refactor behavior for convergent parameter ranges

Implementation Steps
--------------------
1) Locate MuntzPadeCumulantGenerator:
   - arb/functions/complex/MuntzPadeCumulantGenerator.java

2) Identify current behavior:
   - Constructor likely accepts N0 and registers N in context.
   - evaluate() manually loops k=0..N0 computing d_k and accumulating Φ.

3) New constructor signature:
   - Remove N0 parameter:
     public MuntzPadeCumulantGenerator(Context context, ComplexPolynomialSequence a, RealSequence u, RealSequence w) { ... }

4) Compile Φ via expression:
   - Build d(k) as a sequence, and Φ as:
     ComplexPolynomialNullaryFunction.express("Φ","Σk➔(u(k)*a(k)(v) + w(k)*a(k+1)(v))*T^(k*μ+1){k=0..∞}", context);

5) Remove the old evaluate() method and scratch fields:
   - Delete temporary arrays, term fields, and manual loop logic.

6) Tests:
   - Add comparisons: old implementation (in a pre-refactor branch) vs new compiled expression on representative inputs (v and bits).
   - Validate divergence handling (integration with 103-D).

Files to Modify
--------------
- arb/functions/complex/MuntzPadeCumulantGenerator.java
- arb/tests/MuntzPadeCumulantGeneratorTest.java (update to new constructor)

Exit Criteria
-------------
- New constructor compiles and runs.
- Numerical results match old implementation for tested parameter ranges.
- No manual N variable exists in context.
BODY
)
CREATED_ISSUES["103-E"]=$num

# 103-F
num=$(create_issue_from_heredoc "103-F" "103-F: [bonanzai] Remove N context variable from RoughHestonCharacteristicFunction" <<'BODY'
Title: 103-F: [bonanzai] Remove N context variable from RoughHestonCharacteristicFunction

Summary
-------
Remove the public Integer N field from RoughHestonCharacteristicFunction and stop
registering it in the context. Update buildCgf(...) so it no longer expects an N
parameter; the CGF should be constructed to use {k=0..∞} so that truncation is
determined by runtime convergence.

Why
---
N is an accumulation index, not a user parameter. Storing it as a context variable
makes the compiled expressions rely on a mutable external bound. That leads to
incorrect/inflexible behavior and manual mutation patterns.

Implementation Plan
-------------------
1) Remove N declaration:
   - Delete: public final Integer N = Integer.named("N");

2) Remove N initialization and registration:
   - Remove this.N.set(DEFAULT_N) and context.registerVariable(N) in both constructors.

3) Update buildCgf signature and calls:
   - Before: buildCgf(context, a, N.getSignedValue())
   - After:  buildCgf(context, a)
   - Update buildCgf to not accept N0.

4) Ensure CGF is constructed via MuntzPadeCumulantGenerator that now uses infinite-sum compiled expression (103-E).

5) Remove any code paths that referenced N after removal (e.g., setN, getter, or closing N).

6) Update javadoc and comments:
   - Remove references to "Truncation order N" and mention convergence-driven accumulation.

Testing
-------
- RoughHestonCharacteristicFunction evaluates without any .N.set() calls.
- Verify context.getVariable("N") returns null.
- Integration tests: characteristic function value matches expected values across bits precisions.

Files to Modify
--------------
- src/main/java/bonanzai/options/vix/RoughHestonCharacteristicFunction.java
- Update tests referencing pricer.φ.N.set(...) (see 103-I for full test sweep)

Exit Criteria
-------------
- No public N field remains in RoughHestonCharacteristicFunction.
- No context registration of N.
- All tests depending on characteristic function pass.
BODY
)
CREATED_ISSUES["103-F"]=$num

# 103-G
num=$(create_issue_from_heredoc "103-G" "103-G: [bonanzai] Replace {k=0..N} and {j=3..J} with {..∞} in expressions" <<'BODY'
Title: 103-G: [bonanzai] Replace {k=0..N} and {j=3..J} with {..∞} in expressions

Summary
-------
Update compiled expression strings in RoughHestonOptionPricer and related classes to
use infinite upper bounds (∞) so the expression compiler emits convergence-based loops.
Do not change finite, recurrence-bounded inner-sums (e.g., {k=3..n}) that are
structurally finite.

Scope & Changes
--------------
Primary location: RoughHestonOptionPricer.compileCumulantAndPriceChain()

Replace:
- Φ: "Σk➔T^(k*μ+1)*d(k){k=0..N}"  -> "Σk➔T^(k*μ+1)*d(k){k=0..∞}"
- dΦ: similarly
- ΠPricer: "Σj➔(c(j)*ΔCseq(j)(k)){j=3..J~}" -> "Σj➔(c(j)*ΔCseq(j)(k)){j=3..∞}"

Preserve:
- c(n) recurrence inner sum: "Σk➔...{k=3..n}" remains finite and correct.

Implementation Steps
--------------------
1) Find all expression strings containing {k=0..N}, {j=3..J}, or similar patterns.
2) Replace finite upper bounds that represent series with `{..∞}`.
3) Confirm expression parser recognizes `∞` literal and that `upperLimit.isPositiveInfinity()` is true for these ASTs. (If parser does not support the Unicode char, use alternative token recognized by parser, but validate).
4) Unit test expression parsing: create expressions programmatically and ensure AST has infinite upper limit.
5) Validate the compiled classes execute the convergence path (test with small converging series to observe early-exit).

Testing
-------
- Unit tests: confirm the expression strings compile and their AST's upper limit is infinite.
- Integration tests: RoughHestonOptionPricer call() executes and converges as expected without .N.set()/.J.set() calls.
- Edge-case: verify c recurrence (inner finite sum) still uses finite upper bound set by `n`.

Files to Modify
--------------
- src/main/java/bonanzai/options/vix/RoughHestonOptionPricer.java (compileCumulantAndPriceChain)
- Any other expression string constants in bonanzai referencing N or J

Exit Criteria
-------------
- No explicit `{..N}` or `{..J}` remains in expression strings for series that should converge.
- Parser accepts ∞ and generated AST triggers convergence bytecode emission.
BODY
)
CREATED_ISSUES["103-G"]=$num

# 103-H
num=$(create_issue_from_heredoc "103-H" "103-H: [bonanzai] Remove J field and outer loops from RoughHestonOptionPricer" <<'BODY'
Title: 103-H: [bonanzai] Remove J field and outer loops from RoughHestonOptionPricer

Summary
-------
Eliminate the J context variable and any Java-side loops that increment J to
manually manage Edgeworth truncation. The Edgeworth sum should be compiled as
{j=3..∞} and handled by the expression compiler in ASYMPTOTIC mode (optimal
truncation) or CONVERGENT mode where appropriate.

Implementation Plan
-------------------
1) Identify current J usage:
   - public final Integer J; initialization and registration
   - registerJInCfContext() method
   - call() and callSensitivityForStrike() setting J prior to evaluation
   - any external code mutating J

2) Remove J field:
   - Delete declaration and initialization
   - Remove registerJInCfContext() and its invocations

3) Replace Edgeworth price expression upper bound:
   - ΠPricer: change {j=3..J~} -> {j=3..∞}
   - Use SumNode ASYMPTOTIC mode (optimal truncation) if available; otherwise the convergence loop should be extended to record global-min-gap and exit at optimal truncation.

4) Simplify call() and callSensitivityForStrike():
   - Remove loops that increment J; evaluate priceExpr/priceSensitivity once and rely on compiler-driven accumulation
   - Ensure no implicit caching assumptions are violated
   - Keep CUMULANT_ORDER as optional safety upper bound only if required; document its purpose

5) Update invalidation logic:
   - At present, code invalidates caches around J changes. With J removed, ensure the minimal set of caches are invalidated only when parameters change.

Testing
-------
- Unit tests: call() and callSensitivityForStrike() operate correctly without J.set()
- Integration: full Edgeworth benchmark runs and matches reference values
- Asymptotic behavior: verify the series truncates at the globally minimal consecutive-gap index and returns that partial sum

Files to Modify
--------------
- src/main/java/bonanzai/options/vix/RoughHestonOptionPricer.java
- Remove registerJInCfContext() and any code referencing J
- Tests updated in 103-I

Exit Criteria
-------------
- No J field remains nor any Java-side J loops.
- Pricing and sensitivity methods succeed using single evaluate() calls.
- Benchmark tests pass.
BODY
)
CREATED_ISSUES["103-H"]=$num

# 103-I
num=$(create_issue_from_heredoc "103-I" "103-I: [bonanzai] Update tests: remove .N.set/.J.set and verify convergence" <<'BODY'
Title: 103-I: [bonanzai] Update tests: remove .N.set/.J.set and verify convergence

Summary
-------
Update and modernize the test suite to reflect that N and J are not user-controlled
variables. Remove all .N.set() and .J.set() calls from tests, update expression
string expectations, and add tests that validate the automatic convergence metadata
(e.g., iterations used, tolerance, peak term magnitude).

Steps
-----
1) Identify test files using .N.set() or .J.set():
   - RoughHestonCumulantSequenceTest.java
   - RoughHestonSpeedBenchmark.java
   - RoughHestonParameterChangeInvalidationTest.java
   - RoughHestonEdgeworthBenchmarkTest.java
   - RoughHestonEdgeworthSensitivityTest.java
   - RoughHestonPriceSensitivityTest.java
   - RoughHestonCumulantSequenceTest.java
   - RoughHestonPriceSensitivityTest.java
   - MuntzPadeCumulantGeneratorTest.java (arb4j)
   - Any other tests discovered by searching for `.N.set(` or `.J.set(`

2) Edit tests:
   - Remove lines that call .N.set(...) and .J.set(...).
   - Update comments explaining why N/J were removed.
   - For tests that previously asserted values dependent on N/J behavior, update to assert
     that the resulting value is within expected tolerance (the same numerical target), not that N/J had a particular set value.

3) Add convergence metadata tests:
   - Expose a way to query last convergence metadata from compiled functions (if feasible).
   - Add tests that assert:
     - iterationsNeeded > 0
     - converged == true for expected parameter regimes
     - peakTermMagnitude is < some conservative bound for convergent cases

4) Update MuntzPadeCumulantGeneratorTest:
   - Change tests to use new constructor (no N param).
   - Delete assertNotNull(cgf.Φ) if Φ is now inaccessible, or adjust to access compiled function instance.

5) Run full test suite:
   - Ensure all unit and integration tests pass, especially RoughHestonEdgeworthBenchmarkTest (both Table 1 and Table 2).

Notes on Benchmark Tests
------------------------
- The deep-OTM Table 2 case (K=0.8, T=1/52) from issue #102 must be verified after these changes.
- If numerical differences arise, add diagnostic output to the test to capture partial sums and convergence behavior.

Exit Criteria
-------------
- No test contains .N.set() or .J.set() calls.
- All tests pass (unit, integration, benchmark).
- New convergence metadata tests exist and pass.
BODY
)
CREATED_ISSUES["103-I"]=$num

# 103-J
num=$(create_issue_from_heredoc "103-J" "103-J: Integration: Validate full pricing pipeline with ∞ convergence" <<'BODY'
Title: 103-J: Integration: Validate full pricing pipeline with ∞ convergence

Summary
-------
End-to-end integration and validation task. Once arb4j and bonanzai source changes
are in place (103-A .. 103-I), run comprehensive numerical, divergence and
performance validation to ensure correctness and acceptable performance.

Tests & Tasks
------------
1) Numerical validation:
   - Reproduce published benchmark Table 1 and Table 2 (arXiv 2508.15080).
   - For each reference strike, verify price within specified absolute tolerance.
   - Bits precisions: run at 128, 256, 512 as required for benchmarks.

2) Convergence behavior:
   - For several strikes (ATM, OTM deep tail, ITM), inspect:
     - number of terms used in Müntz sum
     - number of Edgeworth terms aggregated and point of optimal truncation
   - Ensure increasing bits increases iteration counts appropriately.

3) Divergence probes:
   - Mis-parameterization cases (e.g., ν extremely large) should trigger ArithmeticException from divergence detection rather than silent failure.
   - Tests should assert Exceptions are raised and include diagnostics.

4) Calibrator validation:
   - Run RoughHestonCalibrator integration tests for calibrator convergence.
   - Verify Jacobian and sensitivities still compute and calibrator converges to known ground-truth in sample cases.

5) Performance benchmarking:
   - Run RoughHestonSpeedBenchmark (6 calibrator prices, reduction to BS, edgeworth divergence probe).
   - Compare wall-clock to prior baseline; document results.
   - Profile CPU/allocations to ensure no severe regressions.

6) Regression test for issue #102:
   - Confirm Table 2 deep-OTM K=0.8 case returns expected value (issue #102).
   - If mismatch, collect diagnostic partial sums, term magnitudes, and convergence metadata for debugging.

Deliverables
------------
- Integration test run results report (include pass/fail and numeric deltas).
- Performance report for the benchmark.
- If failures, diagnostic logs and suggested follow-up actions.
- Documentation update describing the convergence design and how to interpret convergence metadata.

Exit Criteria
-------------
- All integration benchmarks (Table 1 & Table 2) pass to required tolerances.
- Divergence detection behaves as designed.
- Calibrator still converges correctly.
- Performance acceptable (no severe regressions).
- Changes merged or PR ready with green integration checks.
BODY
)
CREATED_ISSUES["103-J"]=$num

# Post a consolidated comment on parent issue #103 --------------------------------
echo
echo "Posting a summary comment to parent issue #$PARENT_ISSUE with created sub-issues..."
COMMENT_TMP="$(mktemp "/tmp/103-parent-comment.XXXXXX.md")"
TMP_FILES+=("$COMMENT_TMP")

{
  echo "Created blocking sub-issues for issue #$PARENT_ISSUE:"
  echo
  for key in 103-A 103-B 103-C 103-D 103-E 103-F 103-G 103-H 103-I 103-J; do
    num="${CREATED_ISSUES[$key]}"
    echo "- ${key}: https://github.com/${REPO}/issues/${num}"
  done
  echo
  echo "Each sub-issue contains detailed implementation plans, tests, files-to-modify, and exit criteria."
  echo
  echo "Workflow suggestion:"
  echo "1) Start with 103-A -> 103-B -> 103-C/103-D in arb4j."
  echo "2) Then 103-E to replace MuntzPadeCumulantGenerator with compiled {..∞} usage."
  echo "3) Move to bonanzai: 103-F -> 103-G -> 103-H, then tests 103-I."
  echo "4) Finish with integration validation 103-J."
  echo
  echo "If you want me to create PR template(s) or branch names for each change, say so and I will produce them (no action will be taken until you confirm)."
} >"$COMMENT_TMP"

gh issue comment --repo "$REPO" --issue "$PARENT_ISSUE" --body-file "$COMMENT_TMP"

echo "Done. Created sub-issues and posted a comment on #$PARENT_ISSUE."

# Print created issue numbers for convenience
echo
echo "Created issues:"
for k in 103-A 103-B 103-C 103-D 103-E 103-F 103-G 103-H 103-I 103-J; do
  echo "$k -> #${CREATED_ISSUES[$k]}  https://github.com/${REPO}/issues/${CREATED_ISSUES[$k]}"
done

echo
echo "Script completed successfully." 