<TeXmacs|2.1.4>

<style|<tuple|generic|framed-theorems>>

<\body>
  <doc-data|<doc-title|The Gram Point Hierarchy and the Lambert <math|W>
  Generator>|<doc-author|<author-data|<author-name|Stephen
  Crowley>>>|<doc-date|April 2026>>

  <abstract-data|<\abstract>
    The nontrivial zeros of the Riemann zeta function and their relationship
    to the Gram points are governed by a hierarchy of phase offset functions
    <math|\<psi\><rsub|k><around|(|t|)>=\<vartheta\><around|(|t|)>-k*t>,
    where <math|\<vartheta\>> is the Riemann--Siegel theta function. The
    explicit closed-form expressions for the level-<math|k> Gram sequence
    <math|<around|{|g<rsub|n><rsup|<around|(|k|)>>|}>> is derived in terms of
    the Lambert <math|W> function and it is shown that all terms are
    generated by iterating a single base inversion operator <math|\<Psi\>>
    composed with the Stirling residual tail of <math|\<vartheta\>>. The full
    Lagrange--Bürmann inversion produces an exact power series for
    <math|g<rsub|n><rsup|<around|(|k|)>>> in which every coefficient is
    expressible through <math|W<rsub|0>*<space|-0.17em><around*|(|<around|(|n+<tfrac|1|8>|)>*<space|0.17em>e<rsup|-<around|(|2*k+1|)>>|)>>,
    generated by a recurrence on polynomials <math|p<rsub|j>>. The
    <math|k>-th level sequence <math|X<rsub|k><around|(|n|)>=n*\<pi\>-g<rsub|n><rsup|<around|(|k-1|)>>>
    is thereby expressed entirely in closed form through the same Lambert
    <math|W> generator at shifted level.
  </abstract>>

  <\table-of-contents|toc>
    <vspace*|1fn><with|font-series|bold|math-font-series|bold|1<space|2spc>Definitions
    and Setup> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-1><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|2<space|2spc>The
    Explicit Gram Sequence> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-2><vspace|0.5fn>

    <vspace*|1fn><with|font-series|bold|math-font-series|bold|3<space|2spc>The
    Lambert <with|mode|math|W> Generator for All Corrections>
    <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
    <no-break><pageref|auto-3><vspace|0.5fn>
  </table-of-contents>

  <section|Definitions and Setup>

  <\definition>
    [Riemann\USiegel theta function]

    <\equation>
      \<vartheta\><around|(|t|)>=arg <space|-0.17em><around*|(|\<pi\><rsup|-i*t/2>*<space|0.17em>\<Gamma\>*<space|-0.17em><around*|(|<tfrac|1|4>+<tfrac|i*t|2>|)>|)><label|eq:theta-def>
    </equation>

    normalized so that <math|\<vartheta\><around|(|t|)>> is real and
    continuous for <math|t\<gtr\>0> with <math|\<vartheta\><around|(|0|)>=0>.
  </definition>

  <\definition>
    [Phase offset] For each integer <math|k\<ge\>0>:

    <\equation>
      \<psi\><rsub|k><around|(|t|)>=\<vartheta\><around|(|t|)>-k*t<label|eq:psi-def>
    </equation>
  </definition>

  <\definition>
    [Stirling residual tail] The function
    <math|\<varphi\>:<around|(|0,\<infty\>|)>\<to\>\<bbb-R\>> is defined by

    <\equation>
      \<varphi\><around|(|t|)>=<math-up|Im><space|-0.17em><around*|[|log
      \<Gamma\>*<space|-0.17em><around*|(|<tfrac|1|4>+<tfrac|i*t|2>|)>|]>-<frac|t|2>*log
      <frac|t|2>+<frac|t|2>+<frac|\<pi\>|8><label|eq:phi-exact>
    </equation>

    so that

    <\equation>
      \<vartheta\><around|(|t|)>=<frac|t|2>*log
      <frac|t|2*\<pi\>>-<frac|t|2>-<frac|\<pi\>|8>+\<varphi\><around|(|t|)><label|eq:theta-decomp>
    </equation>

    Consistency: <math|\<vartheta\><around|(|t|)>=<math-up|Im><around|[|log
    \<Gamma\>*<around|(|<tfrac|1|4>+<tfrac|i*t|2>|)>|]>-<tfrac|t|2>log
    \<pi\>>, and substituting<nbsp><eqref|eq:phi-exact>
    into<nbsp><eqref|eq:theta-decomp> gives <math|<math-up|Im><around|[|log
    \<Gamma\>*<around|(|<tfrac|1|4>+<tfrac|i*t|2>|)>|]>-<tfrac|t|2>log
    \<pi\>> since <math|log <tfrac|t|2*\<pi\>>-log <tfrac|t|2>=-log \<pi\>>.

    The function <math|\<varphi\>> is smooth on
    <math|<around|(|0,\<infty\>|)>> with asymptotic expansion

    <\equation>
      \<varphi\><around|(|t|)>\<sim\><frac|1|48*<space|0.17em>t>+<frac|7|5760*<space|0.17em>t<rsup|3>>+<frac|31|80640*<space|0.17em>t<rsup|5>>+<frac|127|430080*<space|0.17em>t<rsup|7>>+\<cdots\><label|eq:phi-asymp>
    </equation>

    arising from the Stirling series for <math|log \<Gamma\>> at
    <math|z=<tfrac|1|4>+<tfrac|i*t|2>> combined with the subleading terms of
    <math|<math-up|Im><around|[|<around|(|z-<tfrac|1|2>|)>*log z|]>>.
  </definition>

  <\definition>
    [Level-<math|k> Gram sequence] For each <math|k\<ge\>0>, the sequence
    <math|<around|{|g<rsub|n><rsup|<around|(|k|)>>|}><rsub|n\<ge\>0>> of
    positive reals satisfying

    <\equation>
      \<psi\><rsub|k><space|-0.17em><around*|(|g<rsub|n><rsup|<around|(|k|)>>|)>=n*\<pi\>,<space|2em>n=0,1,2,\<ldots\><label|eq:gram-def>
    </equation>

    For <math|k=0> this gives the ordinary Gram points
    <math|\<vartheta\><around|(|g<rsub|n><rsup|<around|(|0|)>>|)>=n*\<pi\>>.
  </definition>

  <\definition>
    [Level sequence] For <math|k\<ge\>1>:

    <\equation>
      X<rsub|k><around|(|n|)>=\<psi\><rsub|k><space|-0.17em><around*|(|g<rsub|n><rsup|<around|(|k-1|)>>|)>=\<vartheta\><space|-0.17em><around*|(|g<rsub|n><rsup|<around|(|k-1|)>>|)>-k*<space|0.17em>g<rsub|n><rsup|<around|(|k-1|)>><label|eq:Xk-def>
    </equation>
  </definition>

  <\definition>
    [Base inversion function]<label|def:Psi>Let <math|W<rsub|0>> denote the
    principal branch of the Lambert <math|W> function. For <math|c\<gtr\>0>
    and integer <math|k\<ge\>0>:

    <\equation>
      \<Psi\><around|(|c,<space|0.17em>k|)>=<frac|2*c|W<rsub|0><space|-0.17em><space|-0.17em><around*|(|<dfrac|c|\<pi\>><space|0.17em>e<rsup|-<around|(|2*k+1|)>>|)>>.<label|eq:Psi-def>
    </equation>
  </definition>

  <section|The Explicit Gram Sequence>

  <\theorem>
    [Explicit form of <math|X<rsub|k>>]<label|thm:Xk>For every
    <math|k\<ge\>1> and every <math|n\<ge\>0>:

    <\equation>
      X<rsub|k><around|(|n|)>=n*\<pi\>-g<rsub|n><rsup|<around|(|k-1|)>>.<label|eq:Xk-explicit>
    </equation>
  </theorem>

  <\proof>
    From<nbsp><eqref|eq:gram-def> at level <math|k-1>:

    <\equation>
      \<vartheta\><around|(|g<rsub|n><rsup|<around|(|k-1|)>>|)>-<around|(|k-1|)>*<space|0.17em>g<rsub|n><rsup|<around|(|k-1|)>>=n*\<pi\>
    </equation>

    , so\ 

    <\equation>
      \<vartheta\><around|(|g<rsub|n><rsup|<around|(|k-1|)>>|)>=n*\<pi\>+<around|(|k-1|)>*<space|0.17em>g<rsub|n><rsup|<around|(|k-1|)>>
    </equation>

    Then<nbsp><eqref|eq:Xk-def> gives

    <\equation>
      <tabular|<tformat|<table|<row|<cell|X<rsub|k><around|(|n|)>>|<cell|=n*\<pi\>+<around|(|k-1|)>*<space|0.17em>g<rsub|n><rsup|<around|(|k-1|)>>-k*<space|0.17em>g<rsub|n><rsup|<around|(|k-1|)>>>>|<row|<cell|>|<cell|=n*\<pi\>-g<rsub|n><rsup|<around|(|k-1|)>>>>>>>
    </equation>
  </proof>

  <\theorem>
    [Exact Lambert <math|W> inversion of the Stirling
    bulk]<label|thm:leading>Define

    <\equation>
      f<around|(|t|)>=<frac|t|2>*log <frac|t|2*\<pi\>>-<frac|<around|(|2*k+1|)>|2>*<space|0.17em>t.<label|eq:f-def>
    </equation>

    Then <math|\<Psi\><around|(|<space|0.17em>\<cdummy\><space|0.17em>,k|)>>
    inverts <math|f> exactly:

    <\equation>
      f<space|-0.17em><around*|(|\<Psi\><around|(|c,k|)>|)>=c*<space|2em><text|for
      all >c\<gtr\>0,<label|eq:Psi-inverse>
    </equation>

    and, with <math|c=\<pi\>*<around|(|n+<tfrac|1|8>|)>>,

    <\equation>
      g<rsub|n><rsup|<around|(|k|)>>=\<Psi\><space|-0.17em><around*|(|\<pi\>*<around|(|n+<tfrac|1|8>|)>,<space|0.27em>k|)>+O<around|(|n<rsup|-1>|)>=<frac|2*\<pi\>*<around|(|n+<tfrac|1|8>|)>|W<rsub|0>*<space|-0.17em><space|-0.17em><around*|(|<around|(|n+<tfrac|1|8>|)>*<space|0.17em>e<rsup|-<around|(|2*k+1|)>>|)>>+O<around|(|n<rsup|-1>|)>.<label|eq:leading>
    </equation>
  </theorem>

  <\proof>
    From<nbsp><eqref|eq:theta-decomp>, the Gram
    equation<nbsp><eqref|eq:gram-def> is

    <\equation>
      f<around|(|t|)>+\<varphi\><around|(|t|)>=c
    </equation>

    where

    <\equation>
      c=\<pi\>*<around|(|n+<tfrac|1|8>|)>
    </equation>

    The function <math|f> collects every term of
    <math|\<vartheta\><around|(|t|)>-k*t> that grows with <math|t> (the
    Stirling bulk), while <math|\<varphi\><around|(|t|)>=O<around|(|t<rsup|-1>|)>>
    is the decaying Stirling residual. Crucially, the equation
    <math|f<around|(|t|)>=c> is solved in closed form by
    <math|\<Psi\><around|(|c,k|)>> with no approximation. To
    verify<nbsp><eqref|eq:Psi-inverse>, substitute\ 

    <\equation>
      t=\<Psi\><around|(|c,k|)>=<frac|2*c|w<rsub|k><around|(|c|)>>
    </equation>

    \ into<nbsp><eqref|eq:f-def>:

    <\equation>
      f<around*|(|\<Psi\><around|(|c,k|)>|)>=f<space|-0.17em><around*|(|<frac|2*c|w<rsub|k><around|(|c|)>>|)>=<frac|c|w<rsub|k><around|(|c|)>>*log
      <frac|c|\<pi\>*<space|0.17em>w<rsub|k><around|(|c|)>>-<frac|<around|(|2*k+1|)>*<space|0.17em>c|w<rsub|k><around|(|c|)>>
    </equation>

    The Lambert equation <math|>

    <\equation>
      w<rsub|k><around|(|c|)>*<space|0.17em>e<rsup|w<rsub|k><around|(|c|)>>=<frac|c|\<pi\>>*<space|0.17em>e<rsup|-<around|(|2*k+1|)>>
    </equation>

    \ gives

    <\equation>
      log <frac|c|\<pi\>*<space|0.17em>w<rsub|k><around|(|c|)>>=w<rsub|k><around|(|c|)>+<around|(|2*k+1|)>
    </equation>

    so

    <\equation>
      <tabular|<tformat|<table|<row|<cell|f<space|-0.17em><around*|(|<frac|2*c|w<rsub|k><around|(|c|)>>|)>>|<cell|=<frac|c|w<rsub|k><around|(|c|)>>*<around*|(|w<rsub|k><around|(|c|)>+<around|(|2*k+1|)>|)>-<frac|<around|(|2*k+1|)>*<space|0.17em>c|w<rsub|k><around|(|c|)>>>>|<row|<cell|>|<cell|=c>>>>>
    </equation>

    Thus <math|\<Psi\><around|(|c,k|)>> is an exact root of
    <math|f<around|(|t|)>=c>.

    The full Gram equation <math|f<around|(|t|)>+\<varphi\><around|(|t|)>=c>
    can be rewritten as <math|f<around|(|t|)>=c-\<varphi\><around|(|t|)>>, a
    fixed-point problem <math|t=\<Psi\><around|(|c-\<varphi\><around|(|t|)>,<space|0.17em>k|)>>
    whose exact solution is given by the Lagrange\UBürmann series
    (Theorem<nbsp><reference|thm:lagrange>). The
    <math|O<around|(|n<rsup|-1>|)>> residual in<nbsp><eqref|eq:leading> comes
    entirely from <math|\<varphi\>>: since
    <math|\<varphi\><around|(|t|)>=O<around|(|t<rsup|-1>|)>> and
    <math|\<partial\><rsub|c>*\<Psi\><around|(|c,k|)>=O<around|(|1/<space|-0.17em>log
    n|)>>, dropping <math|\<varphi\>> incurs an error of order
    <math|O<around|(|n<rsup|-1>|)>>, not from any truncation of <math|f> or
    of <math|W<rsub|0>>.
  </proof>

  <\remark>
    The decomposition <math|\<vartheta\><around|(|t|)>-k*t=f<around|(|t|)>+\<varphi\><around|(|t|)>>
    separates the Gram equation into an exactly solvable part
    <math|f<around|(|t|)>=c> and a perturbation <math|\<varphi\>>. The
    Lambert <math|W> function absorbs the entirety of <math|f>\Vincluding all
    powers of <math|log t>\Vinto a single closed-form expression
    <math|\<Psi\><around|(|c,k|)>>. No asymptotic expansion of
    <math|W<rsub|0>> is used; equation<nbsp><eqref|eq:Psi-inverse> holds
    identically. The Lagrange\UBürmann series in
    Theorem<nbsp><reference|thm:lagrange> then corrects for <math|\<varphi\>>
    to all orders, yielding an exact expression for
    <math|g<rsub|n><rsup|<around|(|k|)>>> in which every coefficient is
    generated by <math|\<Psi\>> and its derivatives.
  </remark>

  <section|The Lambert <math|W> Generator for All Corrections>

  Throughout this section, <math|w<rsub|k><around|(|c|)>=W<rsub|0>*<space|-0.17em><around*|(|<frac|c|\<pi\>>*<space|0.17em>e<rsup|-<around|(|2*k+1|)>>|)>>
  and <math|a<rsub|k>=\<pi\>*<space|0.17em>e<rsup|2*k+1>>, so that
  <math|\<Psi\><around|(|c,k|)>=2*c/w<rsub|k><around|(|c|)>> and the Lambert
  equation reads <math|c=a<rsub|k>*<space|0.17em>w<rsub|k><around|(|c|)>*<space|0.17em>e<rsup|w<rsub|k><around|(|c|)>>>.

  <\theorem>
    [Derivatives of <math|\<Psi\>>]<label|thm:derivatives>The <math|j>-th
    partial derivative of <math|\<Psi\><around|(|c,k|)>> with respect to
    <math|c> is

    <\equation>
      \<partial\><rsub|c><rsup|<space|0.17em>j>*<space|0.17em>\<Psi\><around|(|c,<space|0.17em>k|)>=<frac|2*<space|0.17em>e<rsup|-<around|(|j-1|)>*<space|0.17em>w<rsub|k><around|(|c|)>>|a<rsub|k><rsup|<space|0.27em>j-1>>\<cdot\><frac|p<rsub|j><space|-0.17em><around*|(|w<rsub|k><around|(|c|)>|)>|<around*|(|1+w<rsub|k><around|(|c|)>|)><rsup|2*j-1>>,<label|eq:Psi-deriv>
    </equation>

    where the polynomials <math|p<rsub|j>> satisfy

    <\equation>
      p<rsub|1><around|(|w<rsub|k><around|(|c|)>|)>=1<label|eq:pj-recurrence>
    </equation>

    <\equation>
      p<rsub|j+1><around|(|w<rsub|k><around|(|c|)>|)>=p<rsub|j><rprime|'><around|(|w<rsub|k><around|(|c|)>|)>*<space|0.17em><around|(|1+w<rsub|k><around|(|c|)>|)>-<around*|(|<around|(|j-1|)>*<space|0.17em>w<rsub|k><around|(|c|)>+3*j-2|)>*<space|0.17em>p<rsub|j><around|(|w<rsub|k><around|(|c|)>|)>
    </equation>

    with first values

    <\equation>
      p<rsub|1><around|(|w<rsub|k><around|(|c|)>|)>=1<label|eq:pj-values>
    </equation>

    <\equation>
      p<rsub|2><around|(|w<rsub|k><around|(|c|)>|)>=-1
    </equation>

    <\equation>
      <space|1em>p<rsub|3><around|(|w<rsub|k><around|(|c|)>|)>=w<rsub|k><around|(|c|)>+4
    </equation>

    <\equation>
      p<rsub|4><around|(|w<rsub|k><around|(|c|)>|)>=-<around|(|2*<space|0.17em>w<rsub|k><around|(|c|)><rsup|2>+14*<space|0.17em>w<rsub|k><around|(|c|)>+27|)>
    </equation>
  </theorem>

  <\proof>
    From the Lambert equation <math|w<rsub|k><around|(|c|)>*<space|0.17em>e<rsup|w<rsub|k><around|(|c|)>>=c/a<rsub|k>>,
    differentiating both sides with respect to <math|c>:

    <\equation>
      <around*|(|1+w<rsub|k><around|(|c|)>|)>*<space|0.17em>e<rsup|w<rsub|k><around|(|c|)>>*<space|0.27em>\<partial\><rsub|c>*<space|0.17em>w<rsub|k><around|(|c|)>=<frac|1|a<rsub|k>>
    </equation>

    giving

    <\equation>
      \<partial\><rsub|c>*<space|0.17em>w<rsub|k><around|(|c|)>=<frac|1|a<rsub|k>*<space|0.17em>e<rsup|w<rsub|k><around|(|c|)>>*<space|0.17em><around*|(|1+w<rsub|k><around|(|c|)>|)>><label|eq:dw-dc>
    </equation>

    <with|font-series|bold|Base case> (<math|j=1>). From
    <math|\<Psi\><around|(|c,k|)>=2*c/w<rsub|k><around|(|c|)>>:

    <\equation>
      \<partial\><rsub|c>*<space|0.17em>\<Psi\><around|(|c,k|)>=<frac|2|w<rsub|k><around|(|c|)>>-<frac|2*c|w<rsub|k><around|(|c|)><rsup|2>>*<space|0.17em>\<partial\><rsub|c>*<space|0.17em>w<rsub|k><around|(|c|)>
    </equation>

    Substituting <math|c=a<rsub|k>*<space|0.17em>w<rsub|k><around|(|c|)>*<space|0.17em>e<rsup|w<rsub|k><around|(|c|)>>>
    and<nbsp><eqref|eq:dw-dc>:

    <\equation>
      <tabular|<tformat|<table|<row|<cell|\<partial\><rsub|c>*<space|0.17em>\<Psi\><around|(|c,k|)>>|<cell|=<frac|2|w<rsub|k><around|(|c|)>>-<frac|2*<space|0.17em>a<rsub|k>*<space|0.17em>w<rsub|k><around|(|c|)>*<space|0.17em>e<rsup|w<rsub|k><around|(|c|)>>|w<rsub|k><around|(|c|)><rsup|2>*<space|0.17em>a<rsub|k>*<space|0.17em>e<rsup|w<rsub|k><around|(|c|)>>*<space|0.17em><around|(|1+w<rsub|k><around|(|c|)>|)>>>>|<row|<cell|>|<cell|=<frac|2|w<rsub|k><around|(|c|)>>-<frac|2|w<rsub|k><around|(|c|)>*<space|0.17em><around|(|1+w<rsub|k><around|(|c|)>|)>>=<frac|2|1+w<rsub|k><around|(|c|)>>>>>>>
    </equation>

    confirming<nbsp><eqref|eq:Psi-deriv> at <math|j=1> with
    <math|p<rsub|1>=1>.

    <with|font-series|bold|Induction step>. Assume<nbsp><eqref|eq:Psi-deriv>
    holds at index <math|j>. The product rule applied to\ 

    <\equation>
      \<partial\><rsub|c><rsup|<space|0.17em>j>*\<Psi\><around|(|c,k|)>=2*<space|0.17em>a<rsub|k><rsup|1-j>*<space|0.17em>e<rsup|-<around|(|j-1|)>*w<rsub|k><around|(|c|)>>*<space|0.17em>p<rsub|j><around|(|w<rsub|k><around|(|c|)>|)>*<space|0.17em><around|(|1+w<rsub|k><around|(|c|)>|)><rsup|-<around|(|2*j-1|)>>
    </equation>

    \ and the factor <math|\<partial\><rsub|c>*w<rsub|k><around|(|c|)>>
    from<nbsp><eqref|eq:dw-dc> yields:

    <\equation>
      <tabular|<tformat|<cwith|1|-1|1|-1|font-base-size|9>|<table|<row|<cell|\<partial\><rsub|c><rsup|<space|0.17em>j+1>*\<Psi\><around|(|c,k|)>>|<cell|=*<around*|(|p<rsub|j><rprime|'><around|(|w<rsub|k><around|(|c|)>|)>-<around|(|j-1|)>*<space|0.17em>p<rsub|j><around|(|w<rsub|k><around|(|c|)>|)>-<frac|<around|(|2*j-1|)>*<space|0.17em>p<rsub|j><around|(|w<rsub|k><around|(|c|)>|)>|1+w<rsub|k><around|(|c|)>>|)><frac|<frac|2
      e<rsup|-<around|(|j-1|)>*w<rsub|k><around|(|c|)>>|a<rsub|k><rsup|j-1><around|(|1+w<rsub|k><around|(|c|)>|)><rsup|2*j-1>>|a<rsub|k>*<space|0.17em>e<rsup|w<rsub|k><around|(|c|)>>*<around|(|1+w<rsub|k><around|(|c|)>|)>>>>|<row|<cell|>|<cell|=<frac|2*<space|0.17em>e<rsup|-j*<space|0.17em>w<rsub|k><around|(|c|)>>|a<rsub|k><rsup|<space|0.17em>j>><frac|p<rsub|j><rprime|'><around|(|w<rsub|k><around|(|c|)>|)>*<space|0.17em><around|(|1+w<rsub|k><around|(|c|)>|)>-<around*|(|<around|(|j-1|)>*<around|(|1+w<rsub|k><around|(|c|)>|)>+<around|(|2*j-1|)>|)>*<space|0.17em>p<rsub|j><around|(|w<rsub|k><around|(|c|)>|)>|<around|(|1+w<rsub|k><around|(|c|)>|)><rsup|2*j+1>>>>>>>
    </equation>

    The induction is closed by defining

    <\equation>
      <around|(|j-1|)>*<around|(|1+w<rsub|k><around|(|c|)>|)>+<around|(|2*j-1|)>=<around|(|j-1|)>*<space|0.17em>w<rsub|k><around|(|c|)>+3*j-2
    </equation>

    since

    <\equation>
      p<rsub|j+1><around|(|w<rsub|k><around|(|c|)>|)>=p<rsub|j><rprime|'><around|(|w<rsub|k><around|(|c|)>|)>*<space|0.17em><around|(|1+w<rsub|k><around|(|c|)>|)>-<around|(|<around|(|j-1|)>*<space|0.17em>w<rsub|k><around|(|c|)>+3*j-2|)>*<space|0.17em>p<rsub|j><around|(|w<rsub|k><around|(|c|)>|)>
    </equation>

    \ The first 3 listed values follow:

    <alignat|2|<tformat|<table|<row|<cell|p<rsub|2><around|(|w<rsub|k><around|(|c|)>|)>>|<cell|=0\<cdot\><around|(|1+w<rsub|k><around|(|c|)>|)>-1\<cdot\>p<rsub|1><around|(|w<rsub|k><around|(|c|)>|)>>|<cell|>|<cell|=-1<eq-number>>>|<row|<cell|p<rsub|3><around|(|w<rsub|k><around|(|c|)>|)>>|<cell|=0\<cdot\><around|(|1+w<rsub|k><around|(|c|)>|)>-<around|(|w<rsub|k><around|(|c|)>+4|)>\<cdot\><around|(|-1|)><space|1em>>|<cell|>|<cell|=w<rsub|k><around|(|c|)>+4<eq-number>>>|<row|<cell|p<rsub|4><around|(|w<rsub|k><around|(|c|)>|)>>|<cell|=<around|(|1+w<rsub|k><around|(|c|)>|)>-<around|(|2*<space|0.17em>w<rsub|k><around|(|c|)>+7|)>*<around|(|w<rsub|k><around|(|c|)>+4|)>>|<cell|>|<cell|=-<around|(|2*<space|0.17em>w<rsub|k><around|(|c|)><rsup|2>+14*<space|0.17em>w<rsub|k><around|(|c|)>+27|)><eq-number>>>>>>
  </proof>

  <\theorem>
    [Exact Gram sequence via Lagrange\UBürmann
    inversion]<label|thm:lagrange>Define the correction function
    <math|\<eta\><rsub|k><around|(|c|)>=\<varphi\><space|-0.17em><around*|(|\<Psi\><around|(|c,<space|0.17em>k|)>|)>>.
    The exact solution to<nbsp><eqref|eq:gram-def> is

    <\equation>
      g<rsub|n><rsup|<around|(|k|)>>=<big|sum><rsub|j=0><rsup|\<infty\>><frac|<around|(|-1|)><rsup|j>|j!>*<space|0.17em><frac|d<rsup|<space|0.17em>j-1>|d*c<rsup|<space|0.17em>j-1>>*<space|-0.17em><around*|[|\<partial\><rsub|c>*<space|0.17em>\<Psi\><around|(|c,<space|0.17em>k|)>\<cdot\>\<eta\><rsub|k><around|(|c|)><rsup|j>|]><rsub|c<space|0.17em>=<space|0.17em>\<pi\>*<around|(|n+<frac|1|8>|)>><label|eq:lagrange>
    </equation>

    where <math|<frac|d<rsup|-1>|d*c<rsup|-1>>> at <math|j=0> denotes the
    identity operator, all derivatives of <math|\<Psi\>> are given
    by<nbsp><eqref|eq:Psi-deriv>, and <math|\<partial\><rsub|c>*<space|0.17em>\<Psi\><around|(|c,k|)>=2/<around|(|1+w<rsub|k><around|(|c|)>|)>>.
  </theorem>

  <\proof>
    The Gram equation <math|f<around|(|t|)>=c-\<varphi\><around|(|t|)>>
    with<nbsp><eqref|eq:Psi-inverse> gives the fixed-point equation

    <\equation>
      t=\<Psi\><space|-0.17em><around*|(|c-\<varphi\><around|(|t|)>,<space|0.27em>k|\<nobracket\>>.<label|eq:fixed-point>
    </equation>

    By the Lagrange\UBürmann theorem (Whittaker\UWatson, Ÿ7.32): if
    <math|t=\<Psi\><around|(|c-\<varphi\><around|(|t|)>,<space|0.17em>k|)>>
    and <math|t<rsub|0>=\<Psi\><around|(|c,k|)>>, then for any analytic
    <math|F>,

    <\equation>
      F<around|(|t|)>=F<around|(|t<rsub|0>|)>+<big|sum><rsub|n=1><rsup|\<infty\>><frac|<around|(|-1|)><rsup|n>|n!>*<space|0.17em><frac|d<rsup|<space|0.17em>n-1>|d*c<rsup|<space|0.17em>n-1>>*<space|-0.17em><around*|[|F<rprime|'><around|(|t<rsub|0>|)>*<space|0.27em>\<partial\><rsub|c>*\<Psi\><around|(|c,<space|0.17em>k|)>*<space|0.27em>\<eta\><rsub|k><around|(|c|)><rsup|n>|]>
    </equation>

    Taking <math|F> to be the identity (<math|F<around|(|t|)>=t>,
    <math|F<rprime|'>=1>) gives<nbsp><eqref|eq:lagrange>.

    Convergence: the nearest singularity of
    <math|\<Psi\><around|(|<space|0.17em>\<cdummy\><space|0.17em>,k|)>> in
    the complex <math|c>-plane is the branch point of <math|W<rsub|0>> at
    <math|c=-a<rsub|k>/e>, giving convergence radius
    <math|<around|\||\<pi\>*<around|(|n+<tfrac|1|8>|)>+a<rsub|k>/e|\|>\<gtr\>\<pi\>*<around|(|n+<tfrac|1|8>|)>>
    for <math|n\<ge\>0>. Since <math|<around|\||\<eta\><rsub|k><around|(|c|)>|\|>=<around|\||\<varphi\><around|(|\<Psi\><around|(|c,k|)>|)>|\|>=O<around|(|c<rsup|-1>|)>>
    while this radius grows linearly in <math|c>, the series converges for
    all <math|n\<ge\>0>.
  </proof>

  <\corollary>
    [First correction term and second-order structure]<label|cor:corrections>

    <\equation>
      g<rsub|n><rsup|<around|(|k|)>>=\<Psi\><space|-0.17em><around*|(|\<pi\>*<around|(|n+<tfrac|1|8>|)>,<space|0.17em>k|)>-<frac|2*<space|0.17em>\<eta\><rsub|k>*<space|-0.17em><around*|(|\<pi\>*<around|(|n+<tfrac|1|8>|)>|)>|1+w<rsub|k>*<space|-0.17em><around*|(|\<pi\>*<around|(|n+<tfrac|1|8>|)>|)>>+<frac|1|2>*<frac|d|d*c><space|-0.17em><around*|[|<frac|2*<space|0.17em>\<eta\><rsub|k><around|(|c|)><rsup|2>|1+w<rsub|k><around|(|c|)>>|]><rsub|c<space|0.17em>=<space|0.17em>\<pi\>*<around|(|n+<frac|1|8>|)>>+O<space|-0.17em><around*|(|\<eta\><rsub|k>*<space|-0.17em><around*|(|\<pi\>*<around|(|n+<tfrac|1|8>|)>|)><rsup|3>|)><label|eq:two-terms>
    </equation>

    The <math|j=2> derivative expands via the product rule to

    <\equation>
      <frac|1|2>*<frac|d|d*c><space|-0.17em><around*|[|<frac|2*<space|0.17em>\<eta\><rsub|k><around|(|c|)><rsup|2>|1+w<rsub|k><around|(|c|)>>|]>=-<frac|e<rsup|-w<rsub|k><around|(|c|)>>*<space|0.27em>\<eta\><rsub|k><around|(|c|)><rsup|2>|a<rsub|k>*<space|0.17em><around*|(|1+w<rsub|k><around|(|c|)>|)><rsup|3>>+<frac|4*<space|0.27em>\<eta\><rsub|k><around|(|c|)>*<space|0.27em>\<varphi\><rprime|'><space|-0.17em><around*|(|\<Psi\><around|(|c,<space|0.17em>k|)>|)>|<around*|(|1+w<rsub|k><around|(|c|)>|)><rsup|2>><label|eq:j2-expanded>
    </equation>

    where <math|\<varphi\><rprime|'><around|(|t|)>=<frac|d|d*t>*\<varphi\><around|(|t|)>>.
    Both summands in<nbsp><eqref|eq:j2-expanded> are
    <math|O<space|-0.17em><around*|(|\<eta\><rsub|k><around|(|c|)><space|0.17em>/<space|0.17em>\<Psi\><around|(|c,k|)>|)>>
    and contribute at the same asymptotic order.
  </corollary>

  <\proof>
    The <math|j=0> term of<nbsp><eqref|eq:lagrange> gives
    <math|\<Psi\><space|-0.17em><around*|(|\<pi\>*<around|(|n+<tfrac|1|8>|)>,k|)>>.
    The <math|j=1> term gives <math|-\<partial\><rsub|c>*\<Psi\><around|(|c,k|)>\<cdot\>\<eta\><rsub|k><around|(|c|)>=-2*<space|0.17em>\<eta\><rsub|k><around|(|c|)>/<around|(|1+w<rsub|k><around|(|c|)>|)>>.
    The <math|j=2> term is <math|<tfrac|1|2><space|0.17em><frac|d|d*c>*<around|[|\<partial\><rsub|c>*\<Psi\><around|(|c,k|)>\<cdot\>\<eta\><rsub|k><around|(|c|)><rsup|2>|]>>.
    By the product rule:

    <\equation>
      <frac|1|2>*<frac|d|d*c><space|-0.17em><around*|[|<frac|2*<space|0.17em>\<eta\><rsub|k><around|(|c|)><rsup|2>|1+w<rsub|k><around|(|c|)>>|]>=<frac|1|2>*<space|0.27em>\<partial\><rsub|c><rsup|2>*\<Psi\><around|(|c,k|)>*<space|0.27em>\<eta\><rsub|k><around|(|c|)><rsup|2>+\<partial\><rsub|c>*\<Psi\><around|(|c,k|)>*<space|0.27em>\<eta\><rsub|k><around|(|c|)>*<space|0.27em>\<eta\><rsub|k><rprime|'><around|(|c|)>.
    </equation>

    From Theorem<nbsp><reference|thm:derivatives> at <math|j=2>:
    <math|\<partial\><rsub|c><rsup|2>*\<Psi\><around|(|c,k|)>=-2*<space|0.17em>e<rsup|-w<rsub|k><around|(|c|)>><space|0.17em>/<space|0.17em><around*|(|a<rsub|k>*<space|0.17em><around|(|1+w<rsub|k><around|(|c|)>|)><rsup|3>|)>>.
    The chain rule gives <math|\<eta\><rsub|k><rprime|'><around|(|c|)>=\<varphi\><rprime|'><around|(|\<Psi\><around|(|c,k|)>|)>\<cdot\>\<partial\><rsub|c>*\<Psi\><around|(|c,k|)>=2*<space|0.17em>\<varphi\><rprime|'><around|(|\<Psi\><around|(|c,k|)>|)><space|0.17em>/<space|0.17em><around|(|1+w<rsub|k><around|(|c|)>|)>>.
    Substituting:

    <\equation>
      <frac|1|2><space|-0.17em><around*|(|<space|-0.17em><frac|-2*<space|0.17em>e<rsup|-w<rsub|k><around|(|c|)>>|a<rsub|k>*<around|(|1+w<rsub|k><around|(|c|)>|)><rsup|3>>|)>*\<eta\><rsub|k><around|(|c|)><rsup|2><space|0.27em>+<space|0.27em><frac|2|1+w<rsub|k><around|(|c|)>>\<cdot\>\<eta\><rsub|k><around|(|c|)>\<cdot\><frac|2*<space|0.17em>\<varphi\><rprime|'><around|(|\<Psi\><around|(|c,k|)>|)>|1+w<rsub|k><around|(|c|)>>
    </equation>

    yields<nbsp><eqref|eq:j2-expanded>.
  </proof>

  <\corollary>
    [Explicit <math|k>-th level sequence]<label|cor:Xk>The <math|k>-th level
    sequence\ 

    <\equation>
      X<rsub|k><around|(|n|)>=n*\<pi\>-g<rsub|n><rsup|<around|(|k-1|)>>
    </equation>

    \ is

    <\equation>
      X<rsub|k><around|(|n|)>=n*\<pi\>-<big|sum><rsub|j=0><rsup|\<infty\>><frac|<around|(|-1|)><rsup|j>|j!>*<space|0.17em><frac|d<rsup|<space|0.17em>j-1>|d*c<rsup|<space|0.17em>j-1>><space|-0.17em><around*|(|<frac|2*<space|0.27em>\<eta\><rsub|k-1><around|(|\<pi\><around|(|n+<frac|1|8>|)>|)><rsup|j>|1+w<rsub|k-1><around|(|\<pi\><around|(|n+<frac|1|8>|)>|)>>|)><label|eq:Xk-full>
    </equation>

    with

    <\equation>
      w<rsub|k-1><around|(|c|)>=W<rsub|0>*<space|-0.17em><around*|(|<frac|c|\<pi\>>*<space|0.17em>e<rsup|-<around|(|2*k-1|)>>|)>
    </equation>

    \ and

    <\equation>
      \<eta\><rsub|k-1><around|(|c|)>=\<varphi\><space|-0.17em><around*|(|\<Psi\><around|(|c,<space|0.17em>k-1|)>|)>
    </equation>

    For <math|k=1>, through first-order correction:

    <\equation>
      X<rsub|1><around|(|n|)>=n*\<pi\>-<frac|2*\<pi\>*<around|(|n+<tfrac|1|8>|)>|W<rsub|0>*<space|-0.17em><around*|(|<around|(|n+<tfrac|1|8>|)>/e|)>>+<frac|2*<space|0.27em>\<varphi\><space|-0.17em><around*|(|\<Psi\><around|(|\<pi\>*<around|(|n+<tfrac|1|8>|)>|)>|)>|1+W<rsub|0>*<space|-0.17em><around*|(|<around|(|n+<tfrac|1|8>|)>/e|)>>+O<space|-0.17em><around*|(|\<varphi\><rsup|2>|)><label|eq:X1-explicit>
    </equation>
  </corollary>

  <\proof>
    Substitute<nbsp><eqref|eq:lagrange> with <math|k> replaced by <math|k-1>
    into<nbsp><eqref|eq:Xk-explicit>.
  </proof>

  <\remark>
    The polynomials <math|p<rsub|j>> in<nbsp><eqref|eq:pj-recurrence> depend
    only on <math|w<rsub|k><around|(|c|)>> and not on <math|k>. The factor
    <math|e<rsup|-<around|(|j-1|)>*w<rsub|k><around|(|c|)>>>
    in<nbsp><eqref|eq:Psi-deriv> introduces
    <math|w<rsub|k><around|(|c|)>>-dependence beyond the polynomial, so the
    full <math|j>-th derivative is not purely a rational function of
    <math|w<rsub|k><around|(|c|)>> and <math|1+w<rsub|k><around|(|c|)>>. The
    dependence on the level <math|k> enters through the argument of
    <math|W<rsub|0>>: replacing <math|k> by <math|k+1> multiplies the
    argument by <math|e<rsup|-2>>. Every level of the hierarchy is generated
    by the same algebraic structure\V<eqref|eq:pj-recurrence> and
    <math|\<Psi\>>\Vevaluated at a geometrically rescaled argument of
    <math|W<rsub|0>>.
  </remark>
</body>

<\initial>
  <\collection>
    <associate|magnification|1.1>
    <associate|page-height|auto>
    <associate|page-medium|paper>
    <associate|page-type|letter>
    <associate|page-width|auto>
  </collection>
</initial>

<\references>
  <\collection>
    <associate|auto-1|<tuple|1|1|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|auto-2|<tuple|2|2|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|auto-3|<tuple|3|4|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|cor:Xk|<tuple|13|7|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|cor:corrections|<tuple|12|6|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|def:Psi|<tuple|6|2|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:Psi-def|<tuple|8|2|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:Psi-deriv|<tuple|23|4|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:Psi-inverse|<tuple|14|3|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:X1-explicit|<tuple|52|7|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:Xk-def|<tuple|7|2|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:Xk-explicit|<tuple|9|2|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:Xk-full|<tuple|49|7|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:dw-dc|<tuple|31|4|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:f-def|<tuple|13|3|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:fixed-point|<tuple|42|6|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:gram-def|<tuple|6|2|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:induction-calc|<tuple|25|5|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:j2-expanded|<tuple|45|6|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:lagrange|<tuple|41|5|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:leading|<tuple|15|3|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:phi-asymp|<tuple|5|2|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:phi-exact|<tuple|3|2|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:pj-recurrence|<tuple|24|4|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:pj-values|<tuple|26|4|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:psi-def|<tuple|2|1|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:theta-decomp|<tuple|4|2|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:theta-def|<tuple|1|1|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|eq:two-terms|<tuple|44|6|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|thm:Xk|<tuple|7|2|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|thm:derivatives|<tuple|10|4|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|thm:lagrange|<tuple|11|5|../.TeXmacs/texts/scratch/no_name_3.tm>>
    <associate|thm:leading|<tuple|8|3|../.TeXmacs/texts/scratch/no_name_3.tm>>
  </collection>
</references>

<\auxiliary>
  <\collection>
    <\associate|toc>
      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|1<space|2spc>Definitions
      and Setup> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-1><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|2<space|2spc>The
      Explicit Gram Sequence> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-2><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|3<space|2spc>The
      Lambert <with|mode|<quote|math>|W> Generator for All Corrections>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-3><vspace|0.5fn>
    </associate>
  </collection>
</auxiliary>