package arb.expressions.nodes.unary;

import static arb.expressions.Compiler.loadInput;
import static org.objectweb.asm.Opcodes.GOTO;

import java.util.TreeMap;
import java.util.stream.Collectors;

import org.objectweb.asm.*;

import arb.Integer;
import arb.expressions.Compiler;
import arb.expressions.Expression;
import arb.expressions.nodes.Node;
import arb.functions.Function;

/**
 * The {@link When} class represents a {@link Node} in the {@link Expression}
 * that is generated by the {@link Expression#parseWhen(int)} function when the
 * 'when' "function" is encountered. It's syntax is like this:
 * <code>Function&lt;Integer,Real> f = Function.express(Real.class,Integer.class,"when(n=0,1,n=1,tanh(ln(x)),else,-1)", context);</code>
 * <br>
 * <br>
 * arb4j is made available under the terms of the Business Source License™ v1.1
 * ©2024 which can be found in the root directory of this project in a file
 * named License.pdf, License.txt, or License.tm which are the pdf, text, and
 * TeXmacs formatted versions of the same document respectively.
 */
public class When<D, R, F extends Function<D, R>> extends
                 UnaryOperation<D, R, F>
{

  @Override
  public MethodVisitor generate(MethodVisitor mv, Class<?> resultType)
  {
    assert expression.domainType.equals(Integer.class) : String.format("expression.domain = %s != Integer, the only type supported presently\n",
                                                                       expression.domainType);
    try
    {
      mv.visitCode();

      cases.forEach((key, val) ->
      {
        val.isResult = isResult;
      });
      arg.isResult = isResult;

      Label   endSwitch    = new Label();
      Label   defaultLabel = new Label();
      Label[] labels       = cases.entrySet()
                                  .stream()
                                  .map(entry -> new Label())
                                  .collect(Collectors.toList())
                                  .toArray(new Label[cases.size()]);

      Compiler.checkClassCast(loadInput(mv), expression.domainType);
      mv.visitMethodInsn(Opcodes.INVOKEVIRTUAL,
                         Type.getInternalName(Integer.class),
                         "getSignedValue",
                         Type.getMethodDescriptor(Type.getType(int.class)),
                         false);
      mv.visitTableSwitchInsn(0, cases.size() - 1, defaultLabel, labels);
      var branches = cases.entrySet().stream().collect(Collectors.toList());

      for (int i = 0; i < labels.length; i++)
      {
        mv.visitLabel(labels[i]);
        branches.get(i).getValue().generate(mv, expression.rangeType);
        mv.visitJumpInsn(GOTO, endSwitch);
      }

      mv.visitLabel(defaultLabel);
      super.generate(mv, resultType);
      mv.visitLabel(endSwitch);

    }
    finally
    {
      mv.visitEnd();

    }

    return mv;
  }

  @Override
  public String toString()
  {
    return String.format("When[cases=%s,default=%s]", cases, arg);
  }

  public TreeMap<Integer, Node<D, R, F>> cases;

  public When(Node<D, R, F> node, Expression<D, R, F> expression, int depth)
  {
    super(node,
          expression,
          depth);
  }

  public When(Expression<D, R, F> expression,
              TreeMap<Integer, Node<D, R, F>> cases,
              Node<D, R, F> defaultValue,
              int depth)
  {
    super(defaultValue,
          expression,
          depth);
    this.cases = cases;
  }

  @Override
  public String typeset()
  {
    return "when";
  }

  @Override
  public Class<?> type()
  {
    return expression.rangeType;
  }

}
