package arb.expressions.nodes.unary;

import java.util.TreeMap;

import org.objectweb.asm.MethodVisitor;

import arb.Integer;
import arb.expressions.Expression;
import arb.expressions.nodes.Node;
import arb.functions.Function;

/**
 * The {@link When} class represents a {@link Node} in the {@link Expression}
 * that is generated by the {@link Expression#parseWhen(int)} function when the
 * 'when' "function" is encountered. It's syntax is like this:
 * <code>Function&lt;Integer,Real> f = Function.express(Real.class,Integer.class,"when(n=0,1,n=1,tanh(ln(x)),else,-1)", context);</code>
 * <br>
 * <br>
 * arb4j is made available under the terms of the Business Source License™ v1.1
 * ©2024 which can be found in the root directory of this project in a file
 * named License.pdf, License.txt, or License.tm which are the pdf, text, and
 * TeXmacs formatted versions of the same document respectively.
 */
public class When<D, R, F extends Function<D, R>> extends
                 UnaryOperation<D, R, F>
{

  @Override
  public MethodVisitor generate(MethodVisitor mv, Class<?> resultType)
  {
    for (var entry : cases.entrySet())
    {
      System.out.println("case " + entry.getKey() + " -> " + entry.getValue());
    }
    System.out.println("default -> " + arg);
    assert false : "TODO: generate code to handle the cases and then return super.generate if none of the cases match the ones specified, this calls arg.generate where arg is the defaultValue defined by the expression that comes after the else statement";
    return super.generate(mv, resultType);
  }

  @Override
  public String toString()
  {
    return String.format("When[cases=%s,default=%s]", cases, arg);
  }

  public TreeMap<Integer, Node<D, R, F>> cases;

  public When(Node<D, R, F> node, Expression<D, R, F> expression, int depth)
  {
    super(node,
          expression,
          depth);
  }

  public When(Expression<D, R, F> expression,
              TreeMap<Integer, Node<D, R, F>> cases,
              Node<D, R, F> defaultValue,
              int depth)
  {
    super(defaultValue,
          expression,
          depth);
    this.cases = cases;
  }

  @Override
  public String typeset()
  {
    return "when";
  }

  @Override
  public Class<?> type()
  {
    return expression.rangeType;
  }

}
