<TeXmacs|2.1.4>

<style|generic>

<\body>
  <doc-data|<doc-title|On the Prediction of Non-Stationary
  Processes>|<doc-author|<author-data|<author-name|N. A.
  Abdrabbo>|<\author-affiliation>
    University of Manchester

    Received August 1966. Revised January 1967
  </author-affiliation>>>|<doc-author|<author-data|<author-name|M. B.
  Priestley>|<\author-affiliation>
    University of Manchester

    Received August 1966. Revised January 1967
  </author-affiliation>>>|<doc-title-options|cluster-all>>

  <abstract-data|<\abstract>
    The problem of linear least-squares prediction for a class of
    non-stationary processes which possess ``evolutionary spectral
    representations'' is considered. It is shown that, under certain
    conditions, such processes admit moving-average representations in terms
    of time-dependent coefficients. This feature enables development of a
    close analogue of the Wiener-Kolmogorov approach to the corresponding
    problem for stationary processes.
  </abstract>>

  <section|Introduction><label|sec:introduction>

  The Wiener-Kolmogorov \Plinear least-squares\Q approach to the prediction
  and filtering of stationary processes is now well established, and may, in
  principle, be applied to any practical problem involving stationary
  processes whose second-order properties are known. Accounts of this theory
  have been written at various levels of mathematical rigour (see, for
  example, <cite|Doob1953>, <cite|Bartlett1955>, <cite|Grenander1957>,
  <cite|Yaglom1962>, <cite|Whittle1965>). However, the corresponding problem
  for non-stationary processes has received little attention. There have been
  a few isolated attempts to deal with this topic, but in the main the
  approaches have been either too general or too restricted to be useful in
  practical applications. For example, <cite|Parzen1961> has solved the
  non-stationary prediction problem in principle, but the approach is
  somewhat abstract, and the \Psolution\Q for the optimum predictor is
  expressed as a certain inner-product in a Hilbert space. <cite|Cramer1961a>
  considered the same problem, and obtained some interesting results in the
  form of \Pexistence theorems\Q, but did not present a method for
  determining the explicit form of a predictor in terms of the observed
  variables. Similar remarks apply to the work of <cite|Davis1952>. On the
  other hand, several papers written from an engineering standpoint have
  appeared (see, for example, <cite|Booton1952>, <cite|Zadeh1953>,
  <cite|Bendat1956>), but in most cases the \Pgeneral solution\Q stops with
  the construction of the well-known integral equation (cf.
  <eqref|eq:covariance_equation>) involving the covariance function of the
  process and the unknown \Pcoefficients\Q of the optimal predictor, the
  solution of which is obtainable only when the process obeys some very
  simple model. On a different level, <cite|Kalman1960> has studied
  multivariate non-stationary processes corresponding to dynamical systems
  which are governed by known linear differential equations, and has
  established some basic results regarding the analytic structure of optimal
  predictors for such models. However, from the point of view of practical
  application, the most useful results so far obtained are due to
  <cite|Whittle1965>, who considered non-stationary processes generated by
  autoregressive models with time-dependent coefficients, and obtained
  explicit recursive relations for the optimal predictors. In fact, some of
  the results for these particular models correspond very closely to those
  obtained by Whittle.

  The success of classical prediction theory for stationary processes is due
  essentially to the fact that such processes admit a spectral representation
  in terms of an orthogonal process. This feature not only simplifies the
  solution of the prediction problem, but also enables one to treat a general
  class of stationary processes by means of a \Pcanonical\Q representation,
  so that the discussion need not be restricted to particular models such as
  the autoregressive, moving-average, etc. Hitherto, the lack of a similar
  spectral representation for a general class of non-stationary processes has
  no doubt been one of the major stumbling blocks in attempts to generalize
  the classical theory. However, it turns out that the recently developed
  theory of evolutionary spectra representations <cite|Priestley1965>
  provides an ideal framework for the formulation and solution of
  non-stationary prediction problems. In fact, by using evolutionary spectral
  representations one obtains a prediction theory which is almost an exact
  parallel of the Wiener-Kolmogorov theory. The basic idea underlying this
  approach is the introduction of the evolutionary (i.e. time-dependent)
  spectrum of a non-stationary process, whose form completely determines the
  values of the coefficients of the optimal linear predictor. This means that
  even if observations from a process whose structure is completely unknown
  are presented, this prediction theory may still be usefully applied by
  first estimating the evolutionary spectrum (methods for estimating
  evolutionary spectra have been discussed by <cite|Priestley1965>,
  <cite|Priestley1966>). Of course, this estimation procedure introduces
  further complications which will not be discussed here (see also Section
  <reference|sec:discussion>). Throughout this paper it is assumed that the
  second-order properties of the process are known a priori. It should be
  pointed out, further, that in this account the aim is not at complete
  mathematical rigour; rather the aim is to show how this approach may be
  used to obtain explicit results for non-stationary processes.

  Before discussing the prediction problem, relevant parts of the theory of
  evolutionary spectra are summarized briefly.

  <section|Evolutionary Spectral Representations><label|sec:evolutionary_spectral>

  A class of continuous parameter processes,
  <math|<around|{|X<around|(|t|)>|}>>, with
  <math|E<around|{|X<around|(|t|)>|}>=0>,
  <math|E<around|{|X<rsup|2><around|(|t|)>|}>\<less\>\<infty\>>, for all
  <math|t>, is considered, for which there exists a family <math|\<cal-F\>>
  of functions <math|<around|{|\<phi\><rsub|t><around|(|\<omega\>|)>|}>>
  (defined on the real line and indexed by the suffix <math|t>) and a measure
  <math|\<mu\>> on the real line such that
  <math|<around|{|X<around|(|t|)>|}>> admits a spectral representation of the
  form

  <\equation>
    <label|eq:evolutionary_representation_continuous>X<around|(|t|)>=<big|int><rsub|-\<infty\>><rsup|\<infty\>>\<phi\><rsub|t><around|(|\<omega\>|)>*<space|0.17em>d*Z<around|(|\<omega\>|)>.
  </equation>

  (See also <cite|Granger1964>.) Here <math|<around|{|Z<around|(|\<omega\>|)>|}>>
  is an orthogonal process with <math|E<around*|[|<around|\||d*Z<around|(|\<omega\>|)>|\|><rsup|2>|]>=\<mu\>*<around|(|d*\<omega\>|)>>.
  If there exists a family <math|\<cal-F\>> for which each
  <math|\<phi\><rsub|t>> may be written in the form

  <\equation>
    <label|eq:oscillatory_condition>\<phi\><rsub|t><around|(|\<omega\>|)>=e<rsup|i*\<omega\>*t>*A<rsub|t><around|(|\<omega\>|)>,
  </equation>

  where, for each fixed <math|\<omega\>>, the generalized Fourier transform
  of <math|A<rsub|t><around|(|\<omega\>|)>> (considered as a function of
  <math|t>) has an absolute maximum at the origin, <math|X<around|(|t|)>> is
  termed an oscillatory process (cf. <cite|Priestley1965>), and the
  evolutionary spectrum at time <math|t> with respect to the family
  <math|\<cal-F\>> is defined by

  <\equation>
    <label|eq:evolutionary_spectrum_continuous>d*F<rsub|t><around|(|\<omega\>|)>=<mid|\|>A<rsub|t><around|(|\<omega\>|)><mid|\|><rsup|2>\<mu\>*<around|(|d*\<omega\>|)>*<space|1em><around|(|-\<infty\>\<less\>\<omega\>\<less\>\<infty\>|)>.
  </equation>

  For discrete parameter oscillatory processes (i.e. processes defined only
  for <math|t=0,\<pm\>1,\<pm\>2,\<ldots\>>) there is a corresponding
  evolutionary spectral representation

  <\equation>
    <label|eq:evolutionary_representation_discrete>X<around|(|t|)>=<big|int><rsub|-\<pi\>><rsup|\<pi\>>e<rsup|i*\<omega\>*t>*A<rsub|t><around|(|\<omega\>|)>*<space|0.17em>d*Z<around|(|\<omega\>|)>,
  </equation>

  and the evolutionary spectrum at time <math|t> with respect to the family
  <math|\<cal-F\>> is defined by

  <\equation>
    <label|eq:evolutionary_spectrum_discrete>d*F<rsub|t><around|(|\<omega\>|)>=<mid|\|>A<rsub|t><around|(|\<omega\>|)><mid|\|><rsup|2>\<mu\>*<around|(|d*\<omega\>|)>*<space|1em><around|(|-\<pi\>\<leqslant\>\<omega\>\<leqslant\>\<pi\>|)>.
  </equation>

  When the measure <math|\<mu\>> is absolutely continuous (with respect to
  Lebesgue measure) the derivative <math|F<rsub|t><rprime|'><around|(|\<omega\>|)>=f<rsub|t><around|(|\<omega\>|)>>
  exists for all <math|\<omega\>>, and is termed the evolutionary spectral
  density function at time <math|t>.

  In both the continuous and discrete cases the functions
  <math|A<rsub|t><around|(|\<omega\>|)>> may be normalized so that
  <math|A<rsub|0><around|(|\<omega\>|)>=1> for all <math|\<omega\>>. With
  this convention, <math|\<mu\>*<around|(|d*\<omega\>|)>=d*F<rsub|0><around|(|\<omega\>|)>>,
  the evolutionary spectrum at time zero.

  <section|Moving-Average Representations for Oscillatory
  Processes><label|sec:moving_average>

  As in the prediction theory of stationary processes, the construction
  begins with a one-sided moving-average representation for a class of
  oscillatory processes, the distinction with the stationary case being that
  the coefficients in the moving-average scheme are now time-dependent.

  <subsection|Discrete-parameter Processes><label|subsec:discrete_moving_average>

  Suppose that <math|X<around|(|t|)>> has a representation of the form
  <eqref|eq:evolutionary_representation_discrete>, and that <math|\<mu\>> is
  absolutely continuous with respect to <math|d*\<omega\>>. Then
  <math|f<rsub|t><around|(|\<omega\>|)>> may be written in the form

  <\equation>
    <label|eq:moving_average_density>f<rsub|t><around|(|\<omega\>|)>=<mid|\|>A<rsub|t><around|(|\<omega\>|)><mid|\|><rsup|2>f<around|(|\<omega\>|)>,
  </equation>

  where <math|f<around|(|\<omega\>|)>=d*\<mu\>/d*\<omega\>>. Note that
  <math|f<around|(|\<omega\>|)>=f<rsub|0><around|(|\<omega\>|)>> must be
  integrable. Suppose now that

  <\equation>
    <label|eq:condition_C1><big|int><rsub|-\<pi\>><rsup|\<pi\>>log
    f<around|(|\<omega\>|)>*<space|0.17em>d*\<omega\>\<gtr\>-\<infty\>.
  </equation>

  Then it follows that <cite-parenthesized|Doob1953> there exists a function
  <math|\<psi\><around|(|\<omega\>|)>> such that

  <\equation>
    <label|eq:psi_squared><around|\||\<psi\><around|(|\<omega\>|)>|\|><rsup|2>=f<around|(|\<omega\>|)>,
  </equation>

  where <math|\<psi\><around|(|z|)>>, considered as a function of the complex
  variable <math|z=e<rsup|i*\<omega\>>>, has no poles or zeros inside the
  unit circle <math|<around|\||z|\|>\<less\>1>. The function
  <math|\<psi\><around|(|\<omega\>|)>> may be written as a one-sided Fourier
  transform, viz.

  <\equation>
    <label|eq:psi_fourier>\<psi\><around|(|\<omega\>|)>=<big|sum><rsub|u=0><rsup|\<infty\>>e<rsup|-i*\<omega\>*u>*g<rsup|\<ast\>><around|(|u|)>,
  </equation>

  for some suitable sequence <math|<around|{|g<rsup|\<ast\>><around|(|u|)>|}>>.

  Suppose further that:

  <\enumerate>
    <item><label|eq:condition_C2> The family <math|\<cal-F\>> can be chosen
    so that, for each <math|t>, <math|A<rsub|t><around|(|z|)>> (considered as
    a function of <math|z>) also has no poles or zeros inside the unit
    circle, so that, for each <math|t>, <math|A<rsub|t><around|(|\<omega\>|)>>
    may be written in the form,

    <\equation>
      <label|eq:A_t_fourier>A<rsub|t><around|(|\<omega\>|)>=<big|sum><rsub|u=0><rsup|\<infty\>>e<rsup|-i*\<omega\>*u>*g<rsub|t><around|(|u|)>.
    </equation>
  </enumerate>

  (It is remarked that <math|A<rsub|t><around|(|\<omega\>|)>> is certainly
  square-integrable, since <math|<mid|\|>A<rsub|t><around|(|\<omega\>|)><mid|\|><rsup|2>f<around|(|\<omega\>|)>=f<rsub|t><around|(|\<omega\>|)>>
  is integrable, and by condition <eqref|eq:condition_C1>,
  <math|f<around|(|\<omega\>|)>> may vanish on at most a set of zero
  measure.)

  Note that a necessary condition for the validity of <eqref|eq:A_t_fourier>
  is

  <\equation>
    <label|eq:condition_C3><big|int><rsub|-\<pi\>><rsup|\<pi\>>log
    <mid|\|>A<rsub|t><around|(|\<omega\>|)><mid|\|><rsup|2><space|0.17em>d*\<omega\>\<gtr\>-\<infty\>,
  </equation>

  for all <math|t>. Now write <math|X<around|(|t|)>> in the form

  <\equation>
    <label|eq:X_t_representation>X<around|(|t|)>=<big|int><rsub|-\<pi\>><rsup|\<pi\>>e<rsup|i*t*\<omega\>>*\<alpha\><rsub|t><around|(|\<omega\>|)>*<space|0.17em>d*z<around|(|\<omega\>|)>,
  </equation>

  where <math|\<alpha\><rsub|t><around|(|\<omega\>|)>=A<rsub|t><around|(|\<omega\>|)>*\<psi\><around|(|\<omega\>|)>>,
  so that

  <\equation>
    <label|eq:alpha_t_squared><mid|\|>\<alpha\><rsub|t><around|(|\<omega\>|)><mid|\|><rsup|2>=f<rsub|t><around|(|\<omega\>|)>,
  </equation>

  and <math|z<around|(|\<omega\>|)>> is an orthogonal process on
  <math|<around|(|-\<pi\>,\<pi\>|)>> with
  <math|E*<around|\||d*z<around|(|\<omega\>|)>|\|><rsup|2>=d*\<omega\>>.
  Since both <math|\<psi\><around|(|\<omega\>|)>> and
  <math|A<rsub|t><around|(|\<omega\>|)>> have one-sided Fourier transforms,
  it follows that, for each <math|t>, <math|\<alpha\><rsub|t><around|(|\<omega\>|)>>
  has a one-sided Fourier transform, i.e. one may write

  <\equation>
    <label|eq:alpha_t_fourier>\<alpha\><rsub|t><around|(|\<omega\>|)>=<big|sum><rsub|u=0><rsup|\<infty\>>e<rsup|-i*\<omega\>*u>*h<rsub|t><around|(|u|)>.
  </equation>

  Note that a necessary condition for the validity of
  <eqref|eq:alpha_t_fourier> is

  <\equation>
    <label|eq:condition_C4><big|int><rsub|-\<pi\>><rsup|\<pi\>>log
    f<rsub|t><around|(|\<omega\>|)>*<space|0.17em>d*\<omega\>\<gtr\>-\<infty\>,
  </equation>

  for each <math|t>. In fact, it is readily seen that <eqref|eq:condition_C1>
  and <eqref|eq:condition_C3><math|\<leftrightarrow\>><eqref|eq:condition_C4>,
  but whereas in the stationary case <eqref|eq:condition_C4> is both
  necessary and sufficient to ensure the validity of
  <eqref|eq:X_t_representation> and <eqref|eq:alpha_t_fourier>, sufficiency
  has not been proved in the non-stationary case. Condition
  <eqref|eq:condition_C4> implies that there exist functions
  <math|<around|{|\<alpha\><rsub|t><rsup|\<ast\>><around|(|\<omega\>|)>|}>>,
  say, satisfying <eqref|eq:alpha_t_fourier>, and such that, for each
  <math|t>, <math|f<rsub|t><around|(|\<omega\>|)>=<mid|\|>\<alpha\><rsub|t><rsup|\<ast\>><around|(|\<omega\>|)><mid|\|><rsup|2>>,
  so that <math|A<rsub|t><around|(|\<omega\>|)>=e<rsup|i*\<lambda\><around|(|t,\<omega\>|)>>*\<alpha\><rsub|t><rsup|\<ast\>><around|(|\<omega\>|)>/\<psi\><rsup|\<ast\>><around|(|\<omega\>|)>>,
  for some function <math|\<lambda\><around|(|t,\<omega\>|)>>. In the
  stationary case, <math|exp <around|{|i*\<lambda\><around|(|t,\<omega\>|)>|}>>,
  being independent of <math|t>, may be incorporated with
  <math|d*z<around|(|\<omega\>|)>>, and sufficiency follows. In the
  non-stationary case it would appear that further conditions are required.
  (It is interesting to note, however, that Cramer's result
  <cite-parenthesized|Cramer1961a> for the prediction of harmonizable
  processes has the same feature. That is, Cramer has proved only that when
  the spectrum of a harmonizable process satisfies a condition of the type
  <eqref|eq:condition_C4>, the process must be \Pdeterministic\Q, i.e. that
  in such cases a one-sided moving-average representation is not admissible.)

  Now define the process <math|<around|{|\<xi\><around|(|t|)>|}>> by

  <\equation>
    <label|eq:xi_process>\<xi\><around|(|t|)>=<big|int><rsub|-\<pi\>><rsup|\<pi\>>e<rsup|i*t*\<omega\>>*<space|0.17em>d*z<around|(|\<omega\>|)><space|1em><around|(|t=0,\<pm\>1,\<pm\>2,\<ldots\>|)>,
  </equation>

  so that <math|<around|{|\<xi\><around|(|t|)>|}>> is a stationary
  uncorrelated process, with

  <\equation>
    <label|eq:xi_properties><around*|\<nobracket\>|<tabular*|<tformat|<cwith|1|-1|1|1|cell-halign|c>|<cwith|1|-1|1|1|cell-lborder|0ln>|<cwith|1|-1|1|1|cell-rborder|0ln>|<table|<row|<cell|E<around|{|\<xi\><around|(|t|)>|}>=0*<space|1em><text|for
    all >t,>>|<row|<cell|E<around|{|<mid|\|>\<xi\><around|(|t|)><mid|\|><rsup|2>|}>=2*\<pi\>*<space|1em><text|for
    all >t,>>|<row|<cell|E*<around|{|\<xi\><around|(|t|)>*\<xi\><rsup|\<ast\>><around|(|s|)>|}>=0*<space|1em><around|(|t\<neq\>s|)>.>>>>>|}>
  </equation>

  It now follows from <eqref|eq:X_t_representation> and
  <eqref|eq:alpha_t_fourier> that <math|X<around|(|t|)>> may be written

  <\equation>
    <label|eq:moving_average_discrete>X<around|(|t|)>=<big|sum><rsub|u=0><rsup|\<infty\>>h<rsub|t><around|(|u|)>*<space|0.17em>\<xi\>*<around|(|t-u|)>,
  </equation>

  the above expression existing as a mean-square limit in virtue of the
  condition

  <\equation>
    <label|eq:variance_condition>2*\<pi\>*<big|sum><rsub|u=0><rsup|\<infty\>>h<rsub|t><rsup|2><around|(|u|)>=<big|int><rsub|-\<pi\>><rsup|\<pi\>><mid|\|>\<alpha\><rsub|t><around|(|\<omega\>|)><mid|\|><rsup|2><space|0.17em>d*\<omega\>=<big|int><rsub|-\<pi\>><rsup|\<pi\>>f<rsub|t><around|(|\<omega\>|)>*<space|0.17em>d*\<omega\>=<math-up|var><around|{|X<around|(|t|)>|}>\<less\>\<infty\>.
  </equation>

  <\theorem>
    <label|thm:moving_average_discrete>Let
    <math|<around|{|X<around|(|t|)>|}>> be a discrete-parameter oscillatory
    process. If there exists a family <math|\<cal-F\>> satisfying condition
    <eqref|eq:condition_C2>, and with respect to which
    <math|<around|{|X<around|(|t|)>|}>> has an absolutely continuous
    evolutionary spectrum satisfying condition <eqref|eq:condition_C4>, then
    <math|<around|{|X<around|(|t|)>|}>> may be represented as a one-sided
    moving average process of the form <eqref|eq:moving_average_discrete>.
    Conversely, if <math|<around|{|X<around|(|t|)>|}>> has a one-sided moving
    average representation of the form <eqref|eq:moving_average_discrete>,
    condition <eqref|eq:condition_C4> must be satisfied.
  </theorem>

  <\proof>
    The proof follows from the construction above and the conditions ensuring
    the validity of the Fourier representations.
  </proof>

  <subsection|Continuous-parameter Processes><label|subsec:continuous_moving_average>

  As in the case of stationary processes (see <cite|Whittle1963>), the
  results for discrete parameter processes can readily be adapted to the
  continuous case. The measure <math|\<mu\>> is again assumed to be
  absolutely continuous (with respect to Lebesgue measure) and, in place of
  <eqref|eq:condition_C1>, it is assumed that (using the same notation as in
  <eqref|eq:moving_average_density>)

  <\equation>
    <label|eq:continuous_condition_C1_star><big|int><rsub|-\<infty\>><rsup|\<infty\>><frac|log
    f<around|(|\<omega\>|)>|1+\<omega\><rsup|2>>*<space|0.17em>d*\<omega\>\<gtr\>-\<infty\>.
  </equation>

  Then there exists a function <math|\<psi\><around|(|\<omega\>|)>> such that
  <math|<around|\||\<psi\><around|(|\<omega\>|)>|\|><rsup|2>=f<around|(|\<omega\>|)>>,
  with <math|\<psi\><around|(|z|)>> having no poles or zeros in the lower
  half-plane. The function <math|\<psi\><around|(|\<omega\>|)>> may now be
  written as a one-sided Fourier integral. Corresponding to
  <eqref|eq:condition_C2> it is assumed now that, for each <math|t>,
  <math|A<rsub|t><around|(|\<omega\>|)>> may be written in the form

  <\equation>
    <label|eq:continuous_A_t_fourier>A<rsub|t><around|(|\<omega\>|)>=<big|int><rsub|0><rsup|\<infty\>>e<rsup|-i*\<omega\>*u>*g<rsub|t><around|(|u|)>*<space|0.17em>d*u,
  </equation>

  a necessary condition being

  <\equation>
    <label|eq:condition_C3_star><big|int><rsub|-\<infty\>><rsup|\<infty\>><frac|log
    <mid|\|>A<rsub|t><around|(|\<omega\>|)><mid|\|><rsup|2>|1+\<omega\><rsup|2>>*<space|0.17em>d*\<omega\>\<gtr\>-\<infty\>,
  </equation>

  for all <math|t>. It then follows that <math|X<around|(|t|)>> may be
  written in the form

  <\equation>
    <label|eq:X_t_continuous_representation>X<around|(|t|)>=<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*t*\<omega\>>*\<alpha\><rsub|t><around|(|\<omega\>|)>*<space|0.17em>d*z<around|(|\<omega\>|)>,
  </equation>

  where <math|z<around|(|\<omega\>|)>> is an orthogonal process on
  <math|<around|(|-\<infty\>,\<infty\>|)>>, with
  <math|E<around*|[|<around|\||d*z<around|(|\<omega\>|)>|\|><rsup|2>|]>=d*\<omega\>>,
  and <math|\<alpha\><rsub|t><around|(|\<omega\>|)>> has a one-sided Fourier
  integral representation of the form

  <\equation>
    <label|eq:alpha_t_continuous_fourier>\<alpha\><rsub|t><around|(|\<omega\>|)>=<big|int><rsub|0><rsup|\<infty\>>e<rsup|-i*\<omega\>*u>*h<rsub|t><around|(|u|)>*<space|0.17em>d*u,
  </equation>

  with

  <\equation>
    <mid|\|>\<alpha\><rsub|t><around|(|\<omega\>|)><mid|\|><rsup|2>=f<rsub|t><around|(|\<omega\>|)>
  </equation>

  . Corresponding to <eqref|eq:condition_C4>, a necessary condition for the
  validity of <eqref|eq:alpha_t_continuous_fourier> is

  <\equation>
    <label|eq:condition_C4_star><big|int><rsub|-\<infty\>><rsup|\<infty\>><frac|log
    f<rsub|t><around|(|\<omega\>|)>|1+\<omega\><rsup|2>>*<space|0.17em>d*\<omega\>=<big|int><rsub|-\<infty\>><rsup|\<infty\>><frac|log<mid|\|>\<alpha\><rsub|t><around|(|\<omega\>|)><mid|\|><rsup|2>|1+\<omega\><rsup|2>>*<space|0.17em>d*\<omega\>=<big|int><rsub|-\<infty\>><rsup|\<infty\>><frac|log<mid|\|><big|int><rsub|0><rsup|\<infty\>>e<rsup|-i*\<omega\>*u>*h<rsub|t><around|(|u|)>*<space|0.17em>d*u<mid|\|><rsup|2>|1+\<omega\><rsup|2>>d*\<omega\>\<gtr\>-\<infty\>,
  </equation>

  for all <math|t>. In the continuous case there are analytic difficulties in
  constructing an analogue of the uncorrelated process
  <math|<around|{|\<xi\><around|(|t|)>|}>> (see <cite|Whittle1963>,
  p.<nbsp>21). However, one may formally define the process
  <math|\<xi\><around|(|t|)>> by

  <\equation>
    <label|eq:xi_continuous_process>\<xi\><around|(|t|)>=<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*\<omega\>*t>*<space|0.17em>d*z<around|(|\<omega\>|)>,
  </equation>

  (so that <math|\<xi\><around|(|t|)>> may be interpreted as the
  \Pderivative\Q of a Wiener process), so that

  <\equation>
    <label|eq:xi_continuous_properties><around*|\<nobracket\>|<tabular*|<tformat|<cwith|1|-1|1|1|cell-halign|c>|<cwith|1|-1|1|1|cell-lborder|0ln>|<cwith|1|-1|1|1|cell-rborder|0ln>|<table|<row|<cell|E<around|{|\<xi\><around|(|t|)>|}>=0*<space|1em><text|for
    all >t,>>|<row|<cell|E*<around|{|<mid|\|>d*\<xi\><around|(|t|)><mid|\|><rsup|2>|}>=2*\<pi\>*<space|0.17em>d*t,>>|<row|<cell|E*<around|{|d*\<xi\><around|(|t|)>*d*\<xi\><rsup|\<ast\>><around|(|s|)>|}>=0*<space|1em><around|(|s\<neq\>t|)>.>>>>>|}>
  </equation>

  Then formally one may write <math|X<around|(|t|)>> in the form

  <\equation>
    <label|eq:X_t_continuous_moving_average>X<around|(|t|)>=<big|int><rsub|0><rsup|\<infty\>>h<rsub|t><around|(|u|)>*<space|0.17em>\<xi\>*<around|(|t-u|)>*<space|0.17em>d*u,
  </equation>

  or, more precisely,

  <\equation>
    <label|eq:X_t_continuous_integral>X<around|(|t|)>=<big|int><rsub|0><rsup|\<infty\>>h<rsub|t><around|(|u|)>*<space|0.17em>d*\<xi\>*<around|(|t-u|)>.
  </equation>

  As in case <reference|subsec:discrete_moving_average>,
  <math|<math-up|var><around|{|X<around|(|t|)>|}>\<less\>\<infty\>> implies

  <\equation>
    <big|int><rsub|0><rsup|\<infty\>>h<rsub|t><rsup|2><around|(|u|)>*<space|0.17em>d*u\<less\>\<infty\>
  </equation>

  for all <math|t>.

  <section|The Time-Domain Approach><label|sec:time_domain>

  The basic problem of linear least-squares prediction may be stated as
  follows: the observed values of the process over the semi-infinite interval
  <math|<around|(|-\<infty\>,t|)>> are given and the value of
  <math|X*<around|(|t+m|)>> <math|<around|(|m\<gtr\>0|)>> is to be predicted.
  The predictor <math|<wide|X|~>*<around|(|t+m|)>> is to be chosen as that
  linear combination of <math|<around|{|X<around|(|s|)>,s\<leqslant\>t|}>>
  which is such that

  <\equation>
    <label|eq:prediction_problem>M<around|(|m|)>=E*<around|{|<wide|X|~>*<around|(|t+m|)>-X*<around|(|t+m|)>|}><rsup|2>
  </equation>

  is minimized.

  The existence and uniqueness of the optimum predictor
  <math|<wide|X|~>*<around|(|t+m|)>> can be established by the Hilbert space
  approach, using exactly the same arguments as employed in the stationary
  case (see <cite|Parzen1961>, <cite|Yaglom1962>). (Briefly, one represents
  the process as a curve in a Hilbert space, and shows that
  <math|<wide|X|~>*<around|(|t+m|)>> is the \Pprojection\Q of
  <math|X*<around|(|t+m|)>> on the smallest subspace containing
  <math|<around|{|X<around|(|s|)>,s\<leqslant\>t|}>>.) However, assuming that
  the process has a one-sided moving average form, an explicit expression for
  <math|<wide|X|~>*<around|(|t+m|)>> may easily be obtained in terms of the
  process <math|<around|{|\<xi\><around|(|t|)>|}>>. The continuous and
  discrete cases are treated by essentially the same argument, but the
  details differ and the discrete case is considered first.

  <subsection|Discrete-parameter Processes><label|subsec:discrete_time_domain>

  It is assumed that <math|X<around|(|t|)>> has a one-sided moving average
  representation of the form <eqref|eq:moving_average_discrete>, so that one
  may write

  <\equation>
    <label|eq:X_t_moving_average_form>X<around|(|t|)>=<big|sum><rsub|u=0><rsup|\<infty\>>h<rsub|t><around|(|u|)>*<space|0.17em>\<xi\>*<around|(|t-u|)>=<big|sum><rsub|u=-\<infty\>><rsup|t>h<rsub|t>*<around|(|t-u|)>*<space|0.17em>\<xi\><around|(|u|)>.
  </equation>

  Then

  <\equation>
    <label|eq:X_t_m_expression>X*<around|(|t+m|)>=<big|sum><rsub|u=-\<infty\>><rsup|t>h<rsub|t+m>*<around|(|t+m-u|)>*<space|0.17em>\<xi\><around|(|u|)>+<big|sum><rsub|u=t+1><rsup|t+m>h<rsub|t+m>*<around|(|t+m-u|)>*<space|0.17em>\<xi\><around|(|u|)>.
  </equation>

  Now the predictor <math|<wide|X|~>*<around|(|t+m|)>> is to be chosen as a
  linear combination of <math|<around|{|X<around|(|s|)>,s\<leqslant\>t|}>> of
  the form

  <\equation>
    <label|eq:predictor_form><wide|X|~>*<around|(|t+m|)>=<big|sum><rsub|s=-\<infty\>><rsup|t>b<around|(|s|)>*X<around|(|s|)>.
  </equation>

  However, as each <math|X<around|(|t|)>> is a linear combination of the
  <math|<around|{|\<xi\>*<around|(|t-u|)>|}>>
  <math|<around|(|u\<geqslant\>0|)>>, one may equally well express
  <math|<wide|X|~>*<around|(|t+m|)>> as a linear combination of
  <math|<around|{|\<xi\><around|(|s|)>,s\<leqslant\>t|}>> of the form

  <\equation>
    <label|eq:predictor_xi_form><wide|X|~>*<around|(|t+m|)>=<big|sum><rsub|u=-\<infty\>><rsup|t>a<around|(|u|)>*<space|0.17em>\<xi\><around|(|u|)>.
  </equation>

  The problem now reduces to finding the values of the coefficients
  <math|<around|{|a<around|(|u|)>|}>> which minimize <math|M<around|(|m|)>>,
  and, exactly as in the stationary case, the solution follows immediately
  from <eqref|eq:X_t_m_expression> (cf. <cite|Whittle1963>, p.<nbsp>32;
  <cite|Bartlett1955>, p.<nbsp>199). For, in view of the orthogonality of the
  <math|\<xi\>>'s it follows (either by direct substitution of
  <eqref|eq:predictor_xi_form> and <eqref|eq:X_t_m_expression> in
  <eqref|eq:prediction_problem>, or by noting that the second term in
  <eqref|eq:X_t_m_expression> is orthogonal to the first term) that

  <\equation>
    <label|eq:optimal_predictor><wide|X|~>*<around|(|t+m|)>=<big|sum><rsub|u=-\<infty\>><rsup|t>h<rsub|t+m>*<around|(|t+m-u|)>*<space|0.17em>\<xi\><around|(|u|)>=<big|sum><rsub|u=m><rsup|\<infty\>>h<rsub|t+m><around|(|u|)>*<space|0.17em>\<xi\>*<around|(|t+m-u|)>,
  </equation>

  so that, in terms of <eqref|eq:predictor_xi_form>,

  <\equation>
    a<around|(|u|)>=h<rsub|t+m>*<around|(|t+m-u|)>,
  </equation>

  for all <math|u>. The \Pprediction variance\Q, <math|M<around|(|m|)>>, is
  given by

  <\equation>
    <label|eq:prediction_variance>M<around|(|m|)>=2*\<pi\>*<big|sum><rsub|u=0><rsup|m-1>h<rsub|t+m><rsup|2><around|(|u|)>.
  </equation>

  In practice, only the values of <math|X<around|(|s|)>>
  <math|<around|(|s\<leqslant\>t|)>> are observed, so that in order to
  compute <math|<wide|X|~>*<around|(|t+m|)>> the expression
  <eqref|eq:optimal_predictor> must be expressed in terms of the <math|X>'s
  rather than the <math|\<xi\>>'s. Now write

  <\equation>
    <label|eq:xi_in_terms_of_X>\<xi\><around|(|t|)>=<big|sum><rsub|v=0><rsup|\<infty\>>k<rsub|t><around|(|v|)>*X*<around|(|t-v|)>.
  </equation>

  Then, substituting <eqref|eq:xi_in_terms_of_X> in
  <eqref|eq:X_t_moving_average_form> and equating coefficients of
  <math|\<xi\><around|(|t|)>>, one obtains

  <\equation>
    <label|eq:convolution_relation><big|sum><rsub|v=0><rsup|p>h<rsub|t-v>*<around|(|p-v|)>*k<rsub|t><around|(|v|)>=\<delta\><rsub|p,0><space|1em><around|(|p=0,1,2,\<ldots\>|)>,
  </equation>

  for all <math|t>. Thus, given the sequence
  <math|<around|{|h<rsub|t><around|(|u|)>|}>>, for all <math|t>, one may, in
  principle, solve <eqref|eq:convolution_relation> for
  <math|<around|{|k<rsub|t><around|(|v|)>|}>>. When <math|X<around|(|t|)>> is
  stationary, <math|h<rsub|t><around|(|u|)>> and
  <math|k<rsub|t><around|(|v|)>> are both independent of <math|t> and
  <eqref|eq:convolution_relation> is easily solved by introducing the
  generating functions of the two sequences
  <cite-parenthesized|Whittle1963|p. 32>. In general, there does not appear
  to be any systematic relationship between corresponding terms of the two
  sequences, and the most practical approach would seem to be the method of
  repeated back substitution. That is, if <eqref|eq:convolution_relation> is
  written in detail one has

  <\equation>
    <label|eq:triangular_system>

    <\aligned>
      <tformat|<table|<row|<cell|p=0>|<cell|:<space|1em>h<rsub|t><around|(|0|)>*k<rsub|t><around|(|0|)>=1*<space|1em><text|for
      all >t,>>|<row|<cell|p=1>|<cell|:<space|1em>h<rsub|t><around|(|1|)>*k<rsub|t><around|(|0|)>+h<rsub|t-1><around|(|0|)>*k<rsub|t><around|(|1|)>=0*<space|1em><text|for
      all >t,>>|<row|<cell|p=2>|<cell|:<space|1em>h<rsub|t><around|(|2|)>*k<rsub|t><around|(|0|)>+h<rsub|t-1><around|(|1|)>*k<rsub|t><around|(|1|)>+h<rsub|t-2><around|(|2|)>*k<rsub|t><around|(|2|)>=0*<space|1em><text|for
      all >t,<space|1em><text|etc.>>>>>
    </aligned>
  </equation>

  This system of equations is easily solved, step by step, as it is
  triangular. Thus one finds, for all <math|t>,

  <\equation>
    <\aligned>
      <tformat|<table|<row|<cell|k<rsub|t><around|(|0|)>>|<cell|=1/h<rsub|t><around|(|0|)>,>>|<row|<cell|k<rsub|t><around|(|1|)>>|<cell|=-h<rsub|t><around|(|1|)>/h<rsub|t><around|(|0|)>*h<rsub|t-1><around|(|0|)>,>>|<row|<cell|k<rsub|t><around|(|2|)>>|<cell|=<around|{|-h<rsub|t><around|(|2|)>/h<rsub|t><around|(|0|)>*h<rsub|t-2><around|(|2|)>|}>+<around|{|h<rsub|t><around|(|1|)>*h<rsub|t-1><around|(|1|)>/h<rsub|t><around|(|0|)>*h<rsub|t-1><around|(|0|)>*h<rsub|t-2><around|(|0|)>|}>,>>|<row|<cell|>|<cell|\<cdots\><space|1em><text|etc.>>>>>
    </aligned>
  </equation>

  Alternatively, one may substitute <eqref|eq:X_t_moving_average_form> in
  <eqref|eq:xi_in_terms_of_X> and equate coefficients, obtaining

  <\equation>
    <label|eq:inverse_convolution><big|sum><rsub|v=0><rsup|p>k<rsub|t-v>*<around|(|p-v|)>*h<rsub|t><around|(|v|)>=\<delta\><rsub|p,0><space|1em><around|(|p=0,1,2,\<ldots\>|)>,
  </equation>

  for all <math|t>. <cite|Whittle1965> has pointed out that the two systems
  of equations <eqref|eq:convolution_relation> and
  <eqref|eq:inverse_convolution> are not identical unless the process is
  stationary (in which case both <math|<around|{|h<rsub|t><around|(|u|)>|}>>
  and <math|<around|{|k<rsub|t><around|(|v|)>|}>> are independent of
  <math|t>), but that one set of equations still implies the other. However,
  the triangular form of both <eqref|eq:convolution_relation> and
  <eqref|eq:inverse_convolution> means that these systems of equations are
  ideally suited for numerical solution.

  <subsection|Continuous-parameter Processes><label|subsec:continuous_time_domain>

  The results for continuous-parameter processes are very similar to those
  obtained in the discrete case. Thus one is given
  <math|<around|{|X<around|(|s|)>,-\<infty\>\<less\>s\<leqslant\>t|}>> and
  wishes to predict <math|X*<around|(|t+m|)>> <math|<around|(|m\<gtr\>0|)>>
  by a linear combination of past values, of the form

  <\equation>
    <label|eq:continuous_predictor_integral><wide|X|~>*<around|(|t+m|)>=<big|int><rsub|-\<infty\>><rsup|t>X<around|(|s|)>*b<around|(|s|)>*<space|0.17em>d*s,
  </equation>

  or, equivalently,

  <\equation>
    <label|eq:continuous_predictor_xi><wide|X|~>*<around|(|t+m|)>=<big|int><rsub|-\<infty\>><rsup|t>\<xi\><around|(|u|)>*a<around|(|u|)>*<space|0.17em>d*u.
  </equation>

  Assuming that <math|X<around|(|t|)>> has a moving-average representation of
  the form <eqref|eq:X_t_continuous_integral>, it follows immediately that

  <\equation>
    <label|eq:continuous_optimal_predictor><wide|X|~>*<around|(|t+m|)>=<big|int><rsub|-\<infty\>><rsup|t>h<rsub|t+m>*<around|(|t+m-u|)>*<space|0.17em>\<xi\><around|(|u|)>*<space|0.17em>d*u=<big|int><rsub|m><rsup|\<infty\>>h<rsub|t+m><around|(|u|)>*<space|0.17em>\<xi\>*<around|(|t+m-u|)>*<space|0.17em>d*u.
  </equation>

  In order to express <math|<wide|X|~>*<around|(|t+m|)>> in terms of
  <math|<around|{|X<around|(|s|)>,s\<leqslant\>t|}>> one writes

  <\equation>
    <label|eq:xi_continuous_in_terms_of_X>\<xi\><around|(|t|)>=<big|int><rsub|0><rsup|\<infty\>>k<rsub|t><around|(|v|)>*X*<around|(|t-v|)>*<space|0.17em>d*v,
  </equation>

  and substitutes <eqref|eq:xi_continuous_in_terms_of_X> in
  <eqref|eq:X_t_continuous_integral>. One then obtains

  <\equation>
    <label|eq:integral_equation_1><big|int><rsub|0><rsup|v>h<rsub|t><around|(|u|)>*k<rsub|t-u>*<around|(|v-u|)>*<space|0.17em>d*u=\<delta\><around|(|v|)>,
  </equation>

  for all <math|v\<gtr\>0> and all <math|t>, where
  <math|\<delta\><around|(|v|)>> denotes the Dirac <math|\<delta\>>-function.
  Similarly, substituting <eqref|eq:X_t_continuous_integral> in
  <eqref|eq:xi_continuous_in_terms_of_X>, one finds

  <\equation>
    <label|eq:integral_equation_2><big|int><rsub|0><rsup|u>k<rsub|t><around|(|v|)>*h<rsub|t-v>*<around|(|u-v|)>*<space|0.17em>d*v=\<delta\><around|(|u|)>,
  </equation>

  for all <math|u\<gtr\>0> and all <math|t>. Given the functions
  <math|<around|{|h<rsub|t><around|(|u|)>|}>> (for all <math|t>), the
  functions <math|<around|{|k<rsub|t><around|(|v|)>|}>> may, in principle, be
  determined from either of the above integral equations.

  In certain cases the time-domain approach may be used to obtain an
  expression of the form <eqref|eq:continuous_predictor_integral> or
  <eqref|eq:continuous_predictor_xi> for <math|<wide|X|~>*<around|(|t+m|)>>,
  i.e. an expression in terms of past values of <math|X<around|(|t|)>>,
  without solving either of the systems <eqref|eq:integral_equation_1> or
  <eqref|eq:integral_equation_2> directly. Such cases include uniformly
  modulated processes, and, naturally enough, finite order autoregressive
  models (with time-dependent coefficients). Finite order moving-average
  models (with time-dependent coefficients) can be dealt with also by this
  method, but they are more suited to a frequency-domain approach (see
  Section <reference|sec:frequency_domain>). Some specific examples are now
  discussed.

  <paragraph|Example 1: Uniformly modulated process.> Consider a
  continuous-parameter process of the form

  <\equation>
    <label|eq:uniformly_modulated_process>X<around|(|t|)>=C<around|(|t|)>*<space|0.17em>Y<around|(|t|)>,
  </equation>

  where <math|Y<around|(|t|)>> is a stationary process with spectral density
  function <math|f<rsub|y><around|(|\<omega\>|)>>, say, and
  <math|C<around|(|t|)>> is some given function of <math|t>. Then, with
  respect to the family <math|\<cal-F\>\<equiv\><around|{|e<rsup|i*\<omega\>*t>*C<around|(|t|)>|}>>,
  the evolutionary spectrum of <math|<around|{|X<around|(|t|)>|}>> is given
  by <cite-parenthesized|Priestley1965>

  <\equation>
    <label|eq:evolutionary_spectrum_modulated>f<rsub|t><around|(|\<omega\>|)>=<mid|\|>C<around|(|t|)><mid|\|><rsup|2>f<rsub|y><around|(|\<omega\>|)>.
  </equation>

  Assume that <math|f<rsub|t><around|(|\<omega\>|)>> satisfies condition
  <eqref|eq:condition_C4_star>. Then it follows that

  <\equation>
    <big|int><rsub|-\<infty\>><rsup|\<infty\>><frac|log
    f<rsub|y><around|(|\<omega\>|)>|1+\<omega\><rsup|2>>*<space|0.17em>d*\<omega\>\<gtr\>-\<infty\>,
  </equation>

  so that <math|Y<around|(|t|)>> has a moving-average representation of the
  form

  <\equation>
    <label|eq:moving_average_Y>Y<around|(|t|)>=<big|int><rsub|0><rsup|\<infty\>>g<around|(|u|)>*<space|0.17em>\<xi\>*<around|(|t-u|)>*<space|0.17em>d*u.
  </equation>

  Hence one may write <math|X<around|(|t|)>> in the form
  <eqref|eq:X_t_continuous_integral>, i.e.

  <\equation>
    <label|eq:moving_average_X>X<around|(|t|)>=<big|int><rsub|0><rsup|\<infty\>>h<rsub|t><around|(|u|)>*<space|0.17em>\<xi\>*<around|(|t-u|)>*<space|0.17em>d*u,
  </equation>

  where <math|h<rsub|t><around|(|u|)>=C<around|(|t|)>*g<around|(|u|)>>.
  According to <eqref|eq:continuous_optimal_predictor>, the linear
  least-squares predictor of <math|X*<around|(|t+m|)>> is given by

  <\equation>
    <\aligned>
      <tformat|<table|<row|<cell|<wide|X|~>*<around|(|t+m|)>>|<cell|=<big|int><rsub|m><rsup|\<infty\>>C*<around|(|t+m|)>*g<around|(|u|)>*<space|0.17em>\<xi\>*<around|(|t+m-u|)>*<space|0.17em>d*u>>|<row|<cell|>|<cell|=C*<around|(|t+m|)>*<space|0.17em><wide|Y|~>*<around|(|t+m|)>,>>>>
    </aligned>
  </equation>

  where <math|<wide|Y|~>*<around|(|t+m|)>> is the least-square predictor of
  <math|Y*<around|(|t+m|)>>, given <math|<around|{|Y<around|(|s|)>,s\<leqslant\>t|}>>,
  and may be determined in the usual way. The referee has pointed out that
  this result has a more general form, namely: if

  <\equation>
    X<around|(|t|)>=<big|sum><rsub|u=0><rsup|\<infty\>>a<rsub|t><around|(|u|)>*Y*<around|(|t-u|)>,<space|1em><text|then><space|1em><wide|X|~>*<around|(|t+m|)>=<big|sum><rsub|u=0><rsup|\<infty\>>a<rsub|t+m><around|(|u|)>*Y<rsup|\<ast\>>*<around|(|t+m-u|)>,
  </equation>

  where

  <\equation>
    Y<rsup|\<ast\>><around|(|s|)>=<choice|<tformat|<table|<row|<cell|Y<around|(|s|)>>|<cell|<around|(|s\<leqslant\>t|)>,>>|<row|<cell|<wide|Y|~><around|(|s|)>>|<cell|<around|(|s\<gtr\>t|)>.>>>>>
  </equation>

  For example, using the Wiener predictor (see <cite|Bartlett1955>,
  p.<nbsp>201),

  <\equation>
    <wide|Y|~>*<around|(|t+m|)>=<big|int><rsub|0><rsup|\<infty\>>Y*<around|(|t-u|)>*b<around|(|u|)>*<space|0.17em>d*u,
  </equation>

  where

  <\equation>
    b<around|(|u|)>=<around|(|2*\<pi\>|)><rsup|-1>*<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*\<omega\>*u>*B<around|(|\<omega\>|)>*<space|0.17em>d*\<omega\>,
  </equation>

  and

  <\equation>
    B<around|(|\<omega\>|)>=<frac|e<rsup|i*\<omega\>*m>*<big|int><rsub|m><rsup|\<infty\>>g<around|(|u|)>*e<rsup|-i*\<omega\>*u>*<space|0.17em>d*u|<big|int><rsub|0><rsup|\<infty\>>g<around|(|u|)>*e<rsup|-i*\<omega\>*u>*<space|0.17em>d*u>.
  </equation>

  Thus

  <\equation>
    <wide|X|~>*<around|(|t+m|)>=<big|int><rsub|0><rsup|\<infty\>>X*<around|(|t-u|)>*b<rsup|\<ast\>><around|(|u|)>*<space|0.17em>d*u,
  </equation>

  where

  <\equation>
    b<rsup|\<ast\>><around|(|u|)>=<around|{|C*<around|(|t+m|)>/C*<around|(|t-u|)>|}>*<around|{|<around|(|2*\<pi\>|)><rsup|-1>*<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*\<omega\>*u>*B<around|(|\<omega\>|)>*<space|0.17em>d*\<omega\>|}>.
  </equation>

  <paragraph|Example 2: First-order autoregressive process,
  discrete-parameter.> Suppose <math|<around|{|X<around|(|t|)>|}>> is given
  by

  <\equation>
    <label|eq:first_order_autoregressive>X<around|(|t|)>-\<alpha\><around|(|t|)>*X*<around|(|t-1|)>=\<xi\><around|(|t|)><space|1em><around|(|t=0,\<pm\>1,\<pm\>2,\<ldots\>|)>,
  </equation>

  where <math|<around|{|\<alpha\><around|(|t|)>|}>> is a given sequence with
  <math|<around|\||\<alpha\><around|(|t|)>|\|>\<less\>1> for all <math|t>,
  and <math|<around|{|\<xi\><around|(|t|)>|}>> is an uncorrelated stationary
  process with <math|E<around|{|\<xi\><around|(|t|)>|}>=0>,
  <math|E<around|{|\<xi\><rsup|2><around|(|t|)>|}>=1>. From
  <eqref|eq:first_order_autoregressive> one finds (subject to
  <math|X*<around|(|-\<infty\>|)>=0>)

  <\equation>
    <label|eq:autoregressive_solution>X<around|(|t|)>=<big|sum><rsub|u=0><rsup|\<infty\>>h<rsub|t><around|(|u|)>*<space|0.17em>\<xi\>*<around|(|t-u|)>,
  </equation>

  where

  <\equation>
    h<rsub|t><around|(|u|)>=<choice|<tformat|<table|<row|<cell|\<alpha\><around|(|t|)>*\<alpha\>*<around|(|t-1|)>*\<cdots\>*\<alpha\>*<around|(|t-u+1|)>>|<cell|<around|(|u\<gtr\>0|)>,>>|<row|<cell|1>|<cell|<around|(|u=0|)>.>>>>>
  </equation>

  Hence, according to <eqref|eq:optimal_predictor>, the linear least-squares
  predictor of <math|X*<around|(|t+m|)>> is given by

  <\equation>
    <\aligned>
      <tformat|<table|<row|<cell|<wide|X|~>*<around|(|t+m|)>>|<cell|=<big|sum><rsub|u=m><rsup|\<infty\>>\<alpha\>*<around|(|t+m|)>*\<alpha\>*<around|(|t+m-1|)>*\<cdots\>*\<alpha\>*<around|(|t+m-u+1|)>*<space|0.17em>\<xi\>*<around|(|t+m-u|)>>>|<row|<cell|>|<cell|=<around|{|\<alpha\>*<around|(|t+m|)>*\<cdots\>*\<alpha\>*<around|(|t+1|)>|}>*<big|sum><rsub|u=0><rsup|\<infty\>>\<alpha\><around|(|t|)>*\<cdots\>*\<alpha\>*<around|(|t-u+1|)>*<space|0.17em>\<xi\>*<around|(|t-u|)>>>|<row|<cell|>|<cell|=<around|{|\<alpha\>*<around|(|t+m|)>*\<cdots\>*\<alpha\>*<around|(|t+1|)>|}>*X<around|(|t|)>.>>>>
    </aligned>
  </equation>

  (Note that this is the exact expression for <math|X*<around|(|t+m|)>> when
  <math|\<xi\><around|(|s|)>=0> for all <math|s\<gtr\>t>.)

  <paragraph|Example 3: First-order moving-average process,
  discrete-parameter.> Let <math|<around|{|X<around|(|t|)>|}>> be given by

  <\equation>
    <label|eq:first_order_moving_average>X<around|(|t|)>=\<xi\><around|(|t|)>-\<alpha\><around|(|t|)>*\<xi\>*<around|(|t-1|)>*<space|1em><around|(|t=0,\<pm\>1,\<pm\>2,\<ldots\>|)>,
  </equation>

  with <math|<around|{|\<xi\><around|(|t|)>|}>> as above. Then clearly

  <\equation>
    <wide|X|~>*<around|(|t+m|)>=<choice|<tformat|<table|<row|<cell|-\<alpha\>*<around|(|t+1|)>*<space|0.17em>\<xi\><around|(|t|)>>|<cell|<around|(|m=1|)>,>>|<row|<cell|0>|<cell|<around|(|m\<gtr\>1|)>,>>>>>
  </equation>

  where

  <\equation>
    \<xi\><around|(|t|)>=<big|sum><rsub|v=0><rsup|\<infty\>>k<rsub|t><around|(|v|)>*X*<around|(|t-v|)>,
  </equation>

  with <math|k<rsub|t><around|(|v|)>=\<alpha\><around|(|t|)>*\<alpha\>*<around|(|t-1|)>*\<cdots\>*\<alpha\>*<around|(|t-v+1|)>>.

  <section|The Frequency-Domain Approach><label|sec:frequency_domain>

  An alternative approach based on a generalization of the Wiener-Hopf
  technique for dealing with the prediction of stationary processes is now
  considered. The continuous-parameter case is treated first, and the
  predictor of <math|X*<around|(|t+m|)>> is written in the form

  <\equation>
    <label|eq:frequency_predictor><wide|X|~>*<around|(|t+m|)>=<big|int><rsub|0><rsup|\<infty\>>b<rsub|t><around|(|u|)>*X*<around|(|t-u|)>*<space|0.17em>d*u.
  </equation>

  Note that <eqref|eq:frequency_predictor> is merely a formal way of writing

  <\equation>
    <wide|X|~>*<around|(|t+m|)>=<big|int><rsub|0><rsup|\<infty\>>X*<around|(|t-u|)>*<space|0.17em>d*\<beta\><rsub|t><around|(|u|)>.
  </equation>

  The function <math|b<rsub|t><around|(|u|)>> need not exist in the strict
  sense, as would be the case if, for example,
  <math|<wide|X|~>*<around|(|t+m|)>> involved derivatives of
  <math|X*<around|(|t-u|)>>. Note also that the weight-function
  <math|b<rsub|t><around|(|u|)>> may depend on both <math|t> and <math|m>.
  Now using the evolutionary spectral representation of
  <math|X<around|(|t|)>>, <eqref|eq:X_t_continuous_representation> and
  <eqref|eq:frequency_predictor> may be written

  <\equation>
    <wide|X|~>*<around|(|t+m|)>=<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*\<omega\>*t>*B<rsub|t><around|(|\<omega\>|)>*<space|0.17em>d*z<around|(|\<omega\>|)>,
  </equation>

  where

  <\equation>
    <label|eq:B_t_definition>B<rsub|t><around|(|\<omega\>|)>=<big|int><rsub|0><rsup|\<infty\>>b<rsub|t><around|(|u|)>*\<alpha\><rsub|t-u><around|(|\<omega\>|)>*e<rsup|-i*u*\<omega\>>*<space|0.17em>d*u.
  </equation>

  On the other hand, from <eqref|eq:X_t_continuous_representation>,

  <\equation>
    <label|eq:X_t_m_frequency>X*<around|(|t+m|)>=<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*\<omega\>*<around|(|t+m|)>>*\<alpha\><rsub|t+m><around|(|\<omega\>|)>*<space|0.17em>d*z<around|(|\<omega\>|)>.
  </equation>

  Hence, in virtue of the orthogonality of <math|z<around|(|\<omega\>|)>>,

  <\equation>
    <label|eq:prediction_error_integral>M<around|(|m|)>=E<mid|\|><wide|X|~>*<around|(|t+m|)>-X*<around|(|t+m|)><mid|\|><rsup|2>=<big|int><rsub|-\<infty\>><rsup|\<infty\>><mid|\|>e<rsup|i*\<omega\>*m>*\<alpha\><rsub|t+m><around|(|\<omega\>|)>-B<rsub|t><around|(|\<omega\>|)><mid|\|><rsup|2><space|0.17em>d*\<omega\>.
  </equation>

  One must now choose <math|b<rsub|t><around|(|u|)>> (or, equivalently,
  <math|B<rsub|t><around|(|\<omega\>|)>>) so as to minimize
  <eqref|eq:prediction_error_integral>. As a preliminary step it is first
  shown that, for each <math|t>, the function
  <math|B<rsub|t><around|(|\<omega\>|)>> is a \Pbackward transform\Q, that is
  it may be written as a one-sided Fourier transform of the form

  <\equation>
    <label|eq:B_t_backward_transform>B<rsub|t><around|(|\<omega\>|)>=<around|(|2*\<pi\>|)><rsup|-1>*<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|-i*v*\<omega\>>*K<rsub|t><around|(|v|)>*<space|0.17em>d*v,
  </equation>

  where <math|K<rsub|t><around|(|v|)>=0> for <math|v\<less\>0>. For

  <\equation>
    <\aligned>
      <tformat|<table|<row|<cell|K<rsub|t><around|(|v|)>>|<cell|=<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*\<omega\>*v>*B<rsub|t><around|(|\<omega\>|)>*<space|0.17em>d*\<omega\>>>|<row|<cell|>|<cell|=<big|int><rsub|0><rsup|\<infty\>>b<rsub|t><around|(|u|)><around*|{|<big|int><rsub|0><rsup|\<infty\>>e<rsup|i*\<omega\>*<around|(|v-u|)>>*\<alpha\><rsub|t-u><around|(|\<omega\>|)>*<space|0.17em>d*\<omega\>|}>*d*u.>>>>
    </aligned>
  </equation>

  Since

  <\equation>
    \<alpha\><rsub|t-u><around|(|\<omega\>|)>=<big|int><rsub|0><rsup|\<infty\>>e<rsup|-i*\<omega\>*w>*h<rsub|t-u><around|(|w|)>*<space|0.17em>d*w,
  </equation>

  one has

  <\equation>
    <big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*\<omega\>*<around|(|v-u|)>>*\<alpha\><rsub|t-u><around|(|\<omega\>|)>*<space|0.17em>d*\<omega\>=<choice|<tformat|<table|<row|<cell|h<rsub|t-u>*<around|(|v-u|)>>|<cell|<around|(|u\<leqslant\>v|)>,>>|<row|<cell|0>|<cell|<around|(|u\<gtr\>v|)>.>>>>>
  </equation>

  Hence

  <\equation>
    <label|eq:K_v_definition>K<rsub|t><around|(|v|)>=<big|int><rsub|0><rsup|v>b<rsub|t><around|(|u|)>*h<rsub|t-u>*<around|(|v-u|)>*<space|0.17em>d*u,
  </equation>

  and, in particular, <math|K<rsub|t><around|(|v|)>=0> for <math|v\<less\>0>.

  Now write (for each <math|t>)

  <\equation>
    <label|eq:C1_C2_decomposition>e<rsup|i*\<omega\>*m>*\<alpha\><rsub|t+m><around|(|\<omega\>|)>=C<rsub|t><rsup|<around|(|1|)>><around|(|\<omega\>|)>+C<rsub|t><rsup|<around|(|2|)>><around|(|\<omega\>|)>,
  </equation>

  where, for each <math|t>, <math|C<rsub|t><rsup|<around|(|1|)>><around|(|\<omega\>|)>>
  is a \Pbackward transform\Q, and <math|C<rsub|t><rsup|<around|(|2|)>><around|(|\<omega\>|)>>
  is a \Pforward transform\Q <cite-parenthesized|Bartlett1955|p. 201>. That
  is, write

  <\equation>
    <label|eq:C1_definition>C<rsub|t><rsup|<around|(|1|)>><around|(|\<omega\>|)>=<around|(|2*\<pi\>|)><rsup|-1>*<big|int><rsub|0><rsup|\<infty\>>e<rsup|-i*\<omega\>*u><around*|[|<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*\<theta\>*u>*<around|{|e<rsup|i*\<theta\>*m>*\<alpha\><rsub|t+m><around|(|\<theta\>|)>|}>*<space|0.17em>d*\<theta\>|]>*d*u,
  </equation>

  and

  <\equation>
    <label|eq:C2_definition>C<rsub|t><rsup|<around|(|2|)>><around|(|\<omega\>|)>=<around|(|2*\<pi\>|)><rsup|-1>*<big|int><rsub|-\<infty\>><rsup|0>e<rsup|-i*\<omega\>*u><around*|[|<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*\<theta\>*u>*<around|{|e<rsup|i*\<theta\>*m>*\<alpha\><rsub|t+m><around|(|\<theta\>|)>|}>*<space|0.17em>d*\<theta\>|]>*d*u.
  </equation>

  Then, for each <math|t>, <math|<around|{|C<rsub|t><rsup|<around|(|1|)>><around|(|\<omega\>|)>-B<rsub|t><around|(|\<omega\>|)>|}>>
  and <math|C<rsub|t><rsup|<around|(|2|)>><around|(|\<omega\>|)>> are
  orthogonal with respect to <math|d*\<omega\>> integration, and from
  <eqref|eq:prediction_error_integral> one has

  <\equation>
    <label|eq:minimized_error>M<around|(|m|)>=<big|int><rsub|-\<infty\>><rsup|\<infty\>><mid|\|>C<rsub|t><rsup|<around|(|1|)>><around|(|\<omega\>|)>-B<rsub|t><around|(|\<omega\>|)><mid|\|><rsup|2><space|0.17em>d*\<omega\>+<big|int><rsub|-\<infty\>><rsup|\<infty\>><mid|\|>C<rsub|t><rsup|<around|(|2|)>><around|(|\<omega\>|)><mid|\|><rsup|2><space|0.17em>d*\<omega\>.
  </equation>

  It follows immediately that the minimum of <math|M<around|(|m|)>> is
  attained when <math|B<rsub|t><around|(|\<omega\>|)>> is given by

  <\equation>
    <label|eq:optimal_B_t>B<rsub|t><around|(|\<omega\>|)>=C<rsub|t><rsup|<around|(|1|)>><around|(|\<omega\>|)>,
  </equation>

  for all <math|t>, and the prediction variance is then given by

  <\equation>
    <label|eq:prediction_variance_C2>M<around|(|m|)>=<big|int><rsub|-\<infty\>><rsup|\<infty\>><mid|\|>C<rsub|t><rsup|<around|(|2|)>><around|(|\<omega\>|)><mid|\|><rsup|2><space|0.17em>d*\<omega\>.
  </equation>

  It now remains to solve <eqref|eq:optimal_B_t> to find the functions
  <math|<around|{|b<rsub|t><around|(|u|)>|}>>. Taking Fourier transforms of
  both sides one finds, for <math|v\<gtr\>0>,

  <\equation>
    <\aligned>
      <tformat|<table|<row|<cell|K<rsub|t><around|(|v|)>>|<cell|=<big|int><rsub|-\<infty\>><rsup|\<infty\>>e<rsup|i*\<theta\>*<around|(|v+m|)>>*\<alpha\><rsub|t+m><around|(|\<theta\>|)>*<space|0.17em>d*\<theta\>*<space|1em><text|for
      all >t,>>|<row|<cell|>|<cell|=h<rsub|t+m>*<around|(|v+m|)>.>>>>
    </aligned>
  </equation>

  Hence, using <eqref|eq:K_v_definition>, one finds

  <\equation>
    <label|eq:integral_equation_b_t><big|int><rsub|0><rsup|v>b<rsub|t><around|(|u|)>*h<rsub|t-u>*<around|(|v-u|)>*<space|0.17em>d*u=h<rsub|t+m>*<around|(|v+m|)>,
  </equation>

  for all <math|t> and all <math|v\<gtr\>0>. Given the form of the
  evolutionary spectral density function <math|f<rsub|t><around|(|\<omega\>|)>>,
  for all <math|t>, one may (in principle) determine the function
  <math|h<rsub|t><around|(|u|)>>, for all <math|t>, and hence find the
  optimum weight-function <math|<around|{|b<rsub|t><around|(|u|)>|}>> by
  solving the integral equation <eqref|eq:integral_equation_b_t>.

  Equation <eqref|eq:integral_equation_b_t>, being an integral equation of
  the first kind, may be solved explicitly for
  <math|<around|{|b<rsub|t><around|(|u|)>|}>>. (Note that in the stationary
  case <math|f<rsub|t><around|(|\<omega\>|)>>, and consequently
  <math|h<rsub|t><around|(|u|)>>, are both independent of <math|t>, so that
  <eqref|eq:integral_equation_b_t> may then be solved immediately by noting
  that the left-hand side is the convolution of
  <math|b<rsub|t><around|(|u|)>> and <math|h<rsub|t><around|(|u|)>>.) In the
  general case one may solve <eqref|eq:integral_equation_b_t> by first
  expressing it as an integral equation of the second kind. Thus, if it is
  assumed that

  <\equation>
    h<rsub|t-v><around|(|0|)>\<neq\>0*<text|for all >v*<text|in
    ><around|(|0,\<infty\>|)><text|and ><frac|\<partial\>*h<rsub|t-u>*<around|(|v-u|)>|\<partial\>*v>=h<rsub|t-u,v><rprime|'>*<around|(|v-u|)>*<text|exists
    and is continuous in >u*<text|and >v*<around|(|u\<less\>v|)>,
  </equation>

  then by differentiating both sides of <eqref|eq:integral_equation_b_t> with
  respect to <math|v> one finds

  <\equation>
    <label|eq:differentiated_equation>h<rsub|t-v><around|(|0|)>*b<rsub|t><around|(|v|)>+<big|int><rsub|0><rsup|v>h<rsub|t-u,v><rprime|'>*<around|(|v-u|)>*b<rsub|t><around|(|u|)>*<space|0.17em>d*u=h<rsub|t+m,v><rprime|'>*<around|(|v+m|)>*<space|1em><around|(|v\<geqslant\>0|)>,
  </equation>

  or

  <\equation>
    <label|eq:volterra_equation>b<rsub|t><around|(|v|)>+<big|int><rsub|0><rsup|v><frac|h<rsub|t-u,v><rprime|'>*<around|(|v-u|)>|h<rsub|t-v><around|(|0|)>>*b<rsub|t><around|(|u|)>*<space|0.17em>d*u=<frac|h<rsub|t+m,v><rprime|'>*<around|(|v+m|)>|h<rsub|t-v><around|(|0|)>>.
  </equation>

  The solution of <eqref|eq:volterra_equation> is
  <cite-parenthesized|Tricomi1957|p. 10>

  <\equation>
    <label|eq:volterra_solution>b<rsub|t><around|(|v|)>=<frac|h<rsub|t+m,v><rprime|'>*<around|(|v+m|)>|h<rsub|t-v><around|(|0|)>>+<big|int><rsub|0><rsup|v>H<rsub|t><rsup|\<ast\>><around|(|v,u,-1|)><around*|{|<frac|h<rsub|t+m,v><rprime|'>*<around|(|u+m|)>|h<rsub|t-u><around|(|0|)>>|}>*d*u,
  </equation>

  where, for each <math|t>, the \Presolvent kernel\Q
  <math|H<rsub|t><rsup|\<ast\>><around|(|v,u,-1|)>> is given by

  <\equation>
    <label|eq:resolvent_kernel>H<rsub|t><rsup|\<ast\>><around|(|v,u,-1|)>=-<big|sum><rsub|p=0><rsup|\<infty\>><around|(|-1|)><rsup|p>*K<rsub|t,p+1><rsup|\<ast\>><around|(|u,v|)>,
  </equation>

  and the \Piterated kernels\Q <math|K<rsub|t,p><rsup|\<ast\>><around|(|u,v|)>>
  are given by

  <\equation>
    K<rsub|t,p+1><rsup|\<ast\>><around|(|u,v|)>=<big|int><rsub|u><rsup|v>K<rsub|t,1><rsup|\<ast\>><around|(|u,z|)>*K<rsub|t,p><rsup|\<ast\>><around|(|z,v|)>*<space|0.17em>d*z<space|1em><around|(|p=1,2,\<ldots\>|)>,
  </equation>

  with

  <\equation>
    K<rsub|t,1><rsup|\<ast\>><around|(|u,v|)>=<frac|h<rsub|t-u,v><rprime|'>*<around|(|v-u|)>|h<rsub|t-v><around|(|0|)>>.
  </equation>

  Equation <eqref|eq:volterra_solution> provides an analytic expression for
  <math|<around|{|b<rsub|t><around|(|u|)>|}>>, but in numerical work it may
  well be more convenient to solve the integral equation
  <eqref|eq:integral_equation_b_t> directly.

  For discrete-parameter processes the predictor
  <math|<wide|X|~>*<around|(|t+m|)>> will be of the form

  <\equation>
    <label|eq:discrete_predictor_form><wide|X|~>*<around|(|t+m|)>=<big|sum><rsub|u=0><rsup|\<infty\>>b<rsub|t><around|(|u|)>*X*<around|(|t-u|)>,
  </equation>

  so that, using the spectral representation <eqref|eq:X_t_representation>,

  <\equation>
    <label|eq:discrete_prediction_error>M<around|(|m|)>=<big|int><rsub|-\<pi\>><rsup|\<pi\>><mid|\|>e<rsup|i*\<omega\>*m>*\<alpha\><rsub|t+m><around|(|\<omega\>|)>-B<rsub|t><around|(|\<omega\>|)><mid|\|><rsup|2><space|0.17em>d*\<omega\>,
  </equation>

  where now

  <\equation>
    <label|eq:B_t_discrete>B<rsub|t><around|(|\<omega\>|)>=<big|sum><rsub|u=0><rsup|\<infty\>>b<rsub|t><around|(|u|)>*\<alpha\><rsub|t-u><around|(|\<omega\>|)>*e<rsup|-i*u*\<omega\>>.
  </equation>

  Following a similar argument to that used above, one may show that
  <math|M<around|(|m|)>> is minimized when the sequence
  <math|<around|{|b<rsub|t><around|(|u|)>|}>> is given by

  <\equation>
    <label|eq:discrete_convolution><big|sum><rsub|u=0><rsup|v>b<rsub|t><around|(|u|)>*h<rsub|t-u>*<around|(|v-u|)>=h<rsub|t+m>*<around|(|v+m|)>*<space|1em><around|(|v=0,1,2,\<ldots\>;t=0,\<pm\>1,\<pm\>2,\<ldots\>|)>.
  </equation>

  Here, <math|h<rsub|t><around|(|u|)>> <math|<around|(|u=0,1,2,\<ldots\>|)>>
  is the sequence defined by <eqref|eq:alpha_t_fourier>.

  The system of equations <eqref|eq:discrete_convolution> is again
  \Ptriangular\Q (cf. <eqref|eq:triangular_system>) so that it is easily
  solved for <math|<around|{|b<rsub|t><around|(|u|)>|}>> by repeated
  back-substitution. In fact, this approach has been tried on a numerical
  example (using an ATLAS computer) and has proved quite successful.

  It is interesting to note that had one attempted to obtain
  <math|<around|{|b<rsub|t><around|(|u|)>|}>> directly from the covariance
  function <math|R<around|(|s,t|)>\<equiv\>E*<around|{|X<around|(|s|)>*X<rsup|\<ast\>><around|(|t|)>|}>>,
  one would have obtained the well-known set of equations (see
  <cite|Bendat1959>, p.<nbsp>149),

  <\equation>
    <label|eq:covariance_equation><big|sum><rsub|u=0><rsup|\<infty\>>b<rsub|t><around|(|u|)>*R<around|(|t-u,t-v|)>=R<around|(|t-v,t+m|)>*<space|1em><around|(|v\<geqslant\>0|)>.
  </equation>

  (In the continuous case one obtains the corresponding integral equation.)

  The above system does not lend itself to either an analytic or a numerical
  solution and the spectral approach (cf. <eqref|eq:integral_equation_b_t>,
  <eqref|eq:discrete_convolution>) may be regarded as a method of reducing
  <eqref|eq:covariance_equation> to \Ptriangular\Q form.

  The methods of this section are now applied to some examples discussed in
  Section <reference|subsec:continuous_time_domain>.

  <paragraph|Example 4.> Consider the first-order autoregressive process
  (discrete-parameter) of <eqref|eq:first_order_autoregressive>. Using the
  form of <math|<around|{|h<rsub|t><around|(|u|)>|}>> given by
  <eqref|eq:autoregressive_solution> in <eqref|eq:discrete_convolution>, one
  obtains

  <\equation>
    b<rsub|t><around|(|0|)>+<big|sum><rsub|u=1><rsup|v>b<rsub|t><around|(|u|)>*\<alpha\>*<around|(|t-u|)>*\<alpha\>*<around|(|t-u-1|)>*\<cdots\>*\<alpha\>*<around|(|t-v+1|)>=\<alpha\>*<around|(|t+m|)>*\<alpha\>*<around|(|t+m-1|)>*\<cdots\>*\<alpha\>*<around|(|t-v+1|)>*<space|1em><around|(|v=0,1,2,\<ldots\>|)>.
  </equation>

  Solving this system step by step, one obtains

  <\equation>
    <choice|<tformat|<table|<row|<cell|b<rsub|t><around|(|0|)>=\<alpha\>*<around|(|t+m|)>*\<alpha\>*<around|(|t+m-1|)>*\<cdots\>*\<alpha\>*<around|(|t+1|)>,>>|<row|<cell|b<rsub|t><around|(|u|)>=0*<space|1em><around|(|u\<gtr\>0|)>.>>>>>
  </equation>

  Hence

  <\equation>
    <wide|X|~>*<around|(|t+m|)>=\<alpha\>*<around|(|t+m|)>*\<alpha\>*<around|(|t+m-1|)>*\<cdots\>*\<alpha\>*<around|(|t+1|)>*X<around|(|t|)>,
  </equation>

  in agreement with Example 2.

  <paragraph|Example 5.> Consider now the moving-average process
  (discrete-parameter) of <eqref|eq:first_order_moving_average>. For this
  process,

  <\equation>
    h<rsub|t><around|(|u|)>=<choice|<tformat|<table|<row|<cell|1>|<cell|<around|(|u=0|)>,>>|<row|<cell|-\<alpha\><around|(|t|)>>|<cell|<around|(|u=1|)>,>>|<row|<cell|0>|<cell|<around|(|u\<gtr\>1|)>,>>>>>
  </equation>

  for all <math|t>. Substituting this expression in
  <eqref|eq:discrete_convolution>, one finds

  <\equation>
    b<rsub|t><around|(|0|)>=<choice|<tformat|<table|<row|<cell|-\<alpha\>*<around|(|t+1|)>>|<cell|<around|(|m=1|)>,>>|<row|<cell|0>|<cell|<around|(|m\<gtr\>1|)>,>>>>>
  </equation>

  and

  <\equation>
    b<rsub|t><around|(|u|)>*h<rsub|t-u><around|(|1|)>+b<rsub|t>*<around|(|u+1|)>*h<rsub|t-u><around|(|0|)>=0*<space|1em><around|(|u=1,2,\<ldots\>|)>
  </equation>

  for all <math|m>. The solution of this set of equations is, for all
  <math|u>,

  <\equation>
    b<rsub|t><around|(|u|)>=<choice|<tformat|<table|<row|<cell|-\<alpha\>*<around|(|t+1|)>*\<alpha\><around|(|t|)>*\<cdots\>*\<alpha\>*<around|(|t-u+1|)>>|<cell|<around|(|m=1|)>,>>|<row|<cell|0>|<cell|<around|(|m\<gtr\>1|)>,>>>>>
  </equation>

  so that

  <\equation>
    <wide|X|~>*<around|(|t+m|)>=<choice|<tformat|<table|<row|<cell|-<big|sum><rsub|u=0><rsup|\<infty\>>\<alpha\>*<around|(|t+1|)>*\<alpha\><around|(|t|)>*\<cdots\>*\<alpha\>*<around|(|t-u+1|)>*X<around|(|t|)>>|<cell|<around|(|m=1|)>,>>|<row|<cell|0>|<cell|<around|(|m\<gtr\>1|)>,>>>>>
  </equation>

  in agreement with Example 3.

  <section|Discussion><label|sec:discussion>

  As mentioned in Section <reference|sec:introduction>, this paper is
  concerned primarily with the problem of determining the optimum predictor
  on the assumption that the second-order properties of the process are fully
  known. However, it has been shown that the predictor
  <math|<wide|X|~>*<around|(|t+m|)>> is determined uniquely by the form of
  the evolutionary spectra <math|<around|{|f<rsub|t><around|(|\<omega\>|)>|}>>,
  so that in cases where there is no precise knowledge of the underlying
  model the problem may be attacked by first estimating the functions
  <math|<around|{|f<rsub|t><around|(|\<omega\>|)>|}>>. It will be seen from
  Section <reference|sec:frequency_domain> that
  <math|<wide|X|~>*<around|(|t+m|)>> depends on the form of
  <math|h<rsub|t+m><around|(|u|)>>, i.e. on the form of the evolutionary
  spectrum at the future time point <math|<around|(|t+m|)>>. In a purely
  empirical analysis, one would not, of course, be able to estimate
  <math|f<rsub|t+m><around|(|\<omega\>|)>> directly from observation
  extending only up to time <math|t>, and one would have to assume that the
  spectra were changing with sufficient \Psmoothness\Q over time to enable
  the form of <math|f<rsub|t+m><around|(|\<omega\>|)>> to be inferred from
  the spectra which have been estimated up to time <math|t>. If the
  prediction step <math|m> is much smaller than the characteristic width
  <math|B<rsub|X>> of the process (see <cite|Priestley1965>), it would be a
  reasonable approximation to replace <math|f<rsub|t+m><around|(|\<omega\>|)>>
  by <math|f<rsub|t><around|(|\<omega\>|)>>\Vthe most recently available
  spectrum. In fact, it seems clear intuitively that the very nature of a
  non-stationary process precludes long-range prediction, unless one is
  prepared to make assumptions about the character of the non-stationarity.
  Consequently, if <math|m\<gtr\>B<rsub|X>> one would have to extrapolate the
  available spectra to the time point <math|<around|(|t+m|)>>. This
  extrapolation could be performed on the spectral ordinates themselves (by
  fitting suitable functions of <math|t> to a range of values of
  <math|\<omega\>>), but in general one would presumably start from a model
  of the process which determines the form of the evolutionary spectra in
  terms of a set of time-varying parameters
  <math|<around|{|\<alpha\><rsub|i><around|(|t|)>|}>>, say, and then
  extrapolate the values of these parameters. (Thus, for the model of Example
  2, the <math|<around|{|f<rsub|t><around|(|\<omega\>|)>|}>> may be expressed
  in terms of the time-varying parameter <math|\<alpha\><around|(|t|)>>.) If
  the model specifies further the functional time-dependence of the
  <math|<around|{|\<alpha\><rsub|i><around|(|t|)>|}>> in terms of another set
  of constant parameters, <math|<around|{|\<beta\><rsub|j>|}>>, say, then the
  extrapolation is a straightforward problem and involves merely the
  estimation of the <math|<around|{|\<beta\><rsub|j>|}>>. (For example, in
  some cases one may postulate that the <math|<around|{|\<alpha\><rsub|i><around|(|t|)>|}>>
  are periodic functions of <math|t> with known periodicities.) If, on the
  other hand, the functional form of the <math|<around|{|\<alpha\><rsub|i><around|(|t|)>|}>>
  is not specified by the model, the extrapolation would have to be performed
  by regression techniques.

  <\thebibliography|9>
    <bibitem|Doob1953>Doob, J.<nbsp>L. (1953). <em|Stochastic Processes>. New
    York: Wiley.

    <bibitem|Bartlett1955>Bartlett, M.<nbsp>S. (1955). <em|An Introduction to
    Stochastic Processes>. Cambridge: University Press.

    <bibitem|Grenander1957>Grenander, U. and Rosenblatt, M. (1957).
    <em|Statistical Analysis of Stationary Time Series>. New York: Wiley.

    <bibitem|Yaglom1962>Yaglom, A.<nbsp>M. (1962). <em|An Introduction to the
    Theory of Stationary Random Functions>. Englewood Cliffs, N.J.:
    Prentice-Hall.

    <bibitem|Whittle1965>Whittle, P. (1965). Recursive relations for
    predictors of non-stationary processes.
    <em|J.R.<nbsp>Statist.<nbsp>Soc.<nbsp>B>, <with|font-series|bold|27>,
    523\U532.

    <bibitem|Parzen1961>Parzen, E. (1961). An approach to time series
    analysis. <em|Ann.<nbsp>Math.<nbsp>Statist.>, <with|font-series|bold|32>,
    951\U989.

    <bibitem|Cramer1961a>Cramér, H. (1961a). On some classes of
    non-stationary processes. <em|Proc.<nbsp>4th Berkeley
    Symp.<nbsp>Math.<nbsp>Statist.<nbsp>& Prob.>, <with|font-series|bold|2>,
    57\U78.

    <bibitem|Cramer1961b>Cramér, H. (1961b). On the structure of purely
    non-deterministic stochastic processes. <em|Ark.<nbsp>Mat.>,
    <with|font-series|bold|19>, 249\U266.

    <bibitem|Davis1952>Davis, R.<nbsp>C. (1952). On the theory of prediction
    of non-stationary stochastic processes. <em|J.<nbsp>Appl.<nbsp>Phys.>,
    <with|font-series|bold|23>, 1047\U1053.

    <bibitem|Booton1952>Booton, R.<nbsp>C. (1952). An optimization theory for
    time-varying linear systems with nonstationary statistical inputs.
    <em|Proc.<nbsp>Inst.<nbsp>Radio Engrs>, <with|font-series|bold|40>,
    977\U981.

    <bibitem|Zadeh1953>Zadeh, L.<nbsp>A. (1953). Optimum non-linear filters.
    <em|J.<nbsp>Appl.<nbsp>Phys.>, <with|font-series|bold|24>.

    <bibitem|Bendat1956>Bendat, J.<nbsp>S. (1956). A general theory of linear
    prediction and filtering. <em|J.<nbsp>Soc.<nbsp>Industr.<nbsp>Appl.<nbsp>Math.>,
    <with|font-series|bold|4>, 131\U151.

    <bibitem|Bendat1957>Bendat, J.<nbsp>S. (1957). Exact integral equation
    solutions and synthesis for a large class of optimum time variable linear
    filters. <em|Trans.<nbsp>Inst.<nbsp>Radio Engrs>, IT-3, 71\U80.

    <bibitem|Bendat1959>Bendat, J.<nbsp>S. (1959). <em|Principles and
    Applications of Random Noise Theory>. New York: Wiley.

    <bibitem|Kalman1960>Kalman, R.<nbsp>E. (1960). A new approach to linear
    filtering and prediction problems. <em|J.<nbsp>Basic
    Eng.<nbsp>(Trans.<nbsp>A.S.M.E., Series<nbsp>D)>,
    <with|font-series|bold|82>, 35\U45.

    <bibitem|Granger1964>Granger, C.<nbsp>W.<nbsp>J. and Hatanaka, M. (1964).
    <em|Spectral Analysis of Economic Time Series>. Princeton: University
    Press.

    <bibitem|Priestley1965>Priestley, M.<nbsp>B. (1965). Evolutionary spectra
    and non-stationary processes. <em|J.R.<nbsp>Statist.<nbsp>Soc.<nbsp>B>,
    <with|font-series|bold|27>, 204\U237.

    <bibitem|Priestley1966>Priestley, M.<nbsp>B. (1966). Design relations for
    non-stationary processes. <em|J.R.<nbsp>Statist.<nbsp>Soc.<nbsp>B>,
    <with|font-series|bold|28>, 228\U240.

    <bibitem|Whittle1963>Whittle, P. (1963). <em|Prediction and Regulation>.
    London: English Universities Press.

    <bibitem|Tricomi1957>Tricomi, F.<nbsp>G. (1957). <em|Integral Equations>.
    New York: Wiley.
  </thebibliography>
</body>

<\initial>
  <\collection>
    <associate|page-height|auto>
    <associate|page-medium|paper>
    <associate|page-type|letter>
    <associate|page-width|auto>
  </collection>
</initial>

<\references>
  <\collection>
    <associate|auto-1|<tuple|1|1|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-10|<tuple|2|10|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-11|<tuple|3|10|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-12|<tuple|5|10|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-13|<tuple|1|14|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-14|<tuple|2|14|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-15|<tuple|6|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-16|<tuple|6|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-2|<tuple|2|2|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-3|<tuple|3|2|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-4|<tuple|3.1|3|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-5|<tuple|3.2|4|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-6|<tuple|4|6|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-7|<tuple|4.1|6|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-8|<tuple|4.2|8|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|auto-9|<tuple|1|8|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Bartlett1955|<tuple|Bartlett1955|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Bendat1956|<tuple|Bendat1956|16|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Bendat1957|<tuple|Bendat1957|16|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Bendat1959|<tuple|Bendat1959|16|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Booton1952|<tuple|Booton1952|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Cramer1961a|<tuple|Cramer1961a|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Cramer1961b|<tuple|Cramer1961b|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Davis1952|<tuple|Davis1952|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Doob1953|<tuple|Doob1953|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Granger1964|<tuple|Granger1964|16|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Grenander1957|<tuple|Grenander1957|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Kalman1960|<tuple|Kalman1960|16|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Parzen1961|<tuple|Parzen1961|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Priestley1965|<tuple|Priestley1965|16|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Priestley1966|<tuple|Priestley1966|16|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Tricomi1957|<tuple|Tricomi1957|16|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Whittle1963|<tuple|Whittle1963|16|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Whittle1965|<tuple|Whittle1965|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Yaglom1962|<tuple|Yaglom1962|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|bib-Zadeh1953|<tuple|Zadeh1953|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:A_t_fourier|<tuple|10|3|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:B_t_backward_transform|<tuple|77|11|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:B_t_definition|<tuple|74|11|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:B_t_discrete|<tuple|99|13|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:C1_C2_decomposition|<tuple|82|12|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:C1_definition|<tuple|83|12|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:C2_definition|<tuple|84|12|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:K_v_definition|<tuple|81|11|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:X_t_continuous_integral|<tuple|30|5|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:X_t_continuous_moving_average|<tuple|29|5|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:X_t_continuous_representation|<tuple|23|5|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:X_t_m_expression|<tuple|34|6|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:X_t_m_frequency|<tuple|75|11|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:X_t_moving_average_form|<tuple|33|6|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:X_t_representation|<tuple|12|3|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:alpha_t_continuous_fourier|<tuple|24|5|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:alpha_t_fourier|<tuple|14|3|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:alpha_t_squared|<tuple|13|3|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:autoregressive_solution|<tuple|65|10|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:condition_C1|<tuple|7|3|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:condition_C2|<tuple|1|3|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:condition_C3|<tuple|11|3|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:condition_C3_star|<tuple|22|5|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:condition_C4|<tuple|15|4|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:condition_C4_star|<tuple|26|5|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:continuous_A_t_fourier|<tuple|21|5|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:continuous_condition_C1_star|<tuple|20|4|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:continuous_optimal_predictor|<tuple|47|8|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:continuous_predictor_integral|<tuple|45|8|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:continuous_predictor_xi|<tuple|46|8|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:convolution_relation|<tuple|41|7|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:covariance_equation|<tuple|101|14|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:differentiated_equation|<tuple|91|13|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:discrete_convolution|<tuple|100|13|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:discrete_prediction_error|<tuple|98|13|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:discrete_predictor_form|<tuple|97|13|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:evolutionary_representation_continuous|<tuple|1|2|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:evolutionary_representation_discrete|<tuple|4|2|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:evolutionary_spectrum_continuous|<tuple|3|2|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:evolutionary_spectrum_discrete|<tuple|5|2|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:evolutionary_spectrum_modulated|<tuple|52|8|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:first_order_autoregressive|<tuple|64|10|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:first_order_moving_average|<tuple|68|10|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:frequency_predictor|<tuple|71|10|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:integral_equation_1|<tuple|49|8|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:integral_equation_2|<tuple|50|8|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:integral_equation_b_t|<tuple|89|12|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:inverse_convolution|<tuple|44|7|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:minimized_error|<tuple|85|12|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:moving_average_X|<tuple|55|9|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:moving_average_Y|<tuple|54|9|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:moving_average_density|<tuple|6|3|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:moving_average_discrete|<tuple|18|4|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:optimal_B_t|<tuple|86|12|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:optimal_predictor|<tuple|37|6|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:oscillatory_condition|<tuple|2|2|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:prediction_error_integral|<tuple|76|11|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:prediction_problem|<tuple|32|6|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:prediction_variance|<tuple|39|7|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:prediction_variance_C2|<tuple|87|12|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:predictor_form|<tuple|35|6|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:predictor_xi_form|<tuple|36|6|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:psi_fourier|<tuple|9|3|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:psi_squared|<tuple|8|3|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:resolvent_kernel|<tuple|94|13|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:triangular_system|<tuple|42|7|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:uniformly_modulated_process|<tuple|51|8|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:variance_condition|<tuple|19|4|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:volterra_equation|<tuple|92|13|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:volterra_solution|<tuple|93|13|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:xi_continuous_in_terms_of_X|<tuple|48|8|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:xi_continuous_process|<tuple|27|5|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:xi_continuous_properties|<tuple|28|5|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:xi_in_terms_of_X|<tuple|40|7|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:xi_process|<tuple|16|4|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|eq:xi_properties|<tuple|17|4|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|sec:discussion|<tuple|6|15|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|sec:evolutionary_spectral|<tuple|2|2|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|sec:frequency_domain|<tuple|5|10|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|sec:introduction|<tuple|1|1|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|sec:moving_average|<tuple|3|2|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|sec:time_domain|<tuple|4|6|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|subsec:continuous_moving_average|<tuple|3.2|4|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|subsec:continuous_time_domain|<tuple|4.2|8|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|subsec:discrete_moving_average|<tuple|3.1|3|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|subsec:discrete_time_domain|<tuple|4.1|6|../../.TeXmacs/texts/scratch/no_name_34.tm>>
    <associate|thm:moving_average_discrete|<tuple|1|4|../../.TeXmacs/texts/scratch/no_name_34.tm>>
  </collection>
</references>

<\auxiliary>
  <\collection>
    <\associate|bib>
      Doob1953

      Bartlett1955

      Grenander1957

      Yaglom1962

      Whittle1965

      Parzen1961

      Cramer1961a

      Davis1952

      Booton1952

      Zadeh1953

      Bendat1956

      Kalman1960

      Whittle1965

      Priestley1965

      Priestley1965

      Priestley1966

      Granger1964

      Priestley1965

      Whittle1963

      Whittle1963

      Parzen1961

      Yaglom1962

      Whittle1963

      Bartlett1955

      Whittle1965

      Bartlett1955

      Bendat1959

      Priestley1965
    </associate>
    <\associate|toc>
      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|1<space|2spc>Introduction>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-1><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|2<space|2spc>Evolutionary
      Spectral Representations> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-2><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|3<space|2spc>Moving-Average
      Representations for Oscillatory Processes>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-3><vspace|0.5fn>

      <with|par-left|<quote|1tab>|3.1<space|2spc>Discrete-parameter Processes
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-4>>

      <with|par-left|<quote|1tab>|3.2<space|2spc>Continuous-parameter
      Processes <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-5>>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|4<space|2spc>The
      Time-Domain Approach> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-6><vspace|0.5fn>

      <with|par-left|<quote|1tab>|4.1<space|2spc>Discrete-parameter Processes
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-7>>

      <with|par-left|<quote|1tab>|4.2<space|2spc>Continuous-parameter
      Processes <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-8>>

      <with|par-left|<quote|3tab>|Example 1: Uniformly modulated process.
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-9>>

      <with|par-left|<quote|3tab>|Example 2: First-order autoregressive
      process, discrete-parameter. <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-10>>

      <with|par-left|<quote|3tab>|Example 3: First-order moving-average
      process, discrete-parameter. <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-11>>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|5<space|2spc>The
      Frequency-Domain Approach> <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-12><vspace|0.5fn>

      <with|par-left|<quote|3tab>|Example 4.
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-13>>

      <with|par-left|<quote|3tab>|Example 5.
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-14>>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|6<space|2spc>Discussion>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-15><vspace|0.5fn>

      <vspace*|1fn><with|font-series|<quote|bold>|math-font-series|<quote|bold>|Bibliography>
      <datoms|<macro|x|<repeat|<arg|x>|<with|font-series|medium|<with|font-size|1|<space|0.2fn>.<space|0.2fn>>>>>|<htab|5mm>>
      <no-break><pageref|auto-16><vspace|0.5fn>
    </associate>
  </collection>
</auxiliary>